In [ ]:
#Installations
!pip install PyPDF2
!pip install PyMuPDF
!pip install keybert
!pip install rouge
!pip install textacy
!pip install pdfplumber
!pip install rdflib
!pip install bert-score
!pip install autocorrect
!pip install sentence-transformers
!pip install faiss-cpu --no-cache

Collecting PyPDF2
  Downloading pypdf2-3.0.1-py3-none-any.whl (232 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 232.6/232.6 kB 6.1 MB/s eta 0:00:00
Installing collected packages: PyPDF2
Successfully installed PyPDF2-3.0.1
Collecting PyMuPDF
  Downloading PyMuPDF-1.23.5-cp310-none-manylinux2014_x86_64.whl (4.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.3/4.3 MB 53.1 MB/s eta 0:00:00
Collecting PyMuPDFb==1.23.5 (from PyMuPDF)
  Downloading PyMuPDFb-1.23.5-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (30.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 30.6/30.6 MB 59.3 MB/s eta 0:00:00
Installing collected packages: PyMuPDFb, PyMuPDF
Successfully installed PyMuPDF-1.23.5 PyMuPDFb-1.23.5
Collecting keybert
  Downloading keybert-0.8.3.tar.gz (29 kB)
  Preparing metadata (setup.py) ... done
Collecting sentence-transformers>=0.3.8 (from keybert)
  Downloading sentence-transformers-2.2.2.tar.gz (85 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 86.0/86.0 kB 3.2 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: scikit-learn>=0.22.2 in /usr/local/lib/python3.10/dist-packages (from keybert) (1.2.2)
Requirement already satisfied: numpy>=1.18.5 in /usr/local/lib/python3.10/dist-packages (from keybert) (1.23.5)
Requirement already satisfied: rich>=10.4.0 in /usr/local/lib/python3.10/dist-packages (from keybert) (13.6.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.10/dist-packages (from rich>=10.4.0->keybert) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.10/dist-packages (from rich>=10.4.0->keybert) (2.16.1)
Requirement already satisfied: scipy>=1.3.2 in /usr/local/lib/python3.10/dist-packages (from scikit-learn>=0.22.2->keybert) (1.11.3)
Requirement already satisfied: joblib>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from scikit-learn>=0.22.2->keybert) (1.3.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn>=0.22.2->keybert) (3.2.0)
Collecting transformers<5.0.0,>=4.6.0 (from sentence-transformers>=0.3.8->keybert)
  Downloading transformers-4.34.1-py3-none-any.whl (7.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.7/7.7 MB 18.7 MB/s eta 0:00:00
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from sentence-transformers>=0.3.8->keybert) (4.66.1)
Requirement already satisfied: torch>=1.6.0 in /usr/local/lib/python3.10/dist-packages (from sentence-transformers>=0.3.8->keybert) (2.1.0+cu118)
Requirement already satisfied: torchvision in /usr/local/lib/python3.10/dist-packages (from sentence-transformers>=0.3.8->keybert) (0.16.0+cu118)
Requirement already satisfied: nltk in /usr/local/lib/python3.10/dist-packages (from sentence-transformers>=0.3.8->keybert) (3.8.1)
Collecting sentencepiece (from sentence-transformers>=0.3.8->keybert)
  Downloading sentencepiece-0.1.99-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 49.6 MB/s eta 0:00:00
Collecting huggingface-hub>=0.4.0 (from sentence-transformers>=0.3.8->keybert)
  Downloading huggingface_hub-0.18.0-py3-none-any.whl (301 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 302.0/302.0 kB 17.0 MB/s eta 0:00:00
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.4.0->sentence-transformers>=0.3.8->keybert) (3.12.4)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.4.0->sentence-transformers>=0.3.8->keybert) (2023.6.0)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.4.0->sentence-transformers>=0.3.8->keybert) (2.31.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.4.0->sentence-transformers>=0.3.8->keybert) (6.0.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.4.0->sentence-transformers>=0.3.8->keybert) (4.5.0)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.4.0->sentence-transformers>=0.3.8->keybert) (23.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.10/dist-packages (from markdown-it-py>=2.2.0->rich>=10.4.0->keybert) (0.1.2)
Requirement already satisfied: sympy in /usr/local/lib/python3.10/dist-packages (from torch>=1.6.0->sentence-transformers>=0.3.8->keybert) (1.12)
Requirement already satisfied: networkx in /usr/local/lib/python3.10/dist-packages (from torch>=1.6.0->sentence-transformers>=0.3.8->keybert) (3.2)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch>=1.6.0->sentence-transformers>=0.3.8->keybert) (3.1.2)
Requirement already satisfied: triton==2.1.0 in /usr/local/lib/python3.10/dist-packages (from torch>=1.6.0->sentence-transformers>=0.3.8->keybert) (2.1.0)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.10/dist-packages (from transformers<5.0.0,>=4.6.0->sentence-transformers>=0.3.8->keybert) (2023.6.3)
Collecting tokenizers<0.15,>=0.14 (from transformers<5.0.0,>=4.6.0->sentence-transformers>=0.3.8->keybert)
  Downloading tokenizers-0.14.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.8/3.8 MB 29.5 MB/s eta 0:00:00
Collecting safetensors>=0.3.1 (from transformers<5.0.0,>=4.6.0->sentence-transformers>=0.3.8->keybert)
  Downloading safetensors-0.4.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 62.9 MB/s eta 0:00:00
Requirement already satisfied: click in /usr/local/lib/python3.10/dist-packages (from nltk->sentence-transformers>=0.3.8->keybert) (8.1.7)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in /usr/local/lib/python3.10/dist-packages (from torchvision->sentence-transformers>=0.3.8->keybert) (9.4.0)
Collecting huggingface-hub>=0.4.0 (from sentence-transformers>=0.3.8->keybert)
  Downloading huggingface_hub-0.17.3-py3-none-any.whl (295 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 295.0/295.0 kB 34.3 MB/s eta 0:00:00
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->torch>=1.6.0->sentence-transformers>=0.3.8->keybert) (2.1.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub>=0.4.0->sentence-transformers>=0.3.8->keybert) (3.3.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub>=0.4.0->sentence-transformers>=0.3.8->keybert) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub>=0.4.0->sentence-transformers>=0.3.8->keybert) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub>=0.4.0->sentence-transformers>=0.3.8->keybert) (2023.7.22)
Requirement already satisfied: mpmath>=0.19 in /usr/local/lib/python3.10/dist-packages (from sympy->torch>=1.6.0->sentence-transformers>=0.3.8->keybert) (1.3.0)
Building wheels for collected packages: keybert, sentence-transformers
  Building wheel for keybert (setup.py) ... done
  Created wheel for keybert: filename=keybert-0.8.3-py3-none-any.whl size=39124 sha256=fc8b1c429da898fe3d73858de07d74104cf919043cf2c34ab7c4c3616bb9585a
  Stored in directory: /root/.cache/pip/wheels/70/88/07/1a3bc11fd1dd5f89924a02dcbca89a3015e25e8faa31f904dc
  Building wheel for sentence-transformers (setup.py) ... done
  Created wheel for sentence-transformers: filename=sentence_transformers-2.2.2-py3-none-any.whl size=125923 sha256=bc2aeb4647082a5171e707565d64755a52dd6244a7e6f216c7865c9db830d276
  Stored in directory: /root/.cache/pip/wheels/62/f2/10/1e606fd5f02395388f74e7462910fe851042f97238cbbd902f
Successfully built keybert sentence-transformers
Installing collected packages: sentencepiece, safetensors, huggingface-hub, tokenizers, transformers, sentence-transformers, keybert
Successfully installed huggingface-hub-0.17.3 keybert-0.8.3 safetensors-0.4.0 sentence-transformers-2.2.2 sentencepiece-0.1.99 tokenizers-0.14.1 transformers-4.34.1
Collecting rouge
  Downloading rouge-1.0.1-py3-none-any.whl (13 kB)
Requirement already satisfied: six in /usr/local/lib/python3.10/dist-packages (from rouge) (1.16.0)
Installing collected packages: rouge
Successfully installed rouge-1.0.1
Collecting textacy
  Downloading textacy-0.13.0-py3-none-any.whl (210 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 210.7/210.7 kB 4.4 MB/s eta 0:00:00
Requirement already satisfied: cachetools>=4.0.0 in /usr/local/lib/python3.10/dist-packages (from textacy) (5.3.1)
Requirement already satisfied: catalogue~=2.0 in /usr/local/lib/python3.10/dist-packages (from textacy) (2.0.10)
Collecting cytoolz>=0.10.1 (from textacy)
  Downloading cytoolz-0.12.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.9/1.9 MB 14.3 MB/s eta 0:00:00
Collecting floret~=0.10.0 (from textacy)
  Downloading floret-0.10.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (320 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 320.3/320.3 kB 18.3 MB/s eta 0:00:00
Collecting jellyfish>=0.8.0 (from textacy)
  Downloading jellyfish-1.0.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 18.0 MB/s eta 0:00:00
Requirement already satisfied: joblib>=0.13.0 in /usr/local/lib/python3.10/dist-packages (from textacy) (1.3.2)
Requirement already satisfied: networkx>=2.7 in /usr/local/lib/python3.10/dist-packages (from textacy) (3.2)
Requirement already satisfied: numpy>=1.17.0 in /usr/local/lib/python3.10/dist-packages (from textacy) (1.23.5)
Collecting pyphen>=0.10.0 (from textacy)
  Downloading pyphen-0.14.0-py3-none-any.whl (2.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 27.3 MB/s eta 0:00:00
Requirement already satisfied: requests>=2.10.0 in /usr/local/lib/python3.10/dist-packages (from textacy) (2.31.0)
Requirement already satisfied: scipy>=1.8.0 in /usr/local/lib/python3.10/dist-packages (from textacy) (1.11.3)
Requirement already satisfied: scikit-learn>=1.0 in /usr/local/lib/python3.10/dist-packages (from textacy) (1.2.2)
Requirement already satisfied: spacy~=3.0 in /usr/local/lib/python3.10/dist-packages (from textacy) (3.6.1)
Requirement already satisfied: tqdm>=4.19.6 in /usr/local/lib/python3.10/dist-packages (from textacy) (4.66.1)
Requirement already satisfied: toolz>=0.8.0 in /usr/local/lib/python3.10/dist-packages (from cytoolz>=0.10.1->textacy) (0.12.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests>=2.10.0->textacy) (3.3.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests>=2.10.0->textacy) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests>=2.10.0->textacy) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests>=2.10.0->textacy) (2023.7.22)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn>=1.0->textacy) (3.2.0)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in /usr/local/lib/python3.10/dist-packages (from spacy~=3.0->textacy) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from spacy~=3.0->textacy) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /usr/local/lib/python3.10/dist-packages (from spacy~=3.0->textacy) (1.0.10)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /usr/local/lib/python3.10/dist-packages (from spacy~=3.0->textacy) (2.0.8)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /usr/local/lib/python3.10/dist-packages (from spacy~=3.0->textacy) (3.0.9)
Requirement already satisfied: thinc<8.2.0,>=8.1.8 in /usr/local/lib/python3.10/dist-packages (from spacy~=3.0->textacy) (8.1.12)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in /usr/local/lib/python3.10/dist-packages (from spacy~=3.0->textacy) (1.1.2)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in /usr/local/lib/python3.10/dist-packages (from spacy~=3.0->textacy) (2.4.8)
Requirement already satisfied: typer<0.10.0,>=0.3.0 in /usr/local/lib/python3.10/dist-packages (from spacy~=3.0->textacy) (0.9.0)
Requirement already satisfied: pathy>=0.10.0 in /usr/local/lib/python3.10/dist-packages (from spacy~=3.0->textacy) (0.10.2)
Requirement already satisfied: smart-open<7.0.0,>=5.2.1 in /usr/local/lib/python3.10/dist-packages (from spacy~=3.0->textacy) (6.4.0)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 in /usr/local/lib/python3.10/dist-packages (from spacy~=3.0->textacy) (1.10.13)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from spacy~=3.0->textacy) (3.1.2)
Requirement already satisfied: setuptools in /usr/local/lib/python3.10/dist-packages (from spacy~=3.0->textacy) (67.7.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from spacy~=3.0->textacy) (23.2)
Requirement already satisfied: langcodes<4.0.0,>=3.2.0 in /usr/local/lib/python3.10/dist-packages (from spacy~=3.0->textacy) (3.3.0)
Requirement already satisfied: typing-extensions>=4.2.0 in /usr/local/lib/python3.10/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy~=3.0->textacy) (4.5.0)
Requirement already satisfied: blis<0.8.0,>=0.7.8 in /usr/local/lib/python3.10/dist-packages (from thinc<8.2.0,>=8.1.8->spacy~=3.0->textacy) (0.7.11)
Requirement already satisfied: confection<1.0.0,>=0.0.1 in /usr/local/lib/python3.10/dist-packages (from thinc<8.2.0,>=8.1.8->spacy~=3.0->textacy) (0.1.3)
Requirement already satisfied: click<9.0.0,>=7.1.1 in /usr/local/lib/python3.10/dist-packages (from typer<0.10.0,>=0.3.0->spacy~=3.0->textacy) (8.1.7)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->spacy~=3.0->textacy) (2.1.3)
Installing collected packages: pyphen, jellyfish, floret, cytoolz, textacy
Successfully installed cytoolz-0.12.2 floret-0.10.4 jellyfish-1.0.1 pyphen-0.14.0 textacy-0.13.0
Collecting pdfplumber
  Downloading pdfplumber-0.10.2-py3-none-any.whl (47 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 47.5/47.5 kB 1.4 MB/s eta 0:00:00
Collecting pdfminer.six==20221105 (from pdfplumber)
  Downloading pdfminer.six-20221105-py3-none-any.whl (5.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.6/5.6 MB 17.6 MB/s eta 0:00:00
Requirement already satisfied: Pillow>=9.1 in /usr/local/lib/python3.10/dist-packages (from pdfplumber) (9.4.0)
Collecting pypdfium2>=4.18.0 (from pdfplumber)
  Downloading pypdfium2-4.22.0-py3-none-manylinux_2_17_x86_64.whl (2.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.9/2.9 MB 43.2 MB/s eta 0:00:00
Requirement already satisfied: charset-normalizer>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from pdfminer.six==20221105->pdfplumber) (3.3.0)
Requirement already satisfied: cryptography>=36.0.0 in /usr/local/lib/python3.10/dist-packages (from pdfminer.six==20221105->pdfplumber) (41.0.4)
Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.10/dist-packages (from cryptography>=36.0.0->pdfminer.six==20221105->pdfplumber) (1.16.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.10/dist-packages (from cffi>=1.12->cryptography>=36.0.0->pdfminer.six==20221105->pdfplumber) (2.21)
Installing collected packages: pypdfium2, pdfminer.six, pdfplumber
Successfully installed pdfminer.six-20221105 pdfplumber-0.10.2 pypdfium2-4.22.0
Collecting rdflib
  Downloading rdflib-7.0.0-py3-none-any.whl (531 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 531.9/531.9 kB 6.6 MB/s eta 0:00:00
Collecting isodate<0.7.0,>=0.6.0 (from rdflib)
  Downloading isodate-0.6.1-py2.py3-none-any.whl (41 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.7/41.7 kB 5.6 MB/s eta 0:00:00
Requirement already satisfied: pyparsing<4,>=2.1.0 in /usr/local/lib/python3.10/dist-packages (from rdflib) (3.1.1)
Requirement already satisfied: six in /usr/local/lib/python3.10/dist-packages (from isodate<0.7.0,>=0.6.0->rdflib) (1.16.0)
Installing collected packages: isodate, rdflib
Successfully installed isodate-0.6.1 rdflib-7.0.0
Collecting bert-score
  Downloading bert_score-0.3.13-py3-none-any.whl (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.1/61.1 kB 2.1 MB/s eta 0:00:00
Requirement already satisfied: torch>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from bert-score) (2.1.0+cu118)
Requirement already satisfied: pandas>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from bert-score) (1.5.3)
Requirement already satisfied: transformers>=3.0.0 in /usr/local/lib/python3.10/dist-packages (from bert-score) (4.34.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from bert-score) (1.23.5)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from bert-score) (2.31.0)
Requirement already satisfied: tqdm>=4.31.1 in /usr/local/lib/python3.10/dist-packages (from bert-score) (4.66.1)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.10/dist-packages (from bert-score) (3.7.1)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.10/dist-packages (from bert-score) (23.2)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.0.1->bert-score) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.0.1->bert-score) (2023.3.post1)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from torch>=1.0.0->bert-score) (3.12.4)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.10/dist-packages (from torch>=1.0.0->bert-score) (4.5.0)
Requirement already satisfied: sympy in /usr/local/lib/python3.10/dist-packages (from torch>=1.0.0->bert-score) (1.12)
Requirement already satisfied: networkx in /usr/local/lib/python3.10/dist-packages (from torch>=1.0.0->bert-score) (3.2)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch>=1.0.0->bert-score) (3.1.2)
Requirement already satisfied: fsspec in /usr/local/lib/python3.10/dist-packages (from torch>=1.0.0->bert-score) (2023.6.0)
Requirement already satisfied: triton==2.1.0 in /usr/local/lib/python3.10/dist-packages (from torch>=1.0.0->bert-score) (2.1.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.16.4 in /usr/local/lib/python3.10/dist-packages (from transformers>=3.0.0->bert-score) (0.17.3)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from transformers>=3.0.0->bert-score) (6.0.1)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.10/dist-packages (from transformers>=3.0.0->bert-score) (2023.6.3)
Requirement already satisfied: tokenizers<0.15,>=0.14 in /usr/local/lib/python3.10/dist-packages (from transformers>=3.0.0->bert-score) (0.14.1)
Requirement already satisfied: safetensors>=0.3.1 in /usr/local/lib/python3.10/dist-packages (from transformers>=3.0.0->bert-score) (0.4.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->bert-score) (1.1.1)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.10/dist-packages (from matplotlib->bert-score) (0.12.1)

In [ ]:
!python -m spacy download en_core_web_lg

2023-10-25 18:55:23.198347: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:9342] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2023-10-25 18:55:23.198399: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2023-10-25 18:55:23.198433: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1518] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-10-25 18:55:23.206322: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-10-25 18:55:24.290843: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
2023-10-25 18:55:25.554229: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:894] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2023-10-25 18:55:25.554678: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:894] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2023-10-25 18:55:25.554861: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:894] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
Collecting en-core-web-lg==3.6.0
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_lg-3.6.0/en_core_web_lg-3.6.0-py3-none-any.whl (587.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 587.7/587.7 MB 2.9 MB/s eta 0:00:00
Requirement already satisfied: spacy<3.7.0,>=3.6.0 in /usr/local/lib/python3.10/dist-packages (from en-core-web-lg==3.6.0) (3.6.1)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in /usr/local/lib/python3.10/dist-packages (from spacy<3.7.0,>=3.6.0->en-core-web-lg==3.6.0) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.7.0,>=3.6.0->en-core-web-lg==3.6.0) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.7.0,>=3.6.0->en-core-web-lg==3.6.0) (1.0.10)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /usr/local/lib/python3.10/dist-packages (from spacy<3.7.0,>=3.6.0->en-core-web-lg==3.6.0) (2.0.8)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /usr/local/lib/python3.10/dist-packages (from spacy<3.7.0,>=3.6.0->en-core-web-lg==3.6.0) (3.0.9)
Requirement already satisfied: thinc<8.2.0,>=8.1.8 in /usr/local/lib/python3.10/dist-packages (from spacy<3.7.0,>=3.6.0->en-core-web-lg==3.6.0) (8.1.12)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in /usr/local/lib/python3.10/dist-packages (from spacy<3.7.0,>=3.6.0->en-core-web-lg==3.6.0) (1.1.2)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in /usr/local/lib/python3.10/dist-packages (from spacy<3.7.0,>=3.6.0->en-core-web-lg==3.6.0) (2.4.8)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /usr/local/lib/python3.10/dist-packages (from spacy<3.7.0,>=3.6.0->en-core-web-lg==3.6.0) (2.0.10)
Requirement already satisfied: typer<0.10.0,>=0.3.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.7.0,>=3.6.0->en-core-web-lg==3.6.0) (0.9.0)
Requirement already satisfied: pathy>=0.10.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.7.0,>=3.6.0->en-core-web-lg==3.6.0) (0.10.2)
Requirement already satisfied: smart-open<7.0.0,>=5.2.1 in /usr/local/lib/python3.10/dist-packages (from spacy<3.7.0,>=3.6.0->en-core-web-lg==3.6.0) (6.4.0)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.7.0,>=3.6.0->en-core-web-lg==3.6.0) (4.66.1)
Requirement already satisfied: numpy>=1.15.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.7.0,>=3.6.0->en-core-web-lg==3.6.0) (1.23.5)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.7.0,>=3.6.0->en-core-web-lg==3.6.0) (2.31.0)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 in /usr/local/lib/python3.10/dist-packages (from spacy<3.7.0,>=3.6.0->en-core-web-lg==3.6.0) (1.10.13)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from spacy<3.7.0,>=3.6.0->en-core-web-lg==3.6.0) (3.1.2)
Requirement already satisfied: setuptools in /usr/local/lib/python3.10/dist-packages (from spacy<3.7.0,>=3.6.0->en-core-web-lg==3.6.0) (67.7.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.7.0,>=3.6.0->en-core-web-lg==3.6.0) (23.2)
Requirement already satisfied: langcodes<4.0.0,>=3.2.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.7.0,>=3.6.0->en-core-web-lg==3.6.0) (3.3.0)
Requirement already satisfied: typing-extensions>=4.2.0 in /usr/local/lib/python3.10/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy<3.7.0,>=3.6.0->en-core-web-lg==3.6.0) (4.5.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.13.0->spacy<3.7.0,>=3.6.0->en-core-web-lg==3.6.0) (3.3.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.13.0->spacy<3.7.0,>=3.6.0->en-core-web-lg==3.6.0) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.13.0->spacy<3.7.0,>=3.6.0->en-core-web-lg==3.6.0) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.13.0->spacy<3.7.0,>=3.6.0->en-core-web-lg==3.6.0) (2023.7.22)
Requirement already satisfied: blis<0.8.0,>=0.7.8 in /usr/local/lib/python3.10/dist-packages (from thinc<8.2.0,>=8.1.8->spacy<3.7.0,>=3.6.0->en-core-web-lg==3.6.0) (0.7.11)
Requirement already satisfied: confection<1.0.0,>=0.0.1 in /usr/local/lib/python3.10/dist-packages (from thinc<8.2.0,>=8.1.8->spacy<3.7.0,>=3.6.0->en-core-web-lg==3.6.0) (0.1.3)
Requirement already satisfied: click<9.0.0,>=7.1.1 in /usr/local/lib/python3.10/dist-packages (from typer<0.10.0,>=0.3.0->spacy<3.7.0,>=3.6.0->en-core-web-lg==3.6.0) (8.1.7)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->spacy<3.7.0,>=3.6.0->en-core-web-lg==3.6.0) (2.1.3)
Installing collected packages: en-core-web-lg
Successfully installed en-core-web-lg-3.6.0
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_lg')

In [ ]:
import torch
from transformers import AutoModelForSeq2SeqLM, AutoTokenizer
import math
import IPython
import pickle
import pandas as pd
import matplotlib.pyplot as plt
import pdfplumber
import numpy as np
import itertools
import unicodedata
import re
from re import sub
import matplotlib.pyplot as plt
import matplotlib.image as img
import string
from string import punctuation
import time
from pprint import pprint
from sentence_transformers import SentenceTransformer
import faiss
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
from autocorrect import Speller
spell = Speller()
from sentence_transformers import CrossEncoder

from rouge import Rouge

from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize, sent_tokenize
from nltk.stem import WordNetLemmatizer
from nltk.corpus import wordnet
from nltk.probability import FreqDist
from nltk.parse.corenlp import CoreNLPParser, CoreNLPDependencyParser
from nltk.tree import ParentedTree
from nltk.stem.snowball import SnowballStemmer

# Use English stemmer.
stemmer = SnowballStemmer("english")
from collections import Counter
from tqdm import tqdm

import copy

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.decomposition import LatentDirichletAllocation

import spacy
nlp = spacy.load("en_core_web_lg")
from spacy.matcher import Matcher
from spacy.matcher import DependencyMatcher
from spacy.tokens import Span
from spacy import displacy

from rdflib.namespace import DC, DCTERMS, DOAP, FOAF, OWL, RDF, RDFS, SKOS, VOID, XMLNS, XSD
from rdflib import URIRef, BNode, Literal, Namespace, Graph
from rdflib.extras import describer

import warnings
warnings.filterwarnings('ignore')

%matplotlib inline

In [ ]:
import nltk
nltk.download('wordnet')
nltk.download('omw-1.4')

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...

True

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import PyPDF2
import fitz
import re


# Replace 'your_pdf_file.pdf' with the actual path to your PDF file
pdf_file_path = '/content/drive/MyDrive/PMBOK6-2017_wf.pdf'

# Create a PDF object
pdf_file = open(pdf_file_path, 'rb')
pdf_reader = fitz.open(pdf_file)

In [ ]:
import fitz  # PyMuPDF

output_txt_file_path = 'PDF_LINES_NOT_CLEAN.txt'

start_page = 37
end_page = 524

output_txt_file = open(output_txt_file_path, 'w', encoding='utf-8')

# Open the PDF file
pdf_document = fitz.open(pdf_file_path)  # Replace 'your_pdf_file.pdf' with your PDF file path

for page_num in range(start_page - 1, end_page):
    page = pdf_document.load_page(page_num)

    # Extract text from the page
    page_text = page.get_text()

    # Split the page text into lines
    lines = page_text.split('\n')

    # Process each line
    for line in lines:
        print(line)
        output_txt_file.write(line + '\n')

# Close the PDF file
pdf_document.close()

# Close the output text file
output_txt_file.close()

Le flux de sortie a été tronqué et ne contient que les 5000 dernières lignes.
the project. This information may be at the activity or project level. This includes consideration of attributes such as
resource experience and/or skill level, as well as various geographical locations.

9.3.3.4 CHANGE REQUESTS
Described in Section 4.3.3.4. When changes occur as a result of carrying out the Acquire Resources process (for example,
impacts to the schedule) or when recommended corrective or preventive actions impact any of the components of the
project management plan or project documents, the project manager needs to submit a change request. Change requests
are processed for review and disposition through the Perform Integrated Change Control process (Section 4.6).

9.3.3.5 PROJECT MANAGEMENT PLAN UPDATES
Any change to the project management plan goes through the organization’s change control process via a change
request. Components of the project management plan that may be updated as a result of carrying out this process include
but are not limited to:
◆ Resource management plan. Described in Section 9.1.3.1. The resource management plan may be updated to
reflect actual experience in acquiring resources for the project, including lessons learned in acquiring resources
early in the project that will impact how resources are acquired later in the project.
◆ Cost baseline. Described in Section 7.3.3.1. The cost baseline may change as a result of the acquisition of
resources for the project.

310
Part 1 - Guide

9.3.3.6 PROJECT DOCUMENTS UPDATES
Project documents that may be updated as a result of carrying out this process include but are not limited to:
◆ Lessons learned register. Described in Section 4.4.3.1. The lessons learned register is updated with information
on challenges encountered and how they could have been avoided as well as approaches that worked well for
acquiring resources.
◆ Project schedule. Described in Section 6.5.3.2. Changes to the project schedule may result from the availability
of required resources.
◆ Resource breakdown structure. Described in Section 9.2.3.3. Resources acquired during this process are
recorded in the resource breakdown structure.
◆ Resource requirements. Described in Section 9.2.3.1. Resource requirements documentation is updated to reflect
resources acquired for the project.
◆ Risk register. Described in Section 11.2.3.1. New risks identified during this process are recorded in the risk
register and managed using the risk management processes.
◆ Stakeholder register. Described in Section 13.1.3.1. The stakeholder register is updated with any new
stakeholders and any new information about existing stakeholders that has been gained as a result of
this process.

9.3.3.7 ENTERPRISE ENVIRONMENTAL FACTORS UPDATES
Enterprise environmental factors that are updated include but are not limited to:
◆ Resource availability within the organization, and
◆ Amount of the organization’s consumable resources that have been used.

9.3.3.8 ORGANIZATIONAL PROCESS ASSETS UPDATES
Organizational process assets that are updated as a result of the Acquire Resources process include but are not
limited to documentation related to acquiring, assigning and allocating resources.
9.4 DEVELOP TEAM
Develop Team is the process of improving competencies, team member interaction, and the overall team environment
to enhance project performance. The key benefit of this process is that it results in improved teamwork, enhanced
interpersonal skills and competencies, motivated employees, reduced attrition, and improved overall project performance.
This process is performed throughout the project.
The inputs, tools and techniques, and outputs of the process are depicted in Figure 9-10. Figure 9-11 depicts the data
flow diagram for the process.


311




Project managers require the skills to identify, build, maintain, motivate, lead, and inspire project teams to achieve
high team performance and to meet the project’s objectives. Teamwork is a critical factor for project success, and
developing effective project teams is one of the primary responsibilities of the project manager. Project managers
should create an environment that facilitates teamwork and continually motivates the team by providing challenges
and opportunities, providing timely feedback and support as needed, and recognizing and rewarding good performance.
High team performance can be achieved by employing these behaviors:
◆ Using open and effective communication,
◆ Creating team-building opportunities,
◆ Developing trust among team members,
◆ Managing conflicts in a constructive manner,
◆ Encouraging collaborative problem solving, and
◆ Encouraging collaborative decision making.

312
Part 1 - Guide

Project managers operate in a global environment and work on projects characterized by cultural diversity. Team
members often have diverse industry experience, communicate in multiple languages, and sometimes work with a
“team language” or cultural norm that may be different from their native one. The project management team should
capitalize on cultural differences, focus on developing and sustaining the project team throughout the project life cycle,
and promote working together interdependently in a climate of mutual trust. Developing the project team improves
the people skills, technical competencies, and overall team environment and project performance. It requires clear,
timely, effective, and efficient communication between team members throughout the life of the project. Objectives of
developing a project team include but are not limited to:
◆ Improving the knowledge and skills of team members to increase their ability to complete project deliverables,
while lowering costs, reducing schedules, and improving quality;
◆ Improving feelings of trust and agreement among team members to raise morale, lower conflict, and increase
teamwork;
◆ Creating a dynamic, cohesive, and collaborative team culture to: (1) improve individual and team productivity,
team spirit, and cooperation; and (2) allow cross-training and mentoring between team members to share
knowledge and expertise; and
◆ Empowering the team to participate in decision making and take ownership of the provided solutions to improve
team productivity for more effective and efficient results.
One of the models used to describe team development is the Tuckman ladder [19, 20], which includes five stages of
development that teams may go through. Although it is common for these stages to occur in order, it is not uncommon for
a team to get stuck in a particular stage or regress to an earlier stage. Projects with team members who worked together
in the past might skip a stage.
◆ Forming. This phase is where the team members meet and learn about the project and their formal roles and
responsibilities. Team members tend to be independent and not as open in this phase.
◆ Storming. During this phase, the team begins to address the project work, technical decisions, and the project
management approach. If team members are not collaborative or open to differing ideas and perspectives, the
environment can become counterproductive.
◆ Norming. In this phase, team members begin to work together and adjust their work habits and behaviors to support
the team. The team members learn to trust each other.
◆ Performing. Teams that reach the performing stage function as a well-organized unit. They are interdependent
and work through issues smoothly and effectively.
◆ Adjourning. In this phase, the team completes the work and moves on from the project. This typically occurs when
staff is released from the project as deliverables are completed or as part of the Close Project or Phase process.

313

The duration of a particular stage depends upon team dynamics, team size, and team leadership. Project managers
should have a good understanding of team dynamics in order to move their team members through all stages in an
effective manner.


9.4.1 DEVELOP TEAM: INPUTS

9.4.1.1 PROJECT MANAGEMENT PLAN
Described in Section 4.2.3.1. Project management plan components include but are not limited to the resource
management plan. Described in Section 9.1.3.1, the resource management plan provides guidance on providing
project team member rewards, feedback, additional training, and disciplinary actions as a result of team performance
assessments and other forms of project team management. The resource management plan may include also the team
performance assessment criteria.

9.4.1.2 PROJECT DOCUMENTS
Project documents that can be considered as inputs for this process include but are not limited to:
◆ Lessons learned register. Described in Section 4.4.3.1. Lessons learned earlier in the project with regard to
developing the team can be applied to later phases in the project to improve team performance.
◆ Project schedule. Described in Section 6.5.3.2. The project schedule defines how and when to provide training to
the project team and develop the competencies required at different phases. It identifies the need for team
development strategies based on variations, if any, during the project execution.
◆ Project team assignments. Described in Section 9.3.3.1. Project team assignments identify the team and
member roles and responsibilities.
◆ Resource calendars. Described in Section 9.2.1.2. Resource calendars identify times when the project team
members can participate in team development activities. It also helps illustrate team availability during the entire
project.
◆ Team charter. Described in Section 9.1.3.2. The team charter is where the team operating guidelines are
documented. The team values and operating guidelines provide the structure that describes how the team will
operate together.

9.4.1.3 ENTERPRISE ENVIRONMENTAL FACTORS
The enterprise environmental factors that can influence the Develop Team process include but are not limited to:
◆ Human resource management policies regarding hiring and termination, employee performance reviews,
employee development and training records, and recognition and rewards;
◆ Team member skills, competencies, and specialized knowledge; and
◆ Geographic distribution of team members.

314
Part 1 - Guide

9.4.1.4 ORGANIZATIONAL PROCESS ASSETS
The organizational process assets that can influence the Develop Team process include but are not limited to historical
information and the lessons learned repository.


9.4.2 DEVELOP TEAM: TOOLS AND TECHNIQUES

9.4.2.1 COLOCATION
Colocation involves placing many or all of the most active project team members in the same physical location to
enhance their ability to perform as a team. Colocation can be temporary, such as at strategically important times during
the project, or can continue for the entire project. Colocation strategies can include a team meeting room, common places
to post schedules, and other conveniences that enhance communication and a sense of community.

9.4.2.2 VIRTUAL TEAMS
The use of virtual teams can bring benefits such as the use of more skilled resources, reduced costs, less travel and
relocation expenses, and the proximity of team members to suppliers, customers, or other key stakeholders. Virtual teams
can use technology to create an online team environment where the team can store files, use conversations threads to
discuss issues, and keep a team calendar.

9.4.2.3 COMMUNICATION TECHNOLOGY
Described in Section 10.1.2.3. Communication technology is important in addressing the team development issues in
colocated and virtual teams. It helps build a harmonious environment for the colocated team and a better understanding
for the virtual team, especially those working in different time zones. Examples of communication technology that may
be used are:
◆ Shared portal. A shared repository for information sharing (e.g., website, collaboration software or intranet) is
effective for virtual project teams.
◆ Video conferencing. Video conferencing is an important technique for effective communication with
virtual teams.
◆ Audio conferencing. Communication within a team using audio conferencing is another technique to build
rapport and confidence within virtual teams.
◆ Email/chat. Regular communications using email and chat is also an effective technique.

315

9.4.2.4 INTERPERSONAL AND TEAM SKILLS
Interpersonal and team skills that can be used for this process include but are not limited to:
◆ Conflict management. Described in Section 9.5.2.1. The project manager needs to resolve conflicts in a timely
manner and in a constructive way in order to achieve a high-performing team.
◆ Influencing. Described in Section 9.5.2.1. An influencing skill used in this process is gathering relevant and
critical information to address important issues and reach agreements while maintaining mutual trust.
◆ Motivation. Motivation is providing a reason for someone to act. Teams are motivated by empowering them to
participate in decision making and encouraging them to work independently.
◆ Negotiation. Described in Section 12.2.2.5. Negotiation among team members is used to reach consensus on project
needs. Negotiation can build trust and harmony among the team members.
◆ Team building. Team building is conducting activities that enhance the team’s social relations and build a
collaborative and cooperative working environment. Team building activities can vary from a 5-minute agenda item
in a status review meeting to an offsite, professionally facilitated event designed to improve interpersonal
relationships. The objective of team-building activities is to help individual team members work together effectively.
Team-building strategies are particularly valuable when team members operate from remote locations without the
benefit of face-to-face contact. Informal communication and activities can help in building trust and establishing
good working relationships. While team building is essential during the initial stages of a project, it should be a
continuous process. Changes in a project environment are inevitable, and to manage them effectively, a continuous
or renewed team-building effort may be applied. The project manager should continually monitor team functionality
and performance to determine if any actions are needed to prevent or correct various team problems.

9.4.2.5 RECOGNITION AND REWARDS
Part of the team development process involves recognizing and rewarding desirable behavior. The original
plan for rewarding people is developed during the Plan Resource Management process. Rewards will be effective
only if they satisfy a need that is valued by that individual. Reward decisions are made, formally or informally,
during the process of managing the project team. Cultural differences should be considered when determining
recognition and rewards.

316
Part 1 - Guide

People are motivated when they feel they are valued in the organization and this value is demonstrated by the rewards
given to them. Generally, money is viewed as a tangible aspect of any reward system, but intangible rewards could be
equally or even more effective. Most project team members are motivated by an opportunity to grow, accomplish, be
appreciated, and apply their professional skills to meet new challenges. A good strategy for project managers is to give
the team recognition throughout the life cycle of the project rather than waiting until the project is completed.

9.4.2.6 TRAINING
Training includes all activities designed to enhance the competencies of the project team members. Training can be
formal or informal. Examples of training methods include classroom, online, computer-based, on-the-job training from
another project team member, mentoring, and coaching. If project team members lack the necessary management or
technical skills, such skills can be developed as part of the project work. Scheduled training takes place as stated in
the resource management plan. Unplanned training takes place as a result of observation, conversation, and project
performance appraisals conducted during management of the project team. Training costs could be included in the project
budget or supported by the performing organization if the added skills may be useful for future projects. It may be
performed by in-house or by external trainers.

9.4.2.7 INDIVIDUAL AND TEAM ASSESSMENTS
Individual and team assessment tools give the project manager and the project team insight into areas of strengths and
weaknesses. These tools help project managers assess team members’ preferences, aspirations, how they process and
organize information, how they make decisions, and how they interact with people. Various tools are available such as
attitudinal surveys, specific assessments, structured interviews, ability tests, and focus groups. These tools can provide
improved understanding, trust, commitment, and communications among team members and facilitate more productive
teams throughout the project.

9.4.2.8 MEETINGS
Meetings are used to discuss and address pertinent topics for developing the team. Attendees include the project
manager and the project team. Types of meetings include but are not limited to project orientation meetings, team-
building meetings, and team development meetings.

317

9.4.3 DEVELOP TEAM: OUTPUTS

9.4.3.1 TEAM PERFORMANCE ASSESSMENTS
As project team development efforts such as training, team building, and colocation are implemented, the project
management team makes formal or informal assessments of the project team’s effectiveness. Effective team
development strategies and activities are expected to increase the team’s performance, which increases the likelihood of
meeting project objectives.
The evaluation of a team’s effectiveness may include indicators such as:
◆ Improvements in skills that allow individuals to perform assignments more effectively,
◆ Improvements in competencies that help team members perform better as a team,
◆ Reduced staff turnover rate, and
◆ Increased team cohesiveness where team members share information and experiences openly and help each
other to improve the overall project performance.
As a result of conducting an evaluation of the team’s overall performance, the project management team can
identify the specific training, coaching, mentoring, assistance, or changes required to improve the team’s performance.
This should also include identifying the appropriate or required resources necessary to achieve and implement the
improvements identified in the assessment.

9.4.3.2 CHANGE REQUESTS
Described in Section 4.3.3.4. If change requests occur as a result of carrying out the Develop Team process or if
recommended corrective or preventive actions impact any of the components of the project management plan or project
documents, the project manager needs to submit a change request and follow the Perform Integrated Change Control
process as defined in Section 4.6.

9.4.3.3 PROJECT MANAGEMENT PLAN UPDATES
Any change to the project management plan goes through the organization’s change control process via a change
request. Components that may require a change request for the project management plan include but are not limited to
the resource management plan, as described in Section 9.1.3.1.

318
Part 1 - Guide

9.4.3.4 PROJECT DOCUMENTS UPDATES
Project documents that may be updated as a result of carrying out this process include but are not limited to:
◆ Lessons learned register. Described in Section 4.4.3.1. The lessons learned register is updated with information
on challenges encountered and how they could have been avoided as well as approaches that worked well for
the development of the team.
◆ Project schedule. Described in Section 6.5.3.2. Activities to develop the project team may result in changes to
the project schedule.
◆ Project team assignments. Described in Section 9.3.3.1. When team development results in changes to agreed-
upon assignments, these changes are recorded in the project team assignments documentation.

In [ ]:
# #Read CSV
# import pandas as pd
# df = pd.read_csv('PDF_LINES_NOT_CLEAN.csv')

In [ ]:
file_path = 'PDF_LINES_NOT_CLEAN.txt'

try:
    with open(file_path, 'r',encoding='utf-8') as file:
        # Read the contents of the file
        file_contents = file.read()
        print(file_contents)
except FileNotFoundError:
    print(f"The file '{file_path}' was not found.")

1

1

INTRODUCTION

1.1 OVERVIEW AND PURPOSE OF THIS GUIDE
Project management is not new. It has been in use for hundreds of years. Examples of project outcomes include:
◆ Pyramids of Giza,
◆ Olympic games,
◆ Great Wall of China,
◆ Taj Mahal,
◆ Publication of a children’s book,
◆ Panama Canal,
◆ Development of commercial jet airplanes,
◆ Polio vaccine,
◆ Human beings landing on the moon,
◆ Commercial software applications,
◆ Portable devices to use the global positioning system (GPS), and
◆ Placement of the International Space Station into Earth’s orbit.
The outcomes of these projects were the result of leaders and managers applying project management practices,
principles, processes, tools, and techniques to their work. The managers of these projects used a set of key skills and
applied knowledge to satisfy their customers and other people involved in and affected by the project. By the mid-20th
century, project managers began the work of seeking recognition for project management as a profession. One aspect
of this work involved obtaining agreement on the content of the body of knowledge (BOK) called project management.
This BOK became known as the Project Management Body of Knowledge (PMBOK). The Project Management Institute
(PMI) produced a baseline of charts and glossaries for the PMBOK. Project managers soon realized that no single book could
contain the entire PMBOK. Therefore, PMI developed and published A Guide to the Project Management Body of
Knowledge (PMBOK® Guide).
PMI defines the project management body of knowledge (PMBOK) as a term that describes the knowledge within the
profession of project management. The project management body of knowledge includes proven traditional practices that
are widely applied as well as innovative practices that are emerging in the profession.

2
Part 1 - Guide

The body of knowledge (BOK) includes both published and unpublished materials. This body of knowledge is
constantly evolving. This PMBOK® Guide identifies a subset of the project management body of knowledge that is
generally recognized as good practice.
◆ Generally recognized means the knowledge and practices described are applicable to most projects most of the
time, and there is consensus about their value and usefulness.
◆ Good practice means there is general agreement that the application of the knowledge, skills, tools, and techniques
to project management processes can enhance the chance of success over many projects in delivering the
expected business values and results.
The project manager works with the project team and other stakeholders to determine and use the appropriate
generally recognized good practices for each project. Determining the appropriate combination of processes, inputs, tools,
techniques, outputs and life cycle phases to manage a project is referred to as “tailoring” the application of the
knowledge described in this guide.
This PMBOK® Guide is different from a methodology. A methodology is a system of practices, techniques,
procedures, and rules used by those who work in a discipline. This PMBOK® Guide is a foundation upon which
organizations can build methodologies, policies, procedures, rules, tools and techniques, and life cycle phases
needed to practice project management.


1.1.1 THE STANDARD FOR PROJECT MANAGEMENT
This guide is based on The Standard for Project Management [1]. A standard is a document established by an authority,
custom, or general consent as a model or example. As an American National Standards Institute (ANSI) standard, The
Standard for Project Management was developed using a process based on the concepts of consensus, openness, due
process, and balance. The Standard for Project Management is a foundational reference for PMI’s project management
professional development programs and the practice of project management. Because project management needs to
be tailored to fit the needs of the project, the standard and the guide are both based on descriptive practices, rather than
prescriptive practices. Therefore, the standard identifies the processes that are considered good practices on most
projects, most of the time. The standard also identifies the inputs and outputs that are usually associated with those
processes. The standard does not require that any particular process or practice be performed. The Standard for Project
Management is included as Part II of A Guide to the Project Management Body of Knowledge (PMBOK®  Guide).
The PMBOK® Guide provides more detail about key concepts, emerging trends, considerations for tailoring the project
management processes, and information on how tools and techniques are applied to projects. Project managers may
use one or more methodologies to implement the project management processes outlined in the standard.

3

The scope of this guide is limited to the discipline of project management, rather than the full spectrum of portfolios,
programs, and projects. Portfolios and programs will be addressed only to the degree they interact with projects. PMI
publishes two other standards that address the management of portfolios and programs:
◆ The Standard for Portfolio Management [2], and
◆ The Standard for Program Management [3].


1.1.2 COMMON VOCABULARY
A common vocabulary is an essential element of a professional discipline. The PMI Lexicon of Project Management
Terms [4] provides the foundational professional vocabulary that can be consistently used by organizations, portfolio,
program, and project managers and other project stakeholders. The Lexicon will continue to evolve over time. The glossary
to this guide includes the vocabulary in the Lexicon along with additional definitions. There may be other industry-specific
terms used in projects that are defined by that industry’s literature.


1.1.3 CODE OF ETHICS AND PROFESSIONAL CONDUCT
PMI publishes the Code of Ethics and Professional Conduct [5] to instill confidence in the project management
profession and to help an individual in making wise decisions, particularly when faced with difficult situations where the
individual may be asked to compromise his or her integrity or values. The values that the global project management
community defined as most important were responsibility, respect, fairness, and honesty. The Code of Ethics and
Professional Conduct affirms these four values as its foundation.
The Code of Ethics and Professional Conduct includes both aspirational standards and mandatory standards. The
aspirational standards describe the conduct that practitioners, who are also PMI members, certification holders, or
volunteers, strive to uphold. Although adherence to the aspirational standards is not easily measured, conduct in
accordance with these is an expectation for those who consider themselves to be professionals—it is not optional. The
mandatory standards establish firm requirements and, in some cases, limit or prohibit practitioner behavior. Practitioners
who are also PMI members, certification holders, or volunteers and who do not conduct themselves in accordance with
these standards will be subject to disciplinary procedures before PMI’s Ethics Review Committee.

4
Part 1 - Guide

1.2 FOUNDATIONAL ELEMENTS
This section describes foundational elements necessary for working in and understanding the discipline of project
management.

1.2.1 PROJECTS
A project is a temporary endeavor undertaken to create a unique product, service, or result.
◆ Unique product, service, or result. Projects are undertaken to fulfill objectives by producing deliverables.
An objective is defined as an outcome toward which work is to be directed, a strategic position to be attained,
a purpose to be achieved, a result to be obtained, a product to be produced, or a service to be performed.
A deliverable is defined as any unique and verifiable product, result, or capability to perform a service that is
required to be produced to complete a process, phase, or project. Deliverables may be tangible or intangible.
Fulfillment of project objectives may produce one or more of the following deliverables:
◼ A unique product that can be either a component of another item, an enhancement or correction to an item,
or a new end item in itself (e.g., the correction of a defect in an end item);
◼ A unique service or a capability to perform a service (e.g., a business function that supports production
or distribution);
◼ A unique result, such as an outcome or document (e.g., a research project that develops knowledge that can
be used to determine whether a trend exists or a new process will benefit society); and
◼ A unique combination of one or more products, services, or results (e.g., a software application, its associated
documentation, and help desk services).
Repetitive elements may be present in some project deliverables and activities. This repetition does not change
the fundamental and unique characteristics of the project work. For example, office buildings can be constructed
with the same or similar materials and by the same or different teams. However, each building project remains
unique in key characteristics (e.g., location, design, environment, situation, people involved).
Projects are undertaken at all organizational levels. A project can involve a single individual or a group. A project
can involve a single organizational unit or multiple organizational units from multiple organizations.

5

Examples of projects include but are not limited to:
◼ Developing a new pharmaceutical compound for market,
◼ Expanding a tour guide service,
◼ Merging two organizations,
◼ Improving a business process within an organization,
◼ Acquiring and installing a new computer hardware system for use in an organization,
◼ Exploring for oil in a region,
◼ Modifying a computer software program used in an organization,
◼ Conducting research to develop a new manufacturing process, and
◼ Constructing a building.
◆ Temporary endeavor. The temporary nature of projects indicates that a project has a definite beginning and end.
Temporary does not necessarily mean a project has a short duration. The end of the project is reached when one
or more of the following is true:
◼ The project’s objectives have been achieved;
◼ The objectives will not or cannot be met;
◼ Funding is exhausted or no longer available for allocation to the project;
◼ The need for the project no longer exists (e.g., the customer no longer wants the project completed, a change
in strategy or priority ends the project, the organizational management provides direction to end the project);
◼ The human or physical resources are no longer available; or
◼ The project is terminated for legal cause or convenience.
Projects are temporary, but their deliverables may exist beyond the end of the project. Projects may produce
deliverables of a social, economic, material, or environmental nature. For example, a project to build a national
monument will create a deliverable expected to last for centuries.

6
Part 1 - Guide

◆ Projects drive change. Projects drive change in organizations. From a business perspective, a project is aimed at
moving an organization from one state to another state in order to achieve a specific objective (see Figure 1-1).
Before the project begins, the organization is commonly referred to as being in the current state. The desired result
of the change driven by the project is described as the future state.
For some projects, this may involve creating a transition state where multiple steps are made along a continuum
to achieve the future state. The successful completion of a project results in the organization moving to the future
state and achieving the specific objective. For more information on project management and change, see
Managing Change in Organizations: A Practice Guide [6].



















7

◆ Projects enable business value creation. PMI defines business value as the net quantifiable benefit derived from
a business endeavor. The benefit may be tangible, intangible, or both. In business analysis, business value is
considered the return, in the form of elements such as time, money, goods, or intangibles in return for something
exchanged (see Business Analysis for Practitioners: A Practice Guide, p. 185 [7]).
Business value in projects refers to the benefit that the results of a specific project provide to its stakeholders. The
benefit from projects may be tangible, intangible, or both.
Examples of tangible elements include:
◼ Monetary assets,
◼ Stockholder equity,
◼ Utility,
◼ Fixtures,
◼ Tools, and
◼ Market share.
Examples of intangible elements include:
◼ Goodwill,
◼ Brand recognition,
◼ Public benefit,
◼ Trademarks,
◼ Strategic alignment, and
◼ Reputation.
◆ Project Initiation Context. Organizational leaders initiate projects in response to factors acting upon their
organizations. There are four fundamental categories for these factors, which illustrate the context of a project
(see Figure 1-2):
◼ Meet regulatory, legal, or social requirements;
◼ Satisfy stakeholder requests or needs;
◼ Implement or change business or technological strategies; and
◼ Create, improve, or fix products, processes, or services.

8
Part 1 - Guide


These factors influence an organization’s ongoing operations and business strategies. Leaders respond to these
factors in order to keep the organization viable. Projects provide the means for organizations to successfully make the
changes necessary to deal with these factors. These factors ultimately should link to the strategic objectives of the
organization and the business value of each project.
Table 1-1 illustrates how example factors could align with one or more of the fundamental factor categories.

9




10
Part 1 - Guide

1.2.2 THE IMPORTANCE OF PROJECT MANAGEMENT
Project management is the application of knowledge, skills, tools, and techniques to project activities to meet the
project requirements. Project management is accomplished through the appropriate application and integration of the
project management processes identified for the project. Project management enables organizations to execute projects
effectively and efficiently.
Effective project management helps individuals, groups, and public and private organizations to:
◆ Meet business objectives;
◆ Satisfy stakeholder expectations;
◆ Be more predictable;
◆ Increase chances of success;
◆ Deliver the right products at the right time;
◆ Resolve problems and issues;
◆ Respond to risks in a timely manner;
◆ Optimize the use of organizational resources;
◆ Identify, recover, or terminate failing projects;
◆ Manage constraints (e.g., scope, quality, schedule, costs, resources);
◆ Balance the influence of constraints on the project (e.g., increased scope may increase cost or schedule); and
◆ Manage change in a better manner.
Poorly managed projects or the absence of project management may result in:
◆ Missed deadlines,
◆ Cost overruns,
◆ Poor quality,
◆ Rework,
◆ Uncontrolled expansion of the project,
◆ Loss of reputation for the organization,
◆ Unsatisfied stakeholders, and
◆ Failure in achieving the objectives for which the project was undertaken.
Projects are a key way to create value and benefits in organizations. In today’s business environment, organizational
leaders need to be able to manage with tighter budgets, shorter timelines, scarcity of resources, and rapidly changing
technology. The business environment is dynamic with an accelerating rate of change. To remain competitive in the world
economy, companies are embracing project management to consistently deliver business value.

11

Effective and efficient project management should be considered a strategic competency within organizations. It enables
organizations to:
◆ Tie project results to business goals,
◆ Compete more effectively in their markets,
◆ Sustain the organization, and
◆ Respond to the impact of business environment changes on projects by appropriately adjusting project
management plans (see Section 4.2).


1.2.3 RELATIONSHIP OF PROJECT, PROGRAM, PORTFOLIO, AND OPERATIONS MANAGEMENT

1.2.3.1 OVERVIEW
Using project management processes, tools, and techniques puts in place a sound foundation for organizations to
achieve their goals and objectives. A project may be managed in three separate scenarios: as a stand-alone project (outside
of a portfolio or program), within a program, or within a portfolio. Project managers interact with portfolio and program
managers when a project is within a program or portfolio. For example, multiple projects may be needed to accomplish a
set of goals and objectives for an organization. In those situations, projects may be grouped together into a program. A
program is defined as a group of related projects, subsidiary programs, and program activities managed in a coordinated
manner to obtain benefits not available from managing them individually. Programs are not large projects. A very large
project may be referred to as a megaproject. As a guideline, megaprojects cost US$1billion or more, affect 1 million or
more people, and run for years.
Some organizations may employ the use of a project portfolio to effectively manage multiple programs and projects
that are underway at any given time. A portfolio is defined as projects, programs, subsidiary portfolios, and operations
managed as a group to achieve strategic objectives. Figure 1-3 illustrates an example of how portfolios, programs,
projects, and operations are related in a specific situation.
Program management and portfolio management differ from project management in their life cycles, activities,
objectives, focus, and benefits. However, portfolios, programs, projects, and operations often engage with the same
stakeholders and may need to use the same resources (see Figure 1-3), which may result in a conflict in the organization.
This type of a situation increases the need for coordination within the organization through the use of portfolio, program,
and project management to achieve a workable balance in the organization.

12
Part 1 - Guide

Figure 1-3 illustrates a sample portfolio structure indicating relationships between the programs, projects, shared
resources, and stakeholders.The portfolio components are grouped together in order to facilitate the effective governance
and management of the work that helps to achieve organizational strategies and priorities. Organizational and portfolio
planning impact the components by means of prioritization based on risk, funding, and other considerations. The
portfolio view allows organizations to see how the strategic goals are reflected in the portfolio. This portfolio view
also enables the implementation and coordination of appropriate portfolio, program, and project governance. This
coordinated governance allows authorized allocation of human, financial, and physical resources based on expected
performance and benefits.



Looking at project, program, and portfolio management from an organizational perspective:
◆ Program and project management focus on doing programs and projects the “right” way; and
◆ Portfolio management focuses on doing the “right” programs and projects.
Table 1-2 gives a comparative overview of portfolios, programs, and projects.

13



14
Part 1 - Guide

1.2.3.2 PROGRAM MANAGEMENT
Program management is defined as the application of knowledge, skills, and principles to a program to achieve the
program objectives and to obtain benefits and control not available by managing program components individually.
A program component refers to projects and other programs within a program. Project management focuses on
interdependencies within a project to determine the optimal approach for managing the project. Program management
focuses on the interdependencies between projects and between projects and the program level to determine the
optimal approach for managing them. Actions related to these program and project-level interdependencies may include:

In [ ]:
# Replace lines with X page
def replace_lines(input_text):
    i=1
    output_lines = []

    for line in input_text.split('\n'):
        match = re.search(str(i), line)
        if match:
            num = int(match.group())
            if line and num==i and line[0].isdigit():
                rest_of_line = line[len(str(num)):]
                i=i+1
                if num % 2 == 0:
                    # Even number, replace with "NubPage X"
                    output_lines.append(f"NubPage {num}\n{rest_of_line}")
                else:
                    # Odd number, replace with "NubPage X"
                    output_lines.append(f"NubPage {num}\n{rest_of_line}")

        else:
            output_lines.append(line)

    return '\n'.join(output_lines)

In [ ]:
lines = replace_lines(file_contents).split('\n')
for line in lines:
    print(line)

Le flux de sortie a été tronqué et ne contient que les 5000 dernières lignes.
be used are:
◆ Shared portal. A shared repository for information sharing (e.g., website, collaboration software or intranet) is
effective for virtual project teams.
◆ Video conferencing. Video conferencing is an important technique for effective communication with
virtual teams.
◆ Audio conferencing. Communication within a team using audio conferencing is another technique to build
rapport and confidence within virtual teams.
◆ Email/chat. Regular communications using email and chat is also an effective technique.

NubPage 315


9.4.2.4 INTERPERSONAL AND TEAM SKILLS
Interpersonal and team skills that can be used for this process include but are not limited to:
◆ Conflict management. Described in Section 9.5.2.1. The project manager needs to resolve conflicts in a timely
manner and in a constructive way in order to achieve a high-performing team.
◆ Influencing. Described in Section 9.5.2.1. An influencing skill used in this process is gathering relevant and
critical information to address important issues and reach agreements while maintaining mutual trust.
◆ Motivation. Motivation is providing a reason for someone to act. Teams are motivated by empowering them to
participate in decision making and encouraging them to work independently.
◆ Negotiation. Described in Section 12.2.2.5. Negotiation among team members is used to reach consensus on project
needs. Negotiation can build trust and harmony among the team members.
◆ Team building. Team building is conducting activities that enhance the team’s social relations and build a
collaborative and cooperative working environment. Team building activities can vary from a 5-minute agenda item
in a status review meeting to an offsite, professionally facilitated event designed to improve interpersonal
relationships. The objective of team-building activities is to help individual team members work together effectively.
Team-building strategies are particularly valuable when team members operate from remote locations without the
benefit of face-to-face contact. Informal communication and activities can help in building trust and establishing
good working relationships. While team building is essential during the initial stages of a project, it should be a
continuous process. Changes in a project environment are inevitable, and to manage them effectively, a continuous
or renewed team-building effort may be applied. The project manager should continually monitor team functionality
and performance to determine if any actions are needed to prevent or correct various team problems.

9.4.2.5 RECOGNITION AND REWARDS
Part of the team development process involves recognizing and rewarding desirable behavior. The original
plan for rewarding people is developed during the Plan Resource Management process. Rewards will be effective
only if they satisfy a need that is valued by that individual. Reward decisions are made, formally or informally,
during the process of managing the project team. Cultural differences should be considered when determining
recognition and rewards.

NubPage 316

Part 1 - Guide

People are motivated when they feel they are valued in the organization and this value is demonstrated by the rewards
given to them. Generally, money is viewed as a tangible aspect of any reward system, but intangible rewards could be
equally or even more effective. Most project team members are motivated by an opportunity to grow, accomplish, be
appreciated, and apply their professional skills to meet new challenges. A good strategy for project managers is to give
the team recognition throughout the life cycle of the project rather than waiting until the project is completed.

9.4.2.6 TRAINING
Training includes all activities designed to enhance the competencies of the project team members. Training can be
formal or informal. Examples of training methods include classroom, online, computer-based, on-the-job training from
another project team member, mentoring, and coaching. If project team members lack the necessary management or
technical skills, such skills can be developed as part of the project work. Scheduled training takes place as stated in
the resource management plan. Unplanned training takes place as a result of observation, conversation, and project
performance appraisals conducted during management of the project team. Training costs could be included in the project
budget or supported by the performing organization if the added skills may be useful for future projects. It may be
performed by in-house or by external trainers.

9.4.2.7 INDIVIDUAL AND TEAM ASSESSMENTS
Individual and team assessment tools give the project manager and the project team insight into areas of strengths and
weaknesses. These tools help project managers assess team members’ preferences, aspirations, how they process and
organize information, how they make decisions, and how they interact with people. Various tools are available such as
attitudinal surveys, specific assessments, structured interviews, ability tests, and focus groups. These tools can provide
improved understanding, trust, commitment, and communications among team members and facilitate more productive
teams throughout the project.

9.4.2.8 MEETINGS
Meetings are used to discuss and address pertinent topics for developing the team. Attendees include the project
manager and the project team. Types of meetings include but are not limited to project orientation meetings, team-
building meetings, and team development meetings.

NubPage 317


9.4.3 DEVELOP TEAM: OUTPUTS

9.4.3.1 TEAM PERFORMANCE ASSESSMENTS
As project team development efforts such as training, team building, and colocation are implemented, the project
management team makes formal or informal assessments of the project team’s effectiveness. Effective team
development strategies and activities are expected to increase the team’s performance, which increases the likelihood of
meeting project objectives.
The evaluation of a team’s effectiveness may include indicators such as:
◆ Improvements in skills that allow individuals to perform assignments more effectively,
◆ Improvements in competencies that help team members perform better as a team,
◆ Reduced staff turnover rate, and
◆ Increased team cohesiveness where team members share information and experiences openly and help each
other to improve the overall project performance.
As a result of conducting an evaluation of the team’s overall performance, the project management team can
identify the specific training, coaching, mentoring, assistance, or changes required to improve the team’s performance.
This should also include identifying the appropriate or required resources necessary to achieve and implement the
improvements identified in the assessment.

9.4.3.2 CHANGE REQUESTS
Described in Section 4.3.3.4. If change requests occur as a result of carrying out the Develop Team process or if
recommended corrective or preventive actions impact any of the components of the project management plan or project
documents, the project manager needs to submit a change request and follow the Perform Integrated Change Control
process as defined in Section 4.6.

9.4.3.3 PROJECT MANAGEMENT PLAN UPDATES
Any change to the project management plan goes through the organization’s change control process via a change
request. Components that may require a change request for the project management plan include but are not limited to
the resource management plan, as described in Section 9.1.3.1.

NubPage 318

Part 1 - Guide

9.4.3.4 PROJECT DOCUMENTS UPDATES
Project documents that may be updated as a result of carrying out this process include but are not limited to:
◆ Lessons learned register. Described in Section 4.4.3.1. The lessons learned register is updated with information
on challenges encountered and how they could have been avoided as well as approaches that worked well for
the development of the team.
◆ Project schedule. Described in Section 6.5.3.2. Activities to develop the project team may result in changes to
the project schedule.
◆ Project team assignments. Described in Section 9.3.3.1. When team development results in changes to agreed-
upon assignments, these changes are recorded in the project team assignments documentation.
◆ Resource calendars. Described in Section 9.2.1.2. Resource calendars are updated to reflect the availability of
resources for the project.
◆ Team charter. Described in Section 9.1.3.2. The team charter may be updated to reflect changes to agreed-upon
team operating guidelines that result from team development.

9.4.3.5 ENTERPRISE ENVIRONMENTAL FACTORS UPDATES
Enterprise environmental factors that are updated as a result of the Develop Project Team process include but are
not limited to:
◆ Employee development plan records, and
◆ Skill assessments.

9.4.3.6 ORGANIZATIONAL PROCESS ASSETS UPDATES
Organizational process assets that are updated as a result of the Develop Team process include but are not limited to:
◆ Training requirements, and
◆ Personnel assessment.
9.5 MANAGE TEAM
Manage Team is the process of tracking team member performance, providing feedback, resolving issues, and
managing team changes to optimize project performance. The key benefit of this process is that it influences team
behavior, manages conflict, and resolves issues. This process is performed throughout the project.
The inputs, tools and techniques, and outputs of the process are depicted in Figure 9-12. Figure 9-13 depicts the data
flow diagram for the process.

NubPage 319





Managing the project team requires a variety of management and leadership skills for fostering teamwork and
integrating the efforts of team members to create high-performance teams. Team management involves a combination
of skills with special emphasis on communication, conflict management, negotiation, and leadership. Project managers
should provide challenging assignments to team members and provide recognition for high performance.
The project manager needs to be sensitive to both the willingness and the ability of team members to perform their
work and adjust their management and leadership styles accordingly. Team members with low-skill abilities will require
more intensive oversight than those who have demonstrated ability and experience.

NubPage 320

Part 1 - Guide

9.5.1 MANAGE TEAM: INPUTS

9.5.1.1 PROJECT MANAGEMENT PLAN
Described in Section 4.2.3.1. Project management plan components include but are not limited to the resource
management plan. Described in Section 9.1.3.1, the resource management plan provides guidance on how project team
resources should be managed and eventually released.

9.5.1.2 PROJECT DOCUMENTS
Project documents that can be considered as inputs for this process include but are not limited to:
◆ Issue log. Described in Section 4.3.3.3. Issues arise in the course of managing the project team. An issue log can
be used to document and monitor who is responsible for resolving specific issues by a target date.
◆ Lessons learned register. Described in Section 4.4.3.1. Lessons learned earlier in the project can be applied to
later phases in the project to improve the efficiency and effectiveness of managing the team.
◆ Project team assignments. Described in Section 9.3.3.1. Project team assignments identify the team member
roles and responsibilities.
◆ Team charter. Described in Section 9.1.3.2. The team charter provides guidance for how the team will make
decisions, conduct meetings, and resolve conflict.

9.5.1.3 WORK PERFORMANCE REPORTS
Described in Section 4.5.3.1. Work performance reports are the physical or electronic representation of work
performance information intended to generate decisions, actions, or awareness. Performance reports that can help with
project team management include results from schedule control, cost control, quality control, and scope validation. The
information from performance reports and related forecasts assists in determining future team resource requirements,
recognition and rewards, and updates to the resource management plan.

9.5.1.4 TEAM PERFORMANCE ASSESSMENTS
Described in Section 9.4.3.1. The project management team makes ongoing formal or informal assessments of the
project team’s performance. By continually assessing the project team’s performance, actions can be taken to resolve
issues, modify communication, address conflict, and improve team interaction.

NubPage 321


9.5.1.5 ENTERPRISE ENVIRONMENTAL FACTORS
The enterprise environmental factors that can influence the Manage Team process include but are not limited to
human resource management policies.

9.5.1.6 ORGANIZATIONAL PROCESS ASSETS
The organizational process assets that can influence the Manage Team process include but are not limited to:
◆ Certificates of appreciation,
◆ Corporate apparel, and
◆ Other organizational perquisites.


9.5.2 MANAGE TEAM: TOOLS AND TECHNIQUES

9.5.2.1 INTERPERSONAL AND TEAM SKILLS
Interpersonal and team skills that can be used for this process include but are not limited to:
◆ Conflict management. Conflict is inevitable in a project environment. Sources of conflict include scarce
resources, scheduling priorities, and personal work styles. Team ground rules, group norms, and solid project
management practices, like communication planning and role definition, reduce the amount of conflict.
Successful conflict management results in greater productivity and positive working relationships. When managed
properly, differences of opinion can lead to increased creativity and better decision making. If the differences
become a negative factor, project team members are initially responsible for their resolution. If conflict escalates,
the project manager should help facilitate a satisfactory resolution. Conflict should be addressed early and
usually in private, using a direct, collaborative approach. If disruptive conflict continues, formal procedures may
be used, including disciplinary actions.
The success of project managers in managing their project teams often depends on their ability to resolve
conflict. Different project managers may use different conflict resolution methods. Factors that influence conflict
resolution methods include:
◼ Importance and intensity of the conflict,
◼ Time pressure for resolving the conflict,
◼ Relative power of the people involved in the conflict,
◼ Importance of maintaining a good relationship, and
◼ Motivation to resolve conflict on a long-term or short-term basis.

NubPage 322

Part 1 - Guide

There are five general techniques for resolving conflict. Each technique has its place and use:
 Withdraw/avoid. Retreating from an actual or potential conflict situation; postponing the issue to be better
prepared or to be resolved by others.
 Smooth/accommodate. Emphasizing areas of agreement rather than areas of difference; conceding one’s
position to the needs of others to maintain harmony and relationships.
 Compromise/reconcile. Searching for solutions that bring some degree of satisfaction to all parties in order
to temporarily or partially resolve the conflict. This approach occasionally results in a lose-lose situation.
 Force/direct. Pushing one’s viewpoint at the expense of others; offering only win-lose solutions, usually enforced
through a power position to resolve an emergency. This approach often results to a win-lose situation.
 Collaborate/problem solve. Incorporating multiple viewpoints and insights from differing perspectives;
requires a cooperative attitude and open dialogue that typically leads to consensus and commitment. This
approach can result in a win-win situation.
◆ Decision making. Decision making, in this context, involves the ability to negotiate and influence the organization
and the project management team, rather than the set of tools described in the decision making tool set. Some
guidelines for decision making include:
◼ Focus on goals to be served,
◼ Follow a decision-making process,
◼ Study the environmental factors,
◼ Analyze available information,
◼ Stimulate team creativity, and
◼ Account for risk.
◆ Emotional intelligence. Emotional intelligence is the ability to identify, assess, and manage the personal
emotions of oneself and other people, as well as the collective emotions of groups of people. The team
can use emotional intelligence to reduce tension and increase cooperation by identifying, assessing, and
controlling the sentiments of project team members, anticipating their actions, acknowledging their concerns, and
following up on their issues.

NubPage 323


◆ Influencing. Because project managers often have little or no direct authority over team members in a matrix
environment, their ability to influence stakeholders on a timely basis is critical to project success. Key influencing
skills include:
◼ Ability to be persuasive;
◼ Clearly articulating points and positions;
◼ High levels of active and effective listening skills;
◼ Awareness of, and consideration for, the various perspectives in any situation; and
◼ Gathering relevant information to address issues and reach agreements while maintaining mutual trust.
◆ Leadership. Successful projects require leaders with strong leadership skills. Leadership is the ability to lead
a team and inspire them to do their jobs well. It encompasses a wide range of skills, abilities and actions.
Leadership is important through all phases of the project life cycle. There are multiple leadership theories defining
leadership styles that should be used as needed for each situation or team. It is especially important to
communicate the vision and inspire the project team to achieve high performance.

9.5.2.2 PROJECT MANAGEMENT INFORMATION SYSTEM (PMIS)
Described in Section 4.3.2.2. Project management information systems can include resource management or
scheduling software that can be used for managing and coordinating team members across project activities.


9.5.3 MANAGE TEAM: OUTPUTS

9.5.3.1 CHANGE REQUESTS
Described in Section 4.3.3.4. When change requests occur as a result of carrying out the Manage Team process or
when recommended corrective or preventive actions impact any of the components of the project management plan or
project documents, the project manager needs to submit a change request. Change requests are processed for review and
disposition through the Perform Integrated Change Control process (Section 4.6).
For example, staffing changes, whether made by choice or by uncontrollable events, can disrupt the project team. This
disruption can cause the schedule to slip or the budget to be exceeded. Staffing changes include moving people to different
assignments, outsourcing some of the work, or replacing team members who leave.

NubPage 324

Part 1 - Guide

9.5.3.2 PROJECT MANAGEMENT PLAN UPDATES
Any change to the project management plan goes through the organization’s change control process via a change
request. Components of the project management plan that may require a change request for the project management
plan include but are not limited to:
◆ Resource management plan. Described in Section 9.1.3.1. The resource management plan is updated to reflect
actual experience in managing the project team.
◆ Schedule baseline. Described in Section 6.5.3.1. Changes to the project schedule may be required to reflect the
way the team is performing.
◆ Cost baseline. Described in Section 7.3.3.1. Changes to the project cost baseline may be required to reflect the
way the team is performing.

9.5.3.3 PROJECT DOCUMENTS UPDATES
Project documents that may be updated as a result of carrying out this process include but are not limited to:
◆ Issue log. Described in Section 4.3.3.3. New issues raised as a result of this process are recorded in the issue log.
◆ Lessons learned register. Described in Section 4.4.3.1. The lessons learned register is updated with information

In [ ]:
#REMOVE UNWANTED CHARCTERS
modified_lines = []
for line in lines:
    modified_line = line.replace("uu", "")
    modified_lines.append(modified_line)
output_text = '\n'.join(modified_lines)

In [ ]:
# Part 1 - Guide
modified_lines = []
lines=output_text.split('\n')
for line in lines:
    modified_line = line.replace("Part 1 - Guide", "")
    modified_lines.append(modified_line)
output_text = '\n'.join(modified_lines)

In [ ]:
# u n
modified_lines = []
lines=output_text.split('\n')
for line in lines:
    modified_line = line.replace("u n", "")
    modified_lines.append(modified_line)
output_text = '\n'.join(modified_lines)

In [ ]:
# "Not For Distribution, Sale or Reproduction."
modified_lines = []
lines=output_text.split('\n')
for line in lines:
    modified_line = line.replace('Not For Distribution, Sale or Reproduction.', "")
    modified_lines.append(modified_line)
output_text = '\n'.join(modified_lines)

In [ ]:
# delete empty lines

lines = output_text.split('\n')
non_empty_lines = [line for line in lines if line.strip() != ""]
output_text = '\n'.join(non_empty_lines)

In [ ]:
# Remove spaces from the beginning of the every line
lines = output_text.split('\n')
stripped_lines = [line.lstrip() for line in lines]
output_text = '\n'.join(stripped_lines)

In [ ]:
#need to clean it from "u m"

In [ ]:
lines = output_text.split('\n')
for line in lines:
        print(line, "$")

Le flux de sortie a été tronqué et ne contient que les 5000 dernières lignes.
in the project. Quality assurance is about using project processes effectively. It involves following and meeting standards  $
to assure stakeholders that the final product will meet their needs, expectations, and requirements. Manage Quality  $
includes all the quality assurance activities, and is also concerned with the product design aspects and process  $
improvements. Manage Quality work will fall under the conformance work category in the cost of quality framework.  $
NubPage 268 $
The Manage Quality process implements a set of planned and systematic acts and processes defined within the  $
project’s quality management plan that helps to:  $
◆ Design an optimal and mature product by implementing specific design guidelines that address specific aspects  $
of the product,  $
◆ Build confidence that a future output will be completed in a manner that meets the specified requirements and  $
expectations through quality assurance tools and techniques such as quality audits and failure analysis,  $
◆ Confirm that the quality processes are used and that their use meets the quality objectives of the project, and  $
◆ Improve the efficiency and effectiveness of processes and activities to achieve better results and performance and  $
enhance stakeholders’ satisfaction.  $
The project manager and project team may use the organization’s quality assurance department, or other organizational  $
functions, to execute some of the Manage Quality activities such as failure analysis, design of experiments, and quality  $
improvement. Quality assurance departments usually have cross-organizational experience in using quality tools and  $
techniques and are a good resource for the project.  $
Manage Quality is considered the work of everybody—the project manager, the project team, the project sponsor, the  $
management of the performing organization, and even the customer. All of these have roles in managing quality in the  $
project, though the roles differ in size and effort. The level of participation in the quality management effort may differ between  $
industries and project management styles. In agile projects, quality management is performed by all team members  $
throughout the project, but in traditional projects, quality management is often the responsibility of specific team  $
members.  $
8.2.1 MANAGE QUALITY: INPUTS  $
8.2.1.1 PROJECT MANAGEMENT PLAN  $
Described in Section 4.2.3.1. Project management plan components include but are not limited to the quality  $
management plan. Described in Section 8.1.3.1, the quality management plan defines the acceptable level of project  $
and product quality and describes how to ensure this level of quality in its deliverables and processes. The quality  $
management plan also describes what to do with nonconforming products and what corrective action to implement.  $
NubPage 269 $
8.2.1.2 PROJECT DOCUMENTS  $
Project documents that can be considered as inputs for this process include but are not limited to:  $
◆ Lessons learned register. Described in Section 4.4.3.1. Lessons learned earlier in the project with regard to  $
managing quality can be applied to later phases in the project to improve the efficiency and effectiveness of  $
managing quality.  $
◆ Quality control measurements. Described in Section 8.3.3.1. Quality control measurements are used to analyze  $
and evaluate the quality of the processes and deliverables of the project against the standards of the performing  $
organization or the requirements specified. Quality control measurements can also compare the processes used  $
to create the measurements and validate actual measurements to determine their level of correctness.  $
◆ Quality metrics. Described in Section 8.1.3.2. Quality metrics are verified as part of the Control Quality process.  $
The Manage Quality process uses these quality metrics as a basis for the development of test scenarios for the  $
project and its deliverables and as a basis for improvement initiatives.  $
◆ Risk report. Described in Section 11.2.3.2. Risk report is used in the Manage Quality process to identify sources  $
of overall project risk and the most important drivers of overall risk exposure that can impact the quality objectives  $
of the project.  $
8.2.1.3 ORGANIZATIONAL PROCESS ASSETS  $
The organizational process assets that can influence the Manage Quality process include but are not limited to:  $
◆ Organizational quality management system that includes policies, procedures, and guidelines;  $
◆ Quality templates such as check sheets, traceability matrix, test plans, test documents, and others;  $
◆ Results from previous audits; and  $
◆ Lessons learned repository with information from similar projects.  $
NubPage 270 $
8.2.2 MANAGE QUALITY: TOOLS AND TECHNIQUES  $
8.2.2.1 DATA GATHERING  $
A data-gathering technique that can be used for this process includes but is not limited to checklists (see Section  $
11.2.2.2). A checklist is a structured tool, usually component-specific, used to verify that a set of required steps has been  $
performed or to check if a list of requirements has been satisfied. Based on the project’s requirements and practices,  $
checklists may be simple or complex. Many organizations have standardized checklists available to ensure consistency in  $
frequently performed tasks. In some application areas, checklists are also available from professional associations or  $
commercial service providers. Quality checklists should incorporate the acceptance criteria included in the scope  $
baseline.  $
8.2.2.2 DATA ANALYSIS  $
Data analysis techniques that can be used for this process include but are not limited to:  $
◆ Alternatives analysis. Described in Section 9.2.2.5. This technique is used to evaluate identified options in order  $
to select which different quality options or approaches are most appropriate to use.  $
◆ Document analysis. Described in Section 5.2.2.3. The analysis of different documents produced as part of  $
the output of project control processes, such as quality reports, test reports, performance reports, and variance  $
analysis, can point to and focus on processes that may be out of control and may jeopardize meeting the  $
specified requirements or stakeholders’ expectations.  $
◆ Process analysis. Process analysis identifies opportunities for process improvements. This analysis also  $
examines problems, constraints, and non-value-added activities that occur during a process.  $
◆ Root cause analysis (RCA). Root cause analysis is an analytical technique used to determine the basic underlying  $
reason that causes a variance, defect, or risk. A root cause may underlie more than one variance, defect, or risk. It  $
may also be used as a technique for identifying root causes of a problem and solving them. When all root causes  $
for a problem are removed, the problem does not recur.  $
NubPage 271 $
8.2.2.3 DECISION MAKING  $
A decision-making technique that can be used for this process includes but is not limited to multicriteria decision  $
analysis. Described in Section 8.1.2.4. Multicriteria decision making is used to evaluate several criteria when discussing  $
alternatives that impact project or product quality. Project decisions can include choosing among different implementation  $
scenarios or suppliers. Product decisions can include evaluating the life cycle cost, schedule, stakeholder satisfaction, and  $
risks associated with resolving product defects.  $
8.2.2.4 DATA REPRESENTATION  $
Data representation techniques that can be used for this process include but are not limited to:  $
◆ Affinity diagrams. Described in Section 5.2.2.5. Affinity diagrams can organize potential causes of defects into  $
groups showing areas that should be focused on the most.  $
◆ Cause-and-effect diagrams. Cause-and-effect diagrams are also known as fishbone diagrams, why-why  $
diagrams, or Ishikawa diagrams. This type of diagram breaks down the causes of the problem statement identified  $
into discrete branches, helping to identify the main or root cause of the problem. Figure 8-9 is an example of a  $
cause-and-effect diagram.  $
◆ Flowcharts. Described in Section 8.1.2.5. Flowcharts show a series of steps that lead to a defect.  $
◆ Histograms. Histograms show a graphical representation of numerical data. Histograms can show the number  $
of defects per deliverable, a ranking of the cause of defects, the number of times each process is noncompliant,  $
or other representations of project or product defects.  $
◆ Matrix diagrams. Described in Section 8.1.2.5. The matrix diagram seeks to show the strength of relationships  $
among factors, causes, and objectives that exist between the rows and columns that form the matrix.  $
◆ Scatter diagrams. A scatter diagram is a graph that shows the relationship between two variables. Scatter  $
diagrams can demonstrate a relationship between any element of a process, environment, or activity on one axis  $
and a quality defect on the other axis.  $
NubPage 272 $
8.2.2.5 AUDITS  $
An audit is a structured, independent process used to determine if project activities comply with organizational and  $
project policies, processes, and procedures. A quality audit is usually conducted by a team external to the project,  $
such as the organization’s internal audit department, PMO, or by an auditor external to the organization. Quality audit  $
objectives may include but are not limited to:  $
◆ Identifying all good and best practices being implemented;  $
◆ Identifying all nonconformity, gaps, and shortcomings;  $
◆ Sharing good practices introduced or implemented in similar projects in the organization and/or industry;  $
◆ Proactively offering assistance in a positive manner to improve the implementation of processes to help raise  $
team productivity; and  $
◆ Highlighting contributions of each audit in the lessons learned repository of the organization.  $
NubPage 273 $
The subsequent effort to correct any deficiencies should result in a reduced cost of quality and an increase in sponsor  $
or customer acceptance of the project’s product. Quality audits may be scheduled or random, and may be conducted by  $
internal or external auditors.  $
Quality audits can confirm the implementation of approved change requests including updates, corrective actions,  $
defect repairs, and preventive actions.  $
8.2.2.6 DESIGN FOR X  $
Design for X (DfX) is a set of technical guidelines that may be applied during the design of a product for the optimization  $
of a specific aspect of the design. DfX can control or even improve the product’s final characteristics. The X in DfX can  $
be different aspects of product development, such as reliability, deployment, assembly, manufacturing, cost, service,  $
usability, safety, and quality. Using the DfX may result in cost reduction, quality improvement, better performance, and  $
customer satisfaction.  $
8.2.2.7 PROBLEM SOLVING  $
Problem solving entails finding solutions for issues or challenges. It can include gathering additional information, critical  $
thinking, creative, quantitative and/or logical approaches. Effective and systematic problem solving is a  $
fundamental element in quality assurance and quality improvement. Problems can arise as a result of the Control Quality  $
process or from quality audits and can be associated with a process or deliverable. Using a structured problem-solving  $
method will help eliminate the problem and develop a long-lasting solution. Problem-solving methods generally include  $
the following elements:  $
◆ Defining the problem,  $
◆ Identifying the root-cause,  $
◆ Generating possible solutions,  $
◆ Choosing the best solution,  $
◆ Implementing the solution, and  $
◆ Verifying solution effectiveness.  $
NubPage 274 $
8.2.2.8 QUALITY IMPROVEMENT METHODS  $
Quality improvements can occur based on findings and recommendations from quality control processes, the findings of  $
the quality audits, or problem solving in the Manage Quality process. Plan-do-check-act and Six Sigma are two of the most  $
common quality improvement tools used to analyze and evaluate opportunities for improvement.  $
8.2.3 MANAGE QUALITY: OUTPUTS  $
8.2.3.1 QUALITY REPORTS  $
The quality reports can be graphical, numerical, or qualitative. The information provided can be used by other  $
processes and departments to take corrective actions in order to achieve the project quality expectations. The information  $
presented in the quality reports may include all quality management issues escalated by the team; recommendations for  $
process, project, and product improvements; corrective actions recommendations (including rework, defect/bugs repair,  $
100% inspection, and more); and the summary of findings from the Control Quality process.  $
8.2.3.2 TEST AND EVALUATION DOCUMENTS  $
Test and evaluation documents can be created based on industry needs and the organization’s templates. They are  $
inputs to the Control Quality process and are used to evaluate the achievement of quality objectives. These documents  $
may include dedicated checklists and detailed requirements traceability matrices as part of the document.  $
8.2.3.3 CHANGE REQUESTS  $
Described in Section 4.3.3.4. If changes occur during the Manage Quality process that impact any of the components  $
of the project management plan, project documents, or project or product management processes, the project manager  $
should submit a change request and follow the Perform Integrated Change Control process as defined in Section 4.6.  $
NubPage 275 $
8.2.3.4 PROJECT MANAGEMENT PLAN UPDATES  $
Any change to the project management plan goes through the organization’s change control process via a change  $
request. Components that may require a change request for the project management plan include but are not limited to:  $
◆ Quality management plan. Described in Section 8.1.3.1. The agreed-upon approach to managing quality may  $
need to be modified due to the actual results.  $
◆ Scope baseline. Described in Section 5.4.3.1. The scope baseline may change as a result of specific quality  $
management activities.  $
◆ Schedule baseline. Described in Section 6.5.3.1. The schedule baseline may change as a result of specific  $
quality management activities.  $
◆ Cost baseline. Described in Section 7.3.3.1. The cost baseline may change as a result of specific quality  $
management activities.  $
8.2.3.5 PROJECT DOCUMENTS UPDATES  $
Project documents that may be updated as a result of carrying out this process include but are not limited to:  $
◆ Issue log. Described in Section 4.3.3.3. New issues raised as a result of this process are recorded in the issue  $
log.  $
◆ Lessons learned register. Described in Section 4.4.3.1. The lessons learned register is updated with information  $
on challenges encountered and how they could have been avoided as well as approaches that worked well for  $
the managing quality.  $
◆ Risk register. Described in Section 11.2.3.1. New risks identified during this process are recorded in the risk  $
register and managed using the risk management processes.  $
8.3 CONTROL QUALITY  $
Control Quality is the process of monitoring and recording results of executing the quality management activities in  $
order to assess performance and ensure the project outputs are complete, correct, and meet customer expectations.  $
The key benefit of this process is verifying that project deliverables and work meet the requirements specified by key  $
stakeholders for final acceptance. The Control Quality process determines if the project outputs do what they were  $
intended to do. Those outputs need to comply with all applicable standards, requirements, regulations, and specifications.  $
This process is performed throughout the project.  $
The inputs, tools and techniques, and outputs of this process are depicted in Figure 8-10. Figure 8-11 depicts the  $
data flow diagram of the process.  $
NubPage 276 $
The Control Quality process is performed to measure the completeness, compliance, and fitness for use of a product  $
or service prior to user acceptance and final delivery. This is done by measuring all steps, attributes, and variables used  $
to verify conformance or compliance to the specifications stated during the planning stage.  $
Quality control should be performed throughout the project to formally demonstrate, with reliable data, that the  $
sponsor’s and/or customer’s acceptance criteria have been met.  $
NubPage 277 $
The level of effort to control quality and the degree of implementation may differ between industries and project  $
management styles; in pharmaceutical, health, transportation, and nuclear industries, for example, there may be stricter  $
quality control procedures compared to other industries, and the effort needed to meet the standards may be extensive.  $
For example, in agile projects, the Control Quality activities may be performed by all team members throughout the  $
project life cycle. In waterfall model-based projects, the quality control activities are performed at specific times, toward  $
the end of the project or phase, by specified team members.  $
8.3.1 CONTROL QUALITY: INPUTS  $
8.3.1.1 PROJECT MANAGEMENT PLAN  $
Described in Section 4.2.3.1. Project management plan components include but are not limited to the quality  $
management plan. Described in Section 8.1.3.1, the quality management plan defines how quality control will be  $
performed within the project.  $
8.3.1.2 PROJECT DOCUMENTS  $
Project documents that can be considered as inputs for this process include but are not limited to:  $
◆ Lessons learned register. Described in Section 4.4.3.1. Lessons learned earlier in the project can be applied to  $
later phases in the project to improve quality control.  $
◆ Quality metrics. Described in Section 8.1.3.2. A quality metric specifically describes a project or product attribute  $
and how the Control Quality process will verify compliance to it.  $
◆ Test and evaluation documents. Described in Section 8.2.3.2. Test and evaluation documents are used to  $
evaluate achievement of the quality objectives.  $
NubPage 278 $
8.3.1.3 APPROVED CHANGE REQUESTS  $
Described in Section 4.6.3.1. As part of the Perform Integrated Change Control process, a change log update indicates  $
that some changes are approved and some are not. Approved change requests may include modifications such as  $
defect repairs, revised work methods, and revised schedules. Partial change completion may result in inconsistencies  $
and later delays due to incomplete steps or corrections. The implementation of approved changes should be verified,  $
confirmed for completeness, retested, and certified as correct.  $
8.3.1.4 DELIVERABLES  $
A deliverable is any unique and verifiable product, result, or capability to perform a service that is required to be  $
produced to complete a process, phase, or project. Deliverables that are outputs from the Direct and Manage Project Work  $
process are inspected and compared to the acceptance criteria defined in the project scope statement.  $
8.3.1.5 WORK PERFORMANCE DATA  $
Described in Section 4.3.3.2. Work performance data contains data on product status such as observations, quality  $
metrics, and measurements for technical performance, as well as project quality information on schedule performance  $
and cost performance.  $
8.3.1.6 ENTERPRISE ENVIRONMENTAL FACTORS  $
The enterprise environmental factors that can influence the Control Quality process include but are not limited to:  $
◆ Project management information system; quality management software can be used to track errors and variations  $
in processes or deliverables;  $
◆ Governmental agency regulations; and  $

In [ ]:
# #SAVE TO FILE .TXT
# output_txt_file_path = 'PDF_LINES_SEMI_CLEAN.txt'
# output_txt_file = open(output_txt_file_path, 'w',encoding='utf-8')
# for line in lines:
#     output_txt_file.write(line + '\n')

In [ ]:
#Split chapters (we have 13 chapters)

import  re
import pandas as pd
Chapters=[]
#Pages=[]
Contents=[]


#initial first chapter
Current_chap="0"
Page="1"
content=""
change_Page=False

#initial chapter 1's
Chapters.append(Current_chap)
#Pages.append(Page)

i=int(Current_chap)+1
Next_chap=str(i)

for line in lines:
    line=line.strip()
    #match = re.search(r"NubPage (\d+)", line)
    #Cheking Chapter
    if line and line==Next_chap :
        Contents.append(content)
        content=""
        change_Page=True
        Current_chap=Next_chap
        i=int(Current_chap)+1
        Next_chap=str(i)
        Chapters.append(Current_chap)
    #elif line and match  :
     #   if match and len(Pages)<i and change_Page:
      #      change_Page=False
       #     page = match.group(1)
        #    page_str = str(int(page) - 1)
            #print(f"Chapter '{Current_chap}'PAGE '{page_str}'")
         #   Pages.append(page_str)
    else:
        content += '\n' + line
print(Current_chap)
Contents.append(content)

# Make sure all lists have the same length by filling any missing data with placeholders
max_length = max(len(Chapters), len(Contents))
Chapters.extend([""] * (max_length - len(Chapters)))
#Pages.extend([""] * (max_length - len(Pages)))
Contents.extend([""] * (max_length - len(Contents)))

# Create the dataframe
df = pd.DataFrame({
    'Chapter': Chapters,
   # 'Page': Pages,
    'Content': Contents,
})

df

13

   Chapter                                            Content
0        0                                        \nNubPage 1
1        1  \nINTRODUCTION\n1.1 OVERVIEW AND PURPOSE OF TH...
2        2  \nTHE ENVIRONMENT IN WHICH PROJECTS OPERATE\n2...
3        3  \nTHE ROLE OF THE PROJECT MANAGER\n3.1 OVERVIE...
4        4  \nPROJECT INTEGRATION MANAGEMENT\nProject Inte...
5        5  \nPROJECT SCOPE MANAGEMENT\nProject Scope Mana...
6        6  \nPROJECT SCHEDULE MANAGEMENT\nProject Schedul...
7        7  \nPROJECT COST MANAGEMENT\nProject Cost Manage...
8        8  \nPROJECT QUALITY MANAGEMENT\nProject Quality ...
9        9  \nPROJECT RESOURCE MANAGEMENT\nProject Resourc...
10      10  \nPROJECT COMMUNICATIONS MANAGEMENT\nProject C...
11      11  \nPROJECT RISK MANAGEMENT\nProject Risk Manage...
12      12  \nPROJECT PROCUREMENT MANAGEMENT\nProject Proc...
13      13  \nPROJECT STAKEHOLDER MANAGEMENT\nProject Stak...

In [ ]:
lines_chap1=lines

In [ ]:
content_chap1=''
for line in lines:
    content_chap1 += '\n' + line
df.at[0, "Content"]=content_chap1

#dropping the first row
df=df.drop(0)
#removing \n
df["Content"] = df["Content"].str.replace(r'^\n', '', 1)

df

   Chapter                                            Content
1        1  INTRODUCTION\n1.1 OVERVIEW AND PURPOSE OF THIS...
2        2  THE ENVIRONMENT IN WHICH PROJECTS OPERATE\n2.1...
3        3  THE ROLE OF THE PROJECT MANAGER\n3.1 OVERVIEW\...
4        4  PROJECT INTEGRATION MANAGEMENT\nProject Integr...
5        5  PROJECT SCOPE MANAGEMENT\nProject Scope Manage...
6        6  PROJECT SCHEDULE MANAGEMENT\nProject Schedule ...
7        7  PROJECT COST MANAGEMENT\nProject Cost Manageme...
8        8  PROJECT QUALITY MANAGEMENT\nProject Quality Ma...
9        9  PROJECT RESOURCE MANAGEMENT\nProject Resource ...
10      10  PROJECT COMMUNICATIONS MANAGEMENT\nProject Com...
11      11  PROJECT RISK MANAGEMENT\nProject Risk Manageme...
12      12  PROJECT PROCUREMENT MANAGEMENT\nProject Procur...
13      13  PROJECT STAKEHOLDER MANAGEMENT\nProject Stakeh...

In [ ]:
import pandas as pd
file_path = 'DF_Chapters_Pages_Content.csv'
# Export the DataFrame to a CSV file
df.to_csv(file_path, index=False)

In [ ]:
df_chapters = pd.read_csv(file_path)
df_chapters

    Chapter                                            Content
0         1  INTRODUCTION\n1.1 OVERVIEW AND PURPOSE OF THIS...
1         2  THE ENVIRONMENT IN WHICH PROJECTS OPERATE\n2.1...
2         3  THE ROLE OF THE PROJECT MANAGER\n3.1 OVERVIEW\...
3         4  PROJECT INTEGRATION MANAGEMENT\nProject Integr...
4         5  PROJECT SCOPE MANAGEMENT\nProject Scope Manage...
5         6  PROJECT SCHEDULE MANAGEMENT\nProject Schedule ...
6         7  PROJECT COST MANAGEMENT\nProject Cost Manageme...
7         8  PROJECT QUALITY MANAGEMENT\nProject Quality Ma...
8         9  PROJECT RESOURCE MANAGEMENT\nProject Resource ...
9        10  PROJECT COMMUNICATIONS MANAGEMENT\nProject Com...
10       11  PROJECT RISK MANAGEMENT\nProject Risk Manageme...
11       12  PROJECT PROCUREMENT MANAGEMENT\nProject Procur...
12       13  PROJECT STAKEHOLDER MANAGEMENT\nProject Stakeh...

In [ ]:
# Function to insert the first line from Content into Chapter and remove it from Content
def insert_first_line_to_chapter(row):
    first_line, rest_content = row['Content'].split('\n', 1)
    return str(row['Chapter']) + ' ' + first_line, rest_content

# Apply the function to update Chapter and Content columns
df_chapters[['Chapter', 'Content']] = df_chapters.apply(insert_first_line_to_chapter, axis=1).values.tolist()

df_chapters

,Chapter,Content
0,1 INTRODUCTION,1.1 OVERVIEW AND PURPOSE OF THIS GUIDE\nProjec...
1,2 THE ENVIRONMENT IN WHICH PROJECTS OPERATE,2.1 OVERVIEW\nProjects exist and operate in en...
2,3 THE ROLE OF THE PROJECT MANAGER,3.1 OVERVIEW\nThe project manager plays a crit...
3,4 PROJECT INTEGRATION MANAGEMENT,Project Integration Management includes the pr...
4,5 PROJECT SCOPE MANAGEMENT,Project Scope Management includes the processe...
5,6 PROJECT SCHEDULE MANAGEMENT,Project Schedule Management includes the proce...
6,7 PROJECT COST MANAGEMENT,Project Cost Management includes the processes...
7,8 PROJECT QUALITY MANAGEMENT,Project Quality Management includes the proces...
8,9 PROJECT RESOURCE MANAGEMENT,Project Resource Management includes the proce...
9,10 PROJECT COMMUNICATIONS MANAGEMENT,Project Communications Management includes the...
10,11 PROJECT RISK MANAGEMENT,Project Risk Management includes the processes...
11,12 PROJECT PROCUREMENT MANAGEMENT,Project Procurement Management includes the pr...
12,13 PROJECT STAKEHOLDER MANAGEMENT,Project Stakeholder Management includes the pr...

In [ ]:
df_chap1=df_chapters.head(1)
df_chap1

          Chapter                                            Content
0  1 INTRODUCTION  1.1 OVERVIEW AND PURPOSE OF THIS GUIDE\nProjec...

In [ ]:
content_chap1 = df_chap1["Content"].str.split('\n')
content_chap1

0    [1.1 OVERVIEW AND PURPOSE OF THIS GUIDE, Proje...
Name: Content, dtype: object

In [ ]:
#Chapitre 1  TESTING THE CODE
"""
CHAPTER 1 :
    TESTING THE EXTRACTION OF PDF

"""
import  re
content_chap1 = df_chap1["Content"].str.split('\n')


titles_level1=[] #a.x
titles_level2=[] #a.x.x
titles_level3=[] #a.x.x.x
Contents=[]
i=0
content=""
t1=None
t2=None
t3=None

for line_list in content_chap1:
    for i,line in enumerate(line_list):
        match = re.search(r'^1\.\d+(\.\d+)*\s+', line)
        if line and match :
            previous_line = line_list[i -1]
            level=len(match.group(0).split('.'))-1
            #print(level)
            if level==1:
                #print("LEVEL 1")
                titles_level1.append(line)
                titles_level2.append(None)
                titles_level3.append(None)
                t1=line
                #print(f" title'{t1}'")
                t2=None
                t3=None
            if level==2:
                #print("LEVEL 2")
                titles_level1.append(t1)
                titles_level2.append(line)
                titles_level3.append(None)
                t2=line
                t3=None
            if level==3:
            #print("LEVEL 3")
                titles_level1.append(t1)
                titles_level2.append(t2)
                titles_level3.append(line)
                t3=line
            match2 = re.search(r'^1\.\d+(\.\d+)*\s+', previous_line)
            if match2:
                Contents.append(None)
            # If there is content, append it
            if content:
                Contents.append(content.strip())
                content = ""
        else:
        # Append content lines
            content += '\n' + line
# Append any remaining content
    if content:
        Contents.append(content.strip())
    # Make sure all lists have the same length by filling any missing data with placeholders
    max_length = max(len(titles_level1), len(titles_level2), len(titles_level3), len(Contents))
    titles_level1.extend([""] * (max_length - len(titles_level1)))
    titles_level2.extend([""] * (max_length - len(titles_level2)))
    titles_level3.extend([""] * (max_length - len(titles_level3)))
    Contents.extend([""] * (max_length - len(Contents)))

    df_output = pd.DataFrame({
    'TitleL1': titles_level1,
    'TitleL2': titles_level2,
    'TitleL3': titles_level3,
    'Content': Contents,
    })
df_output

,TitleL1,TitleL2,TitleL3,Content
0,1.1 OVERVIEW AND PURPOSE OF THIS GUIDE,None,None,Project management is not new. It has been in ...
1,1.1 OVERVIEW AND PURPOSE OF THIS GUIDE,1.1.1 THE STANDARD FOR PROJECT MANAGEMENT,None,This guide is based on The Standard for Projec...
2,1.1 OVERVIEW AND PURPOSE OF THIS GUIDE,1.1.2 COMMON VOCABULARY,None,A common vocabulary is an essential element of...
3,1.1 OVERVIEW AND PURPOSE OF THIS GUIDE,1.1.3 CODE OF ETHICS AND PROFESSIONAL CONDUCT,None,PMI publishes the Code of Ethics and Professio...
4,1.2 FOUNDATIONAL ELEMENTS,None,None,This section describes foundational elements n...
5,1.2 FOUNDATIONAL ELEMENTS,1.2.1 PROJECTS,None,A project is a temporary endeavor undertaken t...
6,1.2 FOUNDATIONAL ELEMENTS,1.2.2 THE IMPORTANCE OF PROJECT MANAGEMENT,None,Project management is the application of knowl...
7,1.2 FOUNDATIONAL ELEMENTS,"1.2.3 RELATIONSHIP OF PROJECT, PROGRAM, PORTFO...",None,None
8,1.2 FOUNDATIONAL ELEMENTS,"1.2.3 RELATIONSHIP OF PROJECT, PROGRAM, PORTFO...",1.2.3.1 OVERVIEW,"Using project management processes, tools, and..."
9,1.2 FOUNDATIONAL ELEMENTS,"1.2.3 RELATIONSHIP OF PROJECT, PROGRAM, PORTFO...",1.2.3.2 PROGRAM MANAGEMENT,Program management is defined as the applicati...
10,1.2 FOUNDATIONAL ELEMENTS,"1.2.3 RELATIONSHIP OF PROJECT, PROGRAM, PORTFO...",1.2.3.3 PORTFOLIO MANAGEMENT,"A portfolio is defined as projects, programs, ..."
11,1.2 FOUNDATIONAL ELEMENTS,"1.2.3 RELATIONSHIP OF PROJECT, PROGRAM, PORTFO...",1.2.3.4 OPERATIONS MANAGEMENT,Operations management is an area that is outsi...
12,1.2 FOUNDATIONAL ELEMENTS,"1.2.3 RELATIONSHIP OF PROJECT, PROGRAM, PORTFO...",1.2.3.5 OPERATIONS AND PROJECT MANAGEMENT,Changes in business or organizational operatio...
13,1.2 FOUNDATIONAL ELEMENTS,"1.2.3 RELATIONSHIP OF PROJECT, PROGRAM, PORTFO...",1.2.3.6 ORGANIZATIONAL PROJECT MANAGEMENT (OPM...,"Portfolios, programs, and projects are aligned..."
14,1.2 FOUNDATIONAL ELEMENTS,1.2.4 COMPONENTS OF THE GUIDE,None,"Projects comprise several key components that,..."
15,1.2 FOUNDATIONAL ELEMENTS,1.2.4 COMPONENTS OF THE GUIDE,1.2.4.1 PROJECT AND DEVELOPMENT LIFE CYCLES,A project life cycle is the series of phases t...
16,1.2 FOUNDATIONAL ELEMENTS,1.2.4 COMPONENTS OF THE GUIDE,1.2.4.2 PROJECT PHASE,A project phase is a collection of logically r...
17,1.2 FOUNDATIONAL ELEMENTS,1.2.4 COMPONENTS OF THE GUIDE,1.2.4.3 PHASE GATE,"A phase gate, is held at the end of a phase. T..."
18,1.2 FOUNDATIONAL ELEMENTS,1.2.4 COMPONENTS OF THE GUIDE,1.2.4.4 PROJECT MANAGEMENT PROCESSES,The project life cycle is managed by executing...
19,1.2 FOUNDATIONAL ELEMENTS,1.2.4 COMPONENTS OF THE GUIDE,1.2.4.5 PROJECT MANAGEMENT PROCESS GROUPS,A Project Management Process Group is a logica...
20,1.2 FOUNDATIONAL ELEMENTS,1.2.4 COMPONENTS OF THE GUIDE,1.2.4.6 PROJECT MANAGEMENT KNOWLEDGE AREAS,"In addition to Process Groups, processes are a..."
21,1.2 FOUNDATIONAL ELEMENTS,1.2.4 COMPONENTS OF THE GUIDE,1.2.4.7 PROJECT MANAGEMENT DATA AND INFORMATION,"Throughout the life cycle of a project, a sign..."
22,1.2 FOUNDATIONAL ELEMENTS,1.2.5 TAILORING,None,"Usually, project managers apply a project mana..."
23,1.2 FOUNDATIONAL ELEMENTS,1.2.6 PROJECT MANAGEMENT BUSINESS DOCUMENTS,None,The project manager needs to ensure that the p...
24,1.2 FOUNDATIONAL ELEMENTS,1.2.6 PROJECT MANAGEMENT BUSINESS DOCUMENTS,1.2.6.1 PROJECT BUSINESS CASE,The project business case is a documented econ...
25,1.2 FOUNDATIONAL ELEMENTS,1.2.6 PROJECT MANAGEMENT BUSINESS DOCUMENTS,1.2.6.2 PROJECT BENEFITS MANAGEMENT PLAN,The project benefits management plan is the do...
26,1.2 FOUNDATIONAL ELEMENTS,1.2.6 PROJECT MANAGEMENT BUSINESS DOCUMENTS,1.2.6.3 PROJECT CHARTER AND PROJECT MANAGEMENT...,The project charter is defined as a document i...
27,1.2 FOUNDATIONAL ELEMENTS,1.2.6 PROJECT MANAGEMENT BUSINESS DOCUMENTS,1.2.6.4 PROJECT SUCCESS MEASURES,One of the most common challenges in project m...

In [ ]:
# Add new Column for CHAPTER 1 and fix it ;
df_chap1_new=df_output

value_to_fill = df_chapters.iloc[0, 0]
df_chap1_new['Chapter'] = value_to_fill

new_column_name = 'Chapter'
df_chap1_new = df_chap1_new[[new_column_name] + [col for col in df_chap1_new if col != new_column_name]]
df_chap1_new

,Chapter,TitleL1,TitleL2,TitleL3,Content
0,1 INTRODUCTION,1.1 OVERVIEW AND PURPOSE OF THIS GUIDE,None,None,Project management is not new. It has been in ...
1,1 INTRODUCTION,1.1 OVERVIEW AND PURPOSE OF THIS GUIDE,1.1.1 THE STANDARD FOR PROJECT MANAGEMENT,None,This guide is based on The Standard for Projec...
2,1 INTRODUCTION,1.1 OVERVIEW AND PURPOSE OF THIS GUIDE,1.1.2 COMMON VOCABULARY,None,A common vocabulary is an essential element of...
3,1 INTRODUCTION,1.1 OVERVIEW AND PURPOSE OF THIS GUIDE,1.1.3 CODE OF ETHICS AND PROFESSIONAL CONDUCT,None,PMI publishes the Code of Ethics and Professio...
4,1 INTRODUCTION,1.2 FOUNDATIONAL ELEMENTS,None,None,This section describes foundational elements n...
5,1 INTRODUCTION,1.2 FOUNDATIONAL ELEMENTS,1.2.1 PROJECTS,None,A project is a temporary endeavor undertaken t...
6,1 INTRODUCTION,1.2 FOUNDATIONAL ELEMENTS,1.2.2 THE IMPORTANCE OF PROJECT MANAGEMENT,None,Project management is the application of knowl...
7,1 INTRODUCTION,1.2 FOUNDATIONAL ELEMENTS,"1.2.3 RELATIONSHIP OF PROJECT, PROGRAM, PORTFO...",None,None
8,1 INTRODUCTION,1.2 FOUNDATIONAL ELEMENTS,"1.2.3 RELATIONSHIP OF PROJECT, PROGRAM, PORTFO...",1.2.3.1 OVERVIEW,"Using project management processes, tools, and..."
9,1 INTRODUCTION,1.2 FOUNDATIONAL ELEMENTS,"1.2.3 RELATIONSHIP OF PROJECT, PROGRAM, PORTFO...",1.2.3.2 PROGRAM MANAGEMENT,Program management is defined as the applicati...
10,1 INTRODUCTION,1.2 FOUNDATIONAL ELEMENTS,"1.2.3 RELATIONSHIP OF PROJECT, PROGRAM, PORTFO...",1.2.3.3 PORTFOLIO MANAGEMENT,"A portfolio is defined as projects, programs, ..."
11,1 INTRODUCTION,1.2 FOUNDATIONAL ELEMENTS,"1.2.3 RELATIONSHIP OF PROJECT, PROGRAM, PORTFO...",1.2.3.4 OPERATIONS MANAGEMENT,Operations management is an area that is outsi...
12,1 INTRODUCTION,1.2 FOUNDATIONAL ELEMENTS,"1.2.3 RELATIONSHIP OF PROJECT, PROGRAM, PORTFO...",1.2.3.5 OPERATIONS AND PROJECT MANAGEMENT,Changes in business or organizational operatio...
13,1 INTRODUCTION,1.2 FOUNDATIONAL ELEMENTS,"1.2.3 RELATIONSHIP OF PROJECT, PROGRAM, PORTFO...",1.2.3.6 ORGANIZATIONAL PROJECT MANAGEMENT (OPM...,"Portfolios, programs, and projects are aligned..."
14,1 INTRODUCTION,1.2 FOUNDATIONAL ELEMENTS,1.2.4 COMPONENTS OF THE GUIDE,None,"Projects comprise several key components that,..."
15,1 INTRODUCTION,1.2 FOUNDATIONAL ELEMENTS,1.2.4 COMPONENTS OF THE GUIDE,1.2.4.1 PROJECT AND DEVELOPMENT LIFE CYCLES,A project life cycle is the series of phases t...
16,1 INTRODUCTION,1.2 FOUNDATIONAL ELEMENTS,1.2.4 COMPONENTS OF THE GUIDE,1.2.4.2 PROJECT PHASE,A project phase is a collection of logically r...
17,1 INTRODUCTION,1.2 FOUNDATIONAL ELEMENTS,1.2.4 COMPONENTS OF THE GUIDE,1.2.4.3 PHASE GATE,"A phase gate, is held at the end of a phase. T..."
18,1 INTRODUCTION,1.2 FOUNDATIONAL ELEMENTS,1.2.4 COMPONENTS OF THE GUIDE,1.2.4.4 PROJECT MANAGEMENT PROCESSES,The project life cycle is managed by executing...
19,1 INTRODUCTION,1.2 FOUNDATIONAL ELEMENTS,1.2.4 COMPONENTS OF THE GUIDE,1.2.4.5 PROJECT MANAGEMENT PROCESS GROUPS,A Project Management Process Group is a logica...
20,1 INTRODUCTION,1.2 FOUNDATIONAL ELEMENTS,1.2.4 COMPONENTS OF THE GUIDE,1.2.4.6 PROJECT MANAGEMENT KNOWLEDGE AREAS,"In addition to Process Groups, processes are a..."
21,1 INTRODUCTION,1.2 FOUNDATIONAL ELEMENTS,1.2.4 COMPONENTS OF THE GUIDE,1.2.4.7 PROJECT MANAGEMENT DATA AND INFORMATION,"Throughout the life cycle of a project, a sign..."
22,1 INTRODUCTION,1.2 FOUNDATIONAL ELEMENTS,1.2.5 TAILORING,None,"Usually, project managers apply a project mana..."
23,1 INTRODUCTION,1.2 FOUNDATIONAL ELEMENTS,1.2.6 PROJECT MANAGEMENT BUSINESS DOCUMENTS,None,The project manager needs to ensure that the p...
24,1 INTRODUCTION,1.2 FOUNDATIONAL ELEMENTS,1.2.6 PROJECT MANAGEMENT BUSINESS DOCUMENTS,1.2.6.1 PROJECT BUSINESS CASE,The project business case is a documented econ...
25,1 INTRODUCTION,1.2 FOUNDATIONAL ELEMENTS,1.2.6 PROJECT MANAGEMENT BUSINESS DOCUMENTS,1.2.6.2 PROJECT BENEFITS MANAGEMENT PLAN,The project benefits management plan is the do...
26,1 INTRODUCTION,1.2 FOUNDATIONAL ELEMENTS,1.2.6 PROJECT MANAGEMENT BUSINESS DOCUMENTS,1.2.6.3 PROJECT CHARTER AND PROJECT MANAGEMENT...,The project charter is defined as a document i...
27,1 INTRODUCTION,1.2 FOUNDATIONAL ELEMENTS,1.2.6 PROJECT MANAGEMENT BUSINESS DOCUMENTS,1.2.6.4 PROJECT SUCCESS MEASURES,One of the most common challenges in project m...

In [ ]:
#ALL THE REST OF THE CHAPTERS FROM 1 TO 13

Final_df = pd.DataFrame({'Chapter': [], 'TitleL1': [], 'TitleL2': [], 'TitleL3': [], 'Content': []})
#Final_df = pd.concat([Final_df,df_chap1_new ], ignore_index=True)

for j in range(1,14):
    df_chap=pd.DataFrame()
    df_chap=df_chapters.iloc[j-1:j]
    content_chap=pd.DataFrame()
    content_chap = df_chap["Content"].str.split('\n')

    titles_level1=[] #a.x
    titles_level2=[] #a.x.x
    titles_level3=[] #a.x.x.x
    t_list=[] #list that contains a.x.x.x parts of all Levels
    Contents=[]
    i=0
    content=""
    t1=None
    t2=None
    t3=None

    for line_list in content_chap:
        for i,line in enumerate(line_list):
            pattern = r'^' + str(j) + r'\.\d+(\.\d+)*\s+'
            match = re.search(pattern, line)
            if line and match and not match.group(0)[:-1] in t_list and "—" not in line:
                #print(t_list)
                previous_line = line_list[i -1]
                level=len(match.group(0).split('.'))-1
                #print(level)

                if len(t_list)==0 and len(Contents)==0 and content:
                    #print(t_list)
                    titles_level1.append(None)
                    titles_level2.append(None)
                    titles_level3.append(None)
                    t1=None
                    t2=None
                    t3=None
                if level==1:
                    #print("LEVEL 1")
                    titles_level1.append(line)
                    titles_level2.append(None)
                    titles_level3.append(None)
                    t1=line
                    t2=None
                    t3=None
                    t1_parts=t1.split(" ")
                    t_list.append(t1_parts[0])
                if level==2:
                    titles_level1.append(t1)
                    titles_level2.append(line)
                    titles_level3.append(None)
                    t2=line
                    t3=None
                    t2_parts=t2.split(" ")
                    t_list.append(t2_parts[0])
                if level==3:
                    titles_level1.append(t1)
                    titles_level2.append(t2)
                    titles_level3.append(line)
                    t3=line
                    t3_parts=t3.split(" ")
                    t_list.append(t3_parts[0])
                match2 = re.search(pattern, previous_line)
                if match2:
                    Contents.append(None)
                # If there is content, append it
                if content :
                    Contents.append(content.strip())
                    content = ""
            else:
            # Append content lines
                content += '\n' + line
    # Append any remaining content
        if content:
            Contents.append(content.strip())
        # Make sure all lists have the same length by filling any missing data with placeholders
        max_length = max(len(titles_level1), len(titles_level2), len(titles_level3), len(Contents))
        titles_level1.extend([""] * (max_length - len(titles_level1)))
        titles_level2.extend([""] * (max_length - len(titles_level2)))
        titles_level3.extend([""] * (max_length - len(titles_level3)))
        Contents.extend([""] * (max_length - len(Contents)))

        df_output = pd.DataFrame({
        'TitleL1': titles_level1,
        'TitleL2': titles_level2,
        'TitleL3': titles_level3,
        'Content': Contents,
        })

    df_chap_new=pd.DataFrame()
    df_chap_new=df_output

    value_to_fill = df_chapters.iloc[j-1, 0]
    df_chap_new['Chapter'] = value_to_fill

    new_column_name = 'Chapter'
    df_chap_new = df_chap_new[[new_column_name] + [col for col in df_chap_new if col != new_column_name]]
    Final_df = pd.concat([Final_df,df_chap_new ], ignore_index=True)
Final_df

,Chapter,TitleL1,TitleL2,TitleL3,Content
0,1 INTRODUCTION,1.1 OVERVIEW AND PURPOSE OF THIS GUIDE,None,None,Project management is not new. It has been in ...
1,1 INTRODUCTION,1.1 OVERVIEW AND PURPOSE OF THIS GUIDE,1.1.1 THE STANDARD FOR PROJECT MANAGEMENT,None,This guide is based on The Standard for Projec...
2,1 INTRODUCTION,1.1 OVERVIEW AND PURPOSE OF THIS GUIDE,1.1.2 COMMON VOCABULARY,None,A common vocabulary is an essential element of...
3,1 INTRODUCTION,1.1 OVERVIEW AND PURPOSE OF THIS GUIDE,1.1.3 CODE OF ETHICS AND PROFESSIONAL CONDUCT,None,PMI publishes the Code of Ethics and Professio...
4,1 INTRODUCTION,1.2 FOUNDATIONAL ELEMENTS,None,None,This section describes foundational elements n...
...,...,...,...,...,...
935,13 PROJECT STAKEHOLDER MANAGEMENT,13.4 MONITOR STAKEHOLDER ENGAGEMENT,13.4.3 MONITOR STAKEHOLDER ENGAGEMENT: OUTPUTS,None,None
936,13 PROJECT STAKEHOLDER MANAGEMENT,13.4 MONITOR STAKEHOLDER ENGAGEMENT,13.4.3 MONITOR STAKEHOLDER ENGAGEMENT: OUTPUTS,13.4.3.1 WORK PERFORMANCE INFORMATION,Described in Section 4.5.1.3. Work performance...
937,13 PROJECT STAKEHOLDER MANAGEMENT,13.4 MONITOR STAKEHOLDER ENGAGEMENT,13.4.3 MONITOR STAKEHOLDER ENGAGEMENT: OUTPUTS,13.4.3.2 CHANGE REQUESTS,Described in Section 4.3.3.4. A change request...
938,13 PROJECT STAKEHOLDER MANAGEMENT,13.4 MONITOR STAKEHOLDER ENGAGEMENT,13.4.3 MONITOR STAKEHOLDER ENGAGEMENT: OUTPUTS,13.4.3.3 PROJECT MANAGEMENT PLAN UPDATES,Any change to the project management plan goes...
939,13 PROJECT STAKEHOLDER MANAGEMENT,13.4 MONITOR STAKEHOLDER ENGAGEMENT,13.4.3 MONITOR STAKEHOLDER ENGAGEMENT: OUTPUTS,13.4.3.4 PROJECT DOCUMENTS UPDATES,Project documents that may be updated as a res...

In [ ]:
Final_df.to_csv("DF_CHAPTERs_SUBTITLEsLv3_CONTENTs_NOT_CLEAN.csv", index=False)

In [ ]:
filtered_df = Final_df[Final_df['Chapter'] == '11 PROJECT RISK MANAGEMENT']

In [ ]:
filtered_df

,Chapter,TitleL1,TitleL2,TitleL3,Content
685,11 PROJECT RISK MANAGEMENT,None,None,None,Project Risk Management includes the processes...
686,11 PROJECT RISK MANAGEMENT,11.1 PLAN RISK MANAGEMENT,None,None,Plan Risk Management is the process of definin...
687,11 PROJECT RISK MANAGEMENT,11.1 PLAN RISK MANAGEMENT,11.1.1 PLAN RISK MANAGEMENT: INPUTS,None,None
688,11 PROJECT RISK MANAGEMENT,11.1 PLAN RISK MANAGEMENT,11.1.1 PLAN RISK MANAGEMENT: INPUTS,11.1.1.1 PROJECT CHARTER,Described in Section 4.1.3.1. The project char...
689,11 PROJECT RISK MANAGEMENT,11.1 PLAN RISK MANAGEMENT,11.1.1 PLAN RISK MANAGEMENT: INPUTS,11.1.1.2 PROJECT MANAGEMENT PLAN,Described in Section 4.2.3.1. In planning Proj...
...,...,...,...,...,...
791,11 PROJECT RISK MANAGEMENT,11.7 MONITOR RISKS,11.7.3 MONITOR RISKS: OUTPUTS,11.7.3.1 WORK PERFORMANCE INFORMATION,Described in Section 4.5.1.3. Work performance...
792,11 PROJECT RISK MANAGEMENT,11.7 MONITOR RISKS,11.7.3 MONITOR RISKS: OUTPUTS,11.7.3.2 CHANGE REQUESTS,Described in Section 4.3.3.4. The Monitor Risk...
793,11 PROJECT RISK MANAGEMENT,11.7 MONITOR RISKS,11.7.3 MONITOR RISKS: OUTPUTS,11.7.3.3 PROJECT MANAGEMENT PLAN UPDATES,Any change to the project management plan goes...
794,11 PROJECT RISK MANAGEMENT,11.7 MONITOR RISKS,11.7.3 MONITOR RISKS: OUTPUTS,11.7.3.4 PROJECT DOCUMENTS UPDATES,Project documents that may be updated as a res...
795,11 PROJECT RISK MANAGEMENT,11.7 MONITOR RISKS,11.7.3 MONITOR RISKS: OUTPUTS,11.7.3.5 ORGANIZATIONAL PROCESS ASSETS UPDATES,Organizational process assets that are updated...

In [ ]:
import pandas as pd
df2 = pd.DataFrame(columns=['Concept', 'Description'])

In [ ]:
for i in range(685,685+len(filtered_df)):
  if(filtered_df['TitleL3'][i]!=None):
    concept=filtered_df['TitleL3'][i]
  else:
    if(filtered_df['TitleL2'][i]!=None):
      concept=filtered_df['TitleL2'][i]
    else:
      if(filtered_df['TitleL1'][i]!=None):
        concept=filtered_df['TitleL1'][i]
      else:
          concept=filtered_df['Chapter'][i]
  print(concept)
  new_row = {'Concept': concept, 'Description': filtered_df['Content'][i]}
  df2 = df2.append(new_row, ignore_index=True)

11 PROJECT RISK MANAGEMENT
11.1 PLAN RISK MANAGEMENT
11.1.1 PLAN RISK MANAGEMENT: INPUTS
11.1.1.1 PROJECT CHARTER
11.1.1.2 PROJECT MANAGEMENT PLAN
11.1.1.3 PROJECT DOCUMENTS
11.1.1.4 ENTERPRISE ENVIRONMENTAL FACTORS
11.1.1.5 ORGANIZATIONAL PROCESS ASSETS
11.1.2 PLAN RISK MANAGEMENT: TOOLS AND TECHNIQUES
11.1.2.1 EXPERT JUDGMENT
11.1.2.2 DATA ANALYSIS
11.1.2.3 MEETINGS
11.1.3 PLAN RISK MANAGEMENT: OUTPUTS
11.1.3.1 RISK MANAGEMENT PLAN
11.2 IDENTIFY RISKS
11.2.1 IDENTIFY RISKS: INPUTS
11.2.1.1 PROJECT MANAGEMENT PLAN
11.2.1.2 PROJECT DOCUMENTS
11.2.1.3 AGREEMENTS
11.2.1.4 PROCUREMENT DOCUMENTATION
11.2.1.5 ENTERPRISE ENVIRONMENTAL FACTORS
11.2.1.6 ORGANIZATIONAL PROCESS ASSETS
11.2.2 IDENTIFY RISKS: TOOLS AND TECHNIQUES
11.2.2.1 EXPERT JUDGMENT
11.2.2.2 DATA GATHERING
11.2.2.3 DATA ANALYSIS
11.2.2.4 INTERPERSONAL AND TEAM SKILLS
11.2.2.5 PROMPT LISTS
11.2.2.6 MEETINGS
11.2.3 IDENTIFY RISKS: OUTPUTS
11.2.3.1 RISK REGISTER
11.2.3.2 RISK REPORT
11.2.3.3 PROJECT DOCUMENTS UPDATES
11.3 PERFORM QUALITATIVE RISK ANALYSIS
11.3.1 PERFORM QUALITATIVE RISK ANALYSIS: INPUTS
11.3.1.1 PROJECT MANAGEMENT PLAN
11.3.1.2 PROJECT DOCUMENTS
11.3.1.3 ENTERPRISE ENVIRONMENTAL FACTORS
11.3.1.4 ORGANIZATIONAL PROCESS ASSETS
11.3.2 PERFORM QUALITATIVE RISK ANALYSIS: TOOLS AND TECHNIQUES
11.3.2.1 EXPERT JUDGMENT
11.3.2.2 DATA GATHERING
11.3.2.3 DATA ANALYSIS
11.3.2.4 INTERPERSONAL AND TEAM SKILLS
11.3.2.5 RISK CATEGORIZATION
11.3.2.6 DATA REPRESENTATION
11.3.2.7 MEETINGS
11.3.3 PERFORM QUALITATIVE RISK ANALYSIS: OUTPUTS
11.3.3.1 PROJECT DOCUMENTS UPDATES
11.4 PERFORM QUANTITATIVE RISK ANALYSIS
11.4.1 PERFORM QUANTITATIVE RISK ANALYSIS: INPUTS
11.4.1.1 PROJECT MANAGEMENT PLAN
11.4.1.2 PROJECT DOCUMENTS
11.4.1.3 ENTERPRISE ENVIRONMENTAL FACTORS
11.4.1.4 ORGANIZATIONAL PROCESS ASSETS
11.4.2 PERFORM QUANTITATIVE RISK ANALYSIS: TOOLS AND TECHNIQUES
11.4.2.1 EXPERT JUDGMENT
11.4.2.2 DATA GATHERING
11.4.2.3 INTERPERSONAL AND TEAM SKILLS
11.4.2.4 REPRESENTATIONS OF UNCERTAINTY
11.4.2.5 DATA ANALYSIS
11.4.3 PERFORM QUANTITATIVE RISK ANALYSIS: OUTPUTS
11.4.3.1 PROJECT DOCUMENTS UPDATES
11.5 PLAN RISK RESPONSES
11.5.1 PLAN RISK RESPONSES: INPUTS
11.5.1.1 PROJECT MANAGEMENT PLAN
11.5.1.2 PROJECT DOCUMENTS
11.5.1.3 ENTERPRISE ENVIRONMENTAL FACTORS
11.5.1.4 ORGANIZATIONAL PROCESS ASSETS
11.5.2 PLAN RISK RESPONSES: TOOLS AND TECHNIQUES
11.5.2.1 EXPERT JUDGMENT
11.5.2.2 DATA GATHERING
11.5.2.3 INTERPERSONAL AND TEAM SKILLS
11.5.2.4 STRATEGIES FOR THREATS
11.5.2.5 STRATEGIES FOR OPPORTUNITIES
11.5.2.6 CONTINGENT RESPONSE STRATEGIES
11.5.2.7 STRATEGIES FOR OVERALL PROJECT RISK
11.5.2.8 DATA ANALYSIS
11.5.2.9 DECISION MAKING
11.5.3 PLAN RISK RESPONSES: OUTPUTS
11.5.3.1 CHANGE REQUESTS
11.5.3.2 PROJECT MANAGEMENT PLAN UPDATES
11.5.3.3 PROJECT DOCUMENTS UPDATES
11.6 IMPLEMENT RISK RESPONSES
11.6.1 IMPLEMENT RISK RESPONSES: INPUTS
11.6.1.1 PROJECT MANAGEMENT PLAN
11.6.1.2 PROJECT DOCUMENTS
11.6.1.3 ORGANIZATIONAL PROCESS ASSETS
11.6.2 IMPLEMENT RISK RESPONSES: TOOLS AND TECHNIQUES
11.6.2.1 EXPERT JUDGMENT
11.6.2.2 INTERPERSONAL AND TEAM SKILLS
11.6.2.3 PROJECT MANAGEMENT INFORMATION SYSTEM (PMIS)
11.6.3 IMPLEMENT RISK RESPONSES: OUTPUTS
11.6.3.1 CHANGE REQUESTS
11.6.3.2 PROJECT DOCUMENTS UPDATES
11.7 MONITOR RISKS
11.7.1 MONITOR RISKS: INPUTS
11.7.1.1 PROJECT MANAGEMENT PLAN
11.7.1.2 PROJECT DOCUMENTS
11.7.1.3 WORK PERFORMANCE DATA
11.7.1.4 WORK PERFORMANCE REPORTS
11.7.2 MONITOR RISKS: TOOLS AND TECHNIQUES
11.7.2.1 DATA ANALYSIS
11.7.2.2 AUDITS
11.7.2.3 MEETINGS
11.7.3 MONITOR RISKS: OUTPUTS
11.7.3.1 WORK PERFORMANCE INFORMATION
11.7.3.2 CHANGE REQUESTS
11.7.3.3 PROJECT MANAGEMENT PLAN UPDATES
11.7.3.4 PROJECT DOCUMENTS UPDATES
11.7.3.5 ORGANIZATIONAL PROCESS ASSETS UPDATES

In [ ]:
filtered_df['TitleL2'][685]

In [ ]:
df2

,Concept,Description
0,11 PROJECT RISK MANAGEMENT,Project Risk Management includes the processes...
1,11.1 PLAN RISK MANAGEMENT,Plan Risk Management is the process of definin...
2,11.1.1 PLAN RISK MANAGEMENT: INPUTS,None
3,11.1.1.1 PROJECT CHARTER,Described in Section 4.1.3.1. The project char...
4,11.1.1.2 PROJECT MANAGEMENT PLAN,Described in Section 4.2.3.1. In planning Proj...
...,...,...
106,11.7.3.1 WORK PERFORMANCE INFORMATION,Described in Section 4.5.1.3. Work performance...
107,11.7.3.2 CHANGE REQUESTS,Described in Section 4.3.3.4. The Monitor Risk...
108,11.7.3.3 PROJECT MANAGEMENT PLAN UPDATES,Any change to the project management plan goes...
109,11.7.3.4 PROJECT DOCUMENTS UPDATES,Project documents that may be updated as a res...
110,11.7.3.5 ORGANIZATIONAL PROCESS ASSETS UPDATES,Organizational process assets that are updated...

In [ ]:
df2.to_csv("pmbook_shih.csv", index=False)

In [ ]:
for i in range(685,685+len(filtered_df)):
  print(filtered_df["Content"][i])

Project Risk Management includes the processes of conducting risk management planning, identification, analysis,
response planning, response implementation, and monitoring risk on a project. The objectives of project risk management
are to increase the probability and/or impact of positive risks and to decrease the probability and/or impact of negative
risks, in order to optimize the chances of project success.
The Project Risk Management processes are:
11.1 Plan Risk Management—The process of defining how to conduct risk management activities for a project.
11.2 Identify Risks—The process of identifying individual project risks as well as sources of overall project risk,
and documenting their characteristics.
11.3 Perform Qualitative Risk Analysis—The process of prioritizing individual project risks for further analysis
or action by assessing their probability of occurrence and impact as well as other characteristics.
11.4 Perform Quantitative Risk Analysis—The process of numerically analyzing the combined effect of identified
individual project risks and other sources of uncertainty on overall project objectives.
11.5 Plan Risk Responses—The process of developing options, selecting strategies, and agreeing on actions to
address overall project risk exposure, as well as to treat individual project risks.
11.6 Implement Risk Responses—The process of implementing agreed-upon risk response plans.
11.7 Monitor Risks—The process of monitoring the implementation of agreed-upon risk response plans,
tracking identified risks, identifying and analyzing new risks, and evaluating risk process effectiveness throughout the
project.
Figure 11-1 provides an overview of the Project Risk Management processes. The Project Management Risk processes
are presented as discrete processes with defined interfaces while, in practice, they overlap and interact in ways that
cannot be completely detailed in this PMBOK® Guide.
NubPage 365
KEY CONCEPTS FOR PROJECT RISK MANAGEMENT
All projects are risky since they are unique undertakings with varying degrees of complexity that aim to deliver
benefits. They do this in a context of constraints and assumptions, while responding to stakeholder expectations that
may be conflicting and changing. Organizations should choose to take project risk in a controlled and intentional manner
in order to create value while balancing risk and reward.
Project Risk Management aims to identify and manage risks that are not addressed by the other project management
processes. When unmanaged, these risks have the potential to cause the project to deviate from the plan and fail to
achieve the defined project objectives. Consequently, the effectiveness of Project Risk Management is directly related to
project success.
Risk exists at two levels within every project. Each project contains individual risks that can affect the achievement of
project objectives. It is also important to consider the riskiness of the overall project, which arises from the combination
of individual project risks and other sources of uncertainty. Project Risk Management processes address both levels of risk
in projects, and these are defined as follows:
◆ Individual project risk is an uncertain event or condition that, if it occurs, has a positive or negative effect on one
or more project objectives.
◆ Overall project risk is the effect of uncertainty on the project as a whole, arising from all sources of uncertainty
including individual risks, representing the exposure of stakeholders to the implications of variations in project
outcome, both positive and negative.
Individual project risks can have a positive or negative effect on project objectives if they occur. Project Risk
Management aims to exploit or enhance positive risks (opportunities) while avoiding or mitigating negative risks
(threats). Unmanaged threats may result in issues or problems such as delay, cost overruns, performance shortfall,
or loss of reputation. Opportunities that are captured can lead to benefits such as reduced time and cost, improved
performance, or reputation.
Overall project risk can also be positive or negative. Management of overall project risk aims to keep project risk
exposure within an acceptable range by reducing drivers of negative variation, promoting drivers of positive variation, and
maximizing the probability of achieving overall project objectives.
NubPage 366
Risks will continue to emerge during the lifetime of the project, so Project Risk Management processes should be conducted
iteratively. Risk is initially addressed during project planning by shaping the project strategy. Risk should also be monitored and
managed as the project progresses to ensure that the project stays on track and emergent risks are addressed.
In order to manage risk effectively on a particular project, the project team needs to know what level of risk exposure
is acceptable in pursuit of the project objectives. This is defined by measurable risk thresholds that reflect the risk appetite
of the organization and project stakeholders. Risk thresholds express the degree of acceptable variation around a project
objective. They are explicitly stated and communicated to the project team and reflected in the definitions of risk impact
levels for the project.
TRENDS AND EMERGING PRACTICES IN PROJECT RISK MANAGEMENT
The focus of project risk management is broadening to ensure that all types of risk are considered, and that project
risks are understood in a wider context. Trends and emerging practices for Project Risk Management include but are
not limited to:
◆ Non-event risks. Most projects focus only on risks that are uncertain future events that may or may not occur.
Examples of event-based risks include: a key seller may go out of business during the project, the customer may
change the requirement after design is complete, or a subcontractor may propose enhancements to the standard
operating processes.
There is an increasing recognition that non-event risks need to be identified and managed. There are two main
types of non-event risks:
◼ Variability risk. Uncertainty exists about some key characteristics of a planned event or activity or decision.
Examples of variability risks include: productivity may be above or below target, the number of errors found
during testing may be higher or lower than expected, or unseasonal weather conditions may occur during the
construction phase.
◼ Ambiguity risk. Uncertainty exists about what might happen in the future. Areas of the project where
imperfect knowledge might affect the project’s ability to achieve its objectives include: elements of the
requirement or technical solution, future developments in regulatory frameworks, or inherent systemic
complexity in the project.
NubPage 367
Variability risks can be addressed using Monte Carlo analysis, with the range of variation reflected in probability
distributions, followed by actions to reduce the spread of possible outcomes. Ambiguity risks are managed by
defining those areas where there is a deficit of knowledge or understanding, then filling the gap by obtaining expert
external input or benchmarking against best practices. Ambiguity is also addressed through incremental
development, prototyping, or simulation.
◆ Project resilience. The existence of emergent risk is becoming clear, with a growing awareness of so-called
unknowable-unknowns. These are risks that can only be recognized after they have occurred. Emergent risks
can be tackled through developing project resilience. This requires each project to have:
◼ Right level of budget and schedule contingency for emergent risks, in addition to a specific risk budget for
known risks;
◼ Flexible project processes that can cope with emergent risk while maintaining overall direction toward project
goals, including strong change management;
◼ Empowered project team that has clear objectives and that is trusted to get the job done within agreed-
upon limits;
◼ Frequent review of early warning signs to identify emergent risks as early as possible; and
◼ Clear input from stakeholders to clarify areas where the project scope or strategy can be adjusted in response
to emergent risks.
◆ Integrated risk management. Projects exist in an organizational context, and they may form part of a program
or portfolio. Risk exists at each of these levels, and risks should be owned and managed at the appropriate level.
Some risks identified at higher levels will be delegated to the project team for management, and some project
risks may be escalated to higher levels if they are best managed outside the project. A coordinated approach to
enterprise-wide risk management ensures alignment and coherence in the way risk is managed across all levels.
This builds risk efficiency into the structure of programs and portfolios, providing the greatest overall value for a
given level of risk exposure.
NubPage 368
TAILORING CONSIDERATIONS
Because each project is unique, it is necessary to tailor the way Project Risk Management processes are applied.
Considerations for tailoring include but are not limited to:
◆ Project size. Does the project’s size in terms of budget, duration, scope, or team size require a more detailed
approach to risk management? Or is it small enough to justify a simplified risk process?
◆ Project complexity. Is a robust risk approach demanded by high levels of innovation, new technology, commercial
arrangements, interfaces, or external dependencies that increase project complexity? Or is the project simple
enough that a reduced risk process will suffice?
◆ Project importance. How strategically important is the project? Is the level of risk increased for this project
because it aims to produce breakthrough opportunities, addresses significant blocks to organizational
performance, or involves major product innovation?
◆ Development approach. Is this a waterfall project, where risk processes can be followed sequentially and
iteratively, or does the project follow an agile approach where risk is addressed at the start of each iteration as
well as during its execution?
Tailoring of the Project Risk Management processes to meet these considerations is part of the Plan Risk Management
process, and the outcomes of tailoring decisions are recorded in the risk management plan.
CONSIDERATIONS FOR AGILE/ADAPTIVE ENVIRONMENTS
High-variability environments, by definition, incur more uncertainty and risk. To address this, projects managed using
adaptive approaches make use of frequent reviews of incremental work products and cross-functional project teams to
accelerate knowledge sharing and ensure that risk is understood and managed. Risk is considered when selecting the
content of each iteration, and risks will also be identified, analyzed, and managed during each iteration.
Additionally, the requirements are kept as a living document that is updated regularly, and work may be reprioritized
as the project progresses, based on an improved understanding of current risk exposure.
Plan Risk Management is the process of defining how to conduct risk management activities for a project. The key
benefit of this process is that it ensures that the degree, type, and visibility of risk management are proportionate to both
risks and the importance of the project to the organization and other stakeholders. This process is performed once or
at predefined points in the project. The inputs, tools and techniques, and outputs of the process are depicted in Figure
11-2. Figure 11-3 depicts the data flow diagram for the process.
NubPage 369
The Plan Risk Management process should begin when a project is conceived and should be completed early in the
project. It may be necessary to revisit this process later in the project life cycle, for example at a major phase change, or
if the project scope changes significantly, or if a subsequent review of risk management effectiveness determines that the
Project Risk Management process requires modification.
None
Described in Section 4.1.3.1. The project charter documents the high-level project description and boundaries, high-
level requirements, and risks.
NubPage 370
Described in Section 4.2.3.1. In planning Project Risk Management, all approved subsidiary management plans
should be taken into consideration in order to make the risk management plan consistent with them. The methodology
outlined in other project management plan components might influence the Plan Risk Management process.
Project documents that can be considered as inputs for this process include but are not limited to the stakeholder
register as described in Section 13.1.3.1. The stakeholder register contains details of the project’s stakeholders and
provides an overview of their project roles and their attitude toward risk on this project. This is useful in determining
roles and responsibilities for managing risk on the project, as well as setting risk thresholds for the project.
The enterprise environmental factors that can influence the Plan Risk Management process include but are not
limited to overall risk thresholds set by the organization or key stakeholders.
The organizational process assets that can influence the Plan Risk Management process include but are not
limited to:
◆ Organizational risk policy;
◆ Risk categories, possibly organized into a risk breakdown structure;
◆ Common definitions of risk concepts and terms;
◆ Risk statement formats;
◆ Templates for the risk management plan, risk register, and risk report;
◆ Roles and responsibilities;
◆ Authority levels for decision making; and
◆ Lessons learned repository from previous similar projects.
NubPage 371
None
Described in Section 4.1.2.1. Expertise should be considered from individuals or groups with specialized knowledge
or training in the following topics:
◆ Familiarity with the organization’s approach to managing risk, including enterprise risk management where this
is performed;
◆ Tailoring risk management to the specific needs of a project; and
◆ Types of risk that are likely to be encountered on projects in the same area.
Data analysis techniques that can be used for this process includes but are not limited to a stakeholder analysis
(Section 13.1.2.3) to determine the risk appetite of project stakeholders.
The risk management plan may be developed as part of the project kick-off meeting or a specific planning meeting may
be held. Attendees may include the project manager, selected project team members, key stakeholders, or team members
who are responsible to manage the risk management process on the project. Others outside the organization may also be
invited, as needed, including customers, sellers, and regulators. A skilled facilitator can help participants remain focused
on the task, agree on key aspects of the risk approach, identify and overcome sources of bias, and resolve any
disagreements that may arise.
Plans for conducting risk management activities are defined in these meetings and documented in the risk
management plan (see Section 11.1.3.1).
NubPage 372
None
The risk management plan is a component of the project management plan that describes how risk management
activities will be structured and performed. The risk management plan may include some or all of the following elements:
◆ Risk strategy. Describes the general approach to managing risk on this project.
◆ Methodology. Defines the specific approaches, tools, and data sources that will be used to perform risk
management on the project.
◆ Roles and responsibilities. Defines the lead, support, and risk management team members for each type of
activity described in the risk management plan, and clarifies their responsibilities.
◆ Funding. Identifies the funds needed to perform activities related to Project Risk Management. Establishes
protocols for the application of contingency and management reserves.
◆ Timing. Defines when and how often the Project Risk Management processes will be performed throughout the
project life cycle, and establishes risk management activities for inclusion into the project schedule.
◆ Risk categories. Provide a means for grouping individual project risks. A common way to structure risk categories
is with a risk breakdown structure (RBS), which is a hierarchical representation of potential sources of risk (see
example in Figure 11-4). An RBS helps the project team consider the full range of sources from which individual
project risks may arise. This can be useful when identifying risks or when categorizing identified risks. The
organization may have a generic RBS to be used for all projects, or there may be several RBS frameworks for
different types of projects, or the project may develop a tailored RBS. Where an RBS is not used, an organization
may use a custom risk categorization framework, which may take the form of a simple list of categories or a
structure based on project objectives.
NubPage 373
NubPage 374
◆ Stakeholder risk appetite. The risk appetites of key stakeholders on the project are recorded in the risk
management plan, as they inform the details of the Plan Risk Management process. In particular, stakeholder risk
appetite should be expressed as measurable risk thresholds around each project objective. These thresholds will
determine the acceptable level of overall project risk exposure, and they are also used to inform the definitions of
probability and impacts to be used when assessing and prioritizing individual project risks.
◆ Definitions of risk probability and impacts. Definitions of risk probability and impact levels are specific to the
project context and reflect the risk appetite and thresholds of the organization and key stakeholders. The project
may generate specific definitions of probability and impact levels or it may start with general definitions provided
by the organization. The number of levels reflects the degree of detail required for the Project Risk Management
process, with more levels used for a more detailed risk approach (typically five levels), and fewer for a simple
process (usually three). Table 11-1 provides an example of definitions of probability and impacts against three
project objectives. These scales can be used to evaluate both threats and opportunities by interpreting the impact
definitions as negative for threats (delay, additional cost, and performance shortfall) and positive for opportunities
(reduced time or cost, and performance enhancement).
NubPage 375
◆ Probability and impact matrix. Described in Section 11.3.2.6. Prioritization rules may be specified by the
organization in advance of the project and be included in organizational process assets, or they may be tailored to
the specific project. Opportunities and threats are represented in a common probability and impact matrix using
positive definitions of impact for opportunities and negative impact definitions for threats. Descriptive terms (such
as very high, high, medium, low, and very low) or numeric values can be used for probability and impact. Where
numeric values are used, these can be multiplied to give a probability-impact score for each risk, which allows the
relative priority of individual risks to be evaluated within each priority level. An example probability and impact
matrix is presented in Figure 11-5, which also shows a possible numeric risk scoring scheme.
◆ Reporting formats. Reporting formats define how the outcomes of the Project Risk Management process will
be documented, analyzed, and communicated. This section of the risk management plan describes the content and
format of the risk register and the risk report, as well as any other required outputs from the Project Risk
Management processes.
◆ Tracking. Tracking documents how risk activities will be recorded and how risk management processes will
be audited.
Identify Risks is the process of identifying individual project risks as well as sources of overall project risk, and

In [ ]:
import nltk
nltk.download('all')


import pandas as pd
from keybert import KeyBERT
import nltk
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer

# Télécharger les ressources NLTK (si ce n'est pas déjà fait)
nltk.download('punkt')

# Créer un objet KeyBERT avec un modèle BERT pré-entraîné
model = KeyBERT('distilbert-base-nli-mean-tokens')

# Initialiser le lemmatiseur WordNet
lemmatizer = WordNetLemmatizer()

# Fonction pour extraire des mots-clés à partir de la description
def extract_keywords(description_text):
    if not isinstance(description_text, str) or not description_text.strip():
        return []  # Retourne une liste vide pour les entrées non-chaînes ou vides

    print(f"Texte d'origine : {description_text}")

    # Extraire les mots-clés à partir de la description en utilisant KeyBERT
    keywords = model.extract_keywords(description_text, keyphrase_ngram_range=(2, 3), stop_words='english')
    extracted_keywords = [keyword[0] for keyword in keywords]

    # Lemmatisation et fusion des mots-clés
    lemmatized_keywords = []
    unique_keywords = set()
    for keyword in extracted_keywords:
        words = word_tokenize(keyword)  # Tokenize the keyword
        lemmatized_words = [lemmatizer.lemmatize(word) for word in words]
        merged_keyword = " ".join(lemmatized_words)
        # Check for duplicates and keep only unique keywords
        if "updating risk" in merged_keyword:
            merged_keyword = merged_keyword.replace("updating risk", "risk updating")
        if merged_keyword not in unique_keywords:
            lemmatized_keywords.append(merged_keyword)
            unique_keywords.add(merged_keyword)
    print(f"Mots-clés lemmatisés et fusionnés : {lemmatized_keywords}")

    return lemmatized_keywords

# Appliquer la fonction extract_keywords à la colonne 'Description' de votre DataFrame
df2['Keywords'] = df2['Description'].apply(extract_keywords)

# Afficher le DataFrame mis à jour avec les mots-clés extraits, lemmatisés et fusionnés
df2

[nltk_data] Downloading collection 'all'
[nltk_data]    |
[nltk_data]    | Downloading package abc to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/abc.zip.
[nltk_data]    | Downloading package alpino to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/alpino.zip.
[nltk_data]    | Downloading package averaged_perceptron_tagger to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping taggers/averaged_perceptron_tagger.zip.
[nltk_data]    | Downloading package averaged_perceptron_tagger_ru to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping
[nltk_data]    |       taggers/averaged_perceptron_tagger_ru.zip.
[nltk_data]    | Downloading package basque_grammars to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping grammars/basque_grammars.zip.
[nltk_data]    | Downloading package bcp47 to /root/nltk_data...
[nltk_data]    | Downloading package biocreative_ppi to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/biocreative_ppi.zip.
[nltk_data]    | Downloading package bllip_wsj_no_aux to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping models/bllip_wsj_no_aux.zip.
[nltk_data]    | Downloading package book_grammars to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping grammars/book_grammars.zip.
[nltk_data]    | Downloading package brown to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/brown.zip.
[nltk_data]    | Downloading package brown_tei to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/brown_tei.zip.
[nltk_data]    | Downloading package cess_cat to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/cess_cat.zip.
[nltk_data]    | Downloading package cess_esp to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/cess_esp.zip.
[nltk_data]    | Downloading package chat80 to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/chat80.zip.
[nltk_data]    | Downloading package city_database to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/city_database.zip.
[nltk_data]    | Downloading package cmudict to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/cmudict.zip.
[nltk_data]    | Downloading package comparative_sentences to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/comparative_sentences.zip.
[nltk_data]    | Downloading package comtrans to /root/nltk_data...
[nltk_data]    | Downloading package conll2000 to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/conll2000.zip.
[nltk_data]    | Downloading package conll2002 to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/conll2002.zip.
[nltk_data]    | Downloading package conll2007 to /root/nltk_data...
[nltk_data]    | Downloading package crubadan to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/crubadan.zip.
[nltk_data]    | Downloading package dependency_treebank to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/dependency_treebank.zip.
[nltk_data]    | Downloading package dolch to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/dolch.zip.
[nltk_data]    | Downloading package europarl_raw to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/europarl_raw.zip.
[nltk_data]    | Downloading package extended_omw to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    | Downloading package floresta to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/floresta.zip.
[nltk_data]    | Downloading package framenet_v15 to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/framenet_v15.zip.
[nltk_data]    | Downloading package framenet_v17 to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/framenet_v17.zip.
[nltk_data]    | Downloading package gazetteers to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/gazetteers.zip.
[nltk_data]    | Downloading package genesis to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/genesis.zip.
[nltk_data]    | Downloading package gutenberg to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/gutenberg.zip.
[nltk_data]    | Downloading package ieer to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/ieer.zip.
[nltk_data]    | Downloading package inaugural to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/inaugural.zip.
[nltk_data]    | Downloading package indian to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/indian.zip.
[nltk_data]    | Downloading package jeita to /root/nltk_data...
[nltk_data]    | Downloading package kimmo to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/kimmo.zip.
[nltk_data]    | Downloading package knbc to /root/nltk_data...
[nltk_data]    | Downloading package large_grammars to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping grammars/large_grammars.zip.
[nltk_data]    | Downloading package lin_thesaurus to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/lin_thesaurus.zip.
[nltk_data]    | Downloading package mac_morpho to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/mac_morpho.zip.
[nltk_data]    | Downloading package machado to /root/nltk_data...
[nltk_data]    | Downloading package masc_tagged to /root/nltk_data...
[nltk_data]    | Downloading package maxent_ne_chunker to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping chunkers/maxent_ne_chunker.zip.
[nltk_data]    | Downloading package maxent_treebank_pos_tagger to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping taggers/maxent_treebank_pos_tagger.zip.
[nltk_data]    | Downloading package moses_sample to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping models/moses_sample.zip.
[nltk_data]    | Downloading package movie_reviews to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/movie_reviews.zip.
[nltk_data]    | Downloading package mte_teip5 to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/mte_teip5.zip.
[nltk_data]    | Downloading package mwa_ppdb to /root/nltk_data...
[nltk_data]    |   Unzipping misc/mwa_ppdb.zip.
[nltk_data]    | Downloading package names to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/names.zip.
[nltk_data]    | Downloading package nombank.1.0 to /root/nltk_data...
[nltk_data]    | Downloading package nonbreaking_prefixes to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/nonbreaking_prefixes.zip.
[nltk_data]    | Downloading package nps_chat to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/nps_chat.zip.
[nltk_data]    | Downloading package omw to /root/nltk_data...
[nltk_data]    | Downloading package omw-1.4 to /root/nltk_data...
[nltk_data]    |   Package omw-1.4 is already up-to-date!
[nltk_data]    | Downloading package opinion_lexicon to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/opinion_lexicon.zip.
[nltk_data]    | Downloading package panlex_swadesh to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    | Downloading package paradigms to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/paradigms.zip.
[nltk_data]    | Downloading package pe08 to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/pe08.zip.
[nltk_data]    | Downloading package perluniprops to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping misc/perluniprops.zip.
[nltk_data]    | Downloading package pil to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/pil.zip.
[nltk_data]    | Downloading package pl196x to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/pl196x.zip.
[nltk_data]    | Downloading package porter_test to /root/nltk_data...
[nltk_data]    |   Unzipping stemmers/porter_test.zip.
[nltk_data]    | Downloading package ppattach to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/ppattach.zip.
[nltk_data]    | Downloading package problem_reports to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/problem_reports.zip.
[nltk_data]    | Downloading package product_reviews_1 to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/product_reviews_1.zip.
[nltk_data]    | Downloading package product_reviews_2 to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/product_reviews_2.zip.
[nltk_data]    | Downloading package propbank to /root/nltk_data...
[nltk_data]    | Downloading package pros_cons to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/pros_cons.zip.
[nltk_data]    | Downloading package ptb to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/ptb.zip.
[nltk_data]    | Downloading package punkt to /root/nltk_data...
[nltk_data]    |   Unzipping tokenizers/punkt.zip.
[nltk_data]    | Downloading package qc to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/qc.zip.
[nltk_data]    | Downloading package reuters to /root/nltk_data...
[nltk_data]    | Downloading package rslp to /root/nltk_data...
[nltk_data]    |   Unzipping stemmers/rslp.zip.
[nltk_data]    | Downloading package rte to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/rte.zip.
[nltk_data]    | Downloading package sample_grammars to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping grammars/sample_grammars.zip.
[nltk_data]    | Downloading package semcor to /root/nltk_data...
[nltk_data]    | Downloading package senseval to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/senseval.zip.
[nltk_data]    | Downloading package sentence_polarity to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/sentence_polarity.zip.
[nltk_data]    | Downloading package sentiwordnet to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/sentiwordnet.zip.
[nltk_data]    | Downloading package shakespeare to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/shakespeare.zip.
[nltk_data]    | Downloading package sinica_treebank to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/sinica_treebank.zip.
[nltk_data]    | Downloading package smultron to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/smultron.zip.
[nltk_data]    | Downloading package snowball_data to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    | Downloading package spanish_grammars to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping grammars/spanish_grammars.zip.
[nltk_data]    | Downloading package state_union to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/state_union.zip.
[nltk_data]    | Downloading package stopwords to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/stopwords.zip.
[nltk_data]    | Downloading package subjectivity to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/subjectivity.zip.
[nltk_data]    | Downloading package swadesh to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/swadesh.zip.
[nltk_data]    | Downloading package switchboard to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/switchboard.zip.
[nltk_data]    | Downloading package tagsets to /root/nltk_data...
[nltk_data]    |   Unzipping help/tagsets.zip.
[nltk_data]    | Downloading package timit to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/timit.zip.
[nltk_data]    | Downloading package toolbox to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/toolbox.zip.
[nltk_data]    | Downloading package treebank to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/treebank.zip.
[nltk_data]    | Downloading package twitter_samples to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/twitter_samples.zip.
[nltk_data]    | Downloading package udhr to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/udhr.zip.
[nltk_data]    | Downloading package udhr2 to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/udhr2.zip.
[nltk_data]    | Downloading package unicode_samples to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/unicode_samples.zip.
[nltk_data]    | Downloading package universal_tagset to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping taggers/universal_tagset.zip.
[nltk_data]    | Downloading package universal_treebanks_v20 to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    | Downloading package vader_lexicon to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    | Downloading package verbnet to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/verbnet.zip.
[nltk_data]    | Downloading package verbnet3 to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/verbnet3.zip.
[nltk_data]    | Downloading package webtext to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/webtext.zip.
[nltk_data]    | Downloading package wmt15_eval to /root/nltk_data...
[nltk_data]    |   Unzipping models/wmt15_eval.zip.
[nltk_data]    | Downloading package word2vec_sample to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping models/word2vec_sample.zip.
[nltk_data]    | Downloading package wordnet to /root/nltk_data...
[nltk_data]    |   Package wordnet is already up-to-date!
[nltk_data]    | Downloading package wordnet2021 to /root/nltk_data...
[nltk_data]    | Downloading package wordnet2022 to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/wordnet2022.zip.
[nltk_data]    | Downloading package wordnet31 to /root/nltk_data...
[nltk_data]    | Downloading package wordnet_ic to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/wordnet_ic.zip.
[nltk_data]    | Downloading package words to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/words.zip.
[nltk_data]    | Downloading package ycoe to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/ycoe.zip.
[nltk_data]    |
[nltk_data]  Done downloading collection all
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

Downloading (…)925a9/.gitattributes:   0%|          | 0.00/690 [00:00<?, ?B/s]

Downloading (…)_Pooling/config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

Downloading (…)1a515925a9/README.md:   0%|          | 0.00/3.99k [00:00<?, ?B/s]

Downloading (…)515925a9/config.json:   0%|          | 0.00/550 [00:00<?, ?B/s]

Downloading (…)ce_transformers.json:   0%|          | 0.00/122 [00:00<?, ?B/s]

Downloading pytorch_model.bin:   0%|          | 0.00/265M [00:00<?, ?B/s]

Downloading (…)nce_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

Downloading (…)cial_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

Downloading (…)925a9/tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

Downloading (…)okenizer_config.json:   0%|          | 0.00/450 [00:00<?, ?B/s]

Downloading (…)1a515925a9/vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

Downloading (…)15925a9/modules.json:   0%|          | 0.00/229 [00:00<?, ?B/s]

Texte d'origine : Project Risk Management includes the processes of conducting risk management planning, identification, analysis,
response planning, response implementation, and monitoring risk on a project. The objectives of project risk management
are to increase the probability and/or impact of positive risks and to decrease the probability and/or impact of negative
risks, in order to optimize the chances of project success.
The Project Risk Management processes are:
11.1 Plan Risk Management—The process of defining how to conduct risk management activities for a project.
11.2 Identify Risks—The process of identifying individual project risks as well as sources of overall project risk,
and documenting their characteristics.
11.3 Perform Qualitative Risk Analysis—The process of prioritizing individual project risks for further analysis
or action by assessing their probability of occurrence and impact as well as other characteristics.
11.4 Perform Quantitative Risk Analysis—The process of numerically analyzing the combined effect of identified
individual project risks and other sources of uncertainty on overall project objectives.
11.5 Plan Risk Responses—The process of developing options, selecting strategies, and agreeing on actions to
address overall project risk exposure, as well as to treat individual project risks.
11.6 Implement Risk Responses—The process of implementing agreed-upon risk response plans.
11.7 Monitor Risks—The process of monitoring the implementation of agreed-upon risk response plans,
tracking identified risks, identifying and analyzing new risks, and evaluating risk process effectiveness throughout the
project.
Figure 11-1 provides an overview of the Project Risk Management processes. The Project Management Risk processes
are presented as discrete processes with defined interfaces while, in practice, they overlap and interact in ways that
cannot be completely detailed in this PMBOK® Guide.
NubPage 365
KEY CONCEPTS FOR PROJECT RISK MANAGEMENT
All projects are risky since they are unique undertakings with varying degrees of complexity that aim to deliver
benefits. They do this in a context of constraints and assumptions, while responding to stakeholder expectations that
may be conflicting and changing. Organizations should choose to take project risk in a controlled and intentional manner
in order to create value while balancing risk and reward.
Project Risk Management aims to identify and manage risks that are not addressed by the other project management
processes. When unmanaged, these risks have the potential to cause the project to deviate from the plan and fail to
achieve the defined project objectives. Consequently, the effectiveness of Project Risk Management is directly related to
project success.
Risk exists at two levels within every project. Each project contains individual risks that can affect the achievement of
project objectives. It is also important to consider the riskiness of the overall project, which arises from the combination
of individual project risks and other sources of uncertainty. Project Risk Management processes address both levels of risk
in projects, and these are defined as follows:
◆ Individual project risk is an uncertain event or condition that, if it occurs, has a positive or negative effect on one
or more project objectives.
◆ Overall project risk is the effect of uncertainty on the project as a whole, arising from all sources of uncertainty
including individual risks, representing the exposure of stakeholders to the implications of variations in project
outcome, both positive and negative.
Individual project risks can have a positive or negative effect on project objectives if they occur. Project Risk
Management aims to exploit or enhance positive risks (opportunities) while avoiding or mitigating negative risks
(threats). Unmanaged threats may result in issues or problems such as delay, cost overruns, performance shortfall,
or loss of reputation. Opportunities that are captured can lead to benefits such as reduced time and cost, improved
performance, or reputation.
Overall project risk can also be positive or negative. Management of overall project risk aims to keep project risk
exposure within an acceptable range by reducing drivers of negative variation, promoting drivers of positive variation, and
maximizing the probability of achieving overall project objectives.
NubPage 366
Risks will continue to emerge during the lifetime of the project, so Project Risk Management processes should be conducted
iteratively. Risk is initially addressed during project planning by shaping the project strategy. Risk should also be monitored and
managed as the project progresses to ensure that the project stays on track and emergent risks are addressed.
In order to manage risk effectively on a particular project, the project team needs to know what level of risk exposure
is acceptable in pursuit of the project objectives. This is defined by measurable risk thresholds that reflect the risk appetite
of the organization and project stakeholders. Risk thresholds express the degree of acceptable variation around a project
objective. They are explicitly stated and communicated to the project team and reflected in the definitions of risk impact
levels for the project.
TRENDS AND EMERGING PRACTICES IN PROJECT RISK MANAGEMENT
The focus of project risk management is broadening to ensure that all types of risk are considered, and that project
risks are understood in a wider context. Trends and emerging practices for Project Risk Management include but are
not limited to:
◆ Non-event risks. Most projects focus only on risks that are uncertain future events that may or may not occur.
Examples of event-based risks include: a key seller may go out of business during the project, the customer may
change the requirement after design is complete, or a subcontractor may propose enhancements to the standard
operating processes.
There is an increasing recognition that non-event risks need to be identified and managed. There are two main
types of non-event risks:
◼ Variability risk. Uncertainty exists about some key characteristics of a planned event or activity or decision.
Examples of variability risks include: productivity may be above or below target, the number of errors found
during testing may be higher or lower than expected, or unseasonal weather conditions may occur during the
construction phase.
◼ Ambiguity risk. Uncertainty exists about what might happen in the future. Areas of the project where
imperfect knowledge might affect the project’s ability to achieve its objectives include: elements of the
requirement or technical solution, future developments in regulatory frameworks, or inherent systemic
complexity in the project.
NubPage 367
Variability risks can be addressed using Monte Carlo analysis, with the range of variation reflected in probability
distributions, followed by actions to reduce the spread of possible outcomes. Ambiguity risks are managed by
defining those areas where there is a deficit of knowledge or understanding, then filling the gap by obtaining expert
external input or benchmarking against best practices. Ambiguity is also addressed through incremental
development, prototyping, or simulation.
◆ Project resilience. The existence of emergent risk is becoming clear, with a growing awareness of so-called
unknowable-unknowns. These are risks that can only be recognized after they have occurred. Emergent risks
can be tackled through developing project resilience. This requires each project to have:
◼ Right level of budget and schedule contingency for emergent risks, in addition to a specific risk budget for
known risks;
◼ Flexible project processes that can cope with emergent risk while maintaining overall direction toward project
goals, including strong change management;
◼ Empowered project team that has clear objectives and that is trusted to get the job done within agreed-
upon limits;
◼ Frequent review of early warning signs to identify emergent risks as early as possible; and
◼ Clear input from stakeholders to clarify areas where the project scope or strategy can be adjusted in response
to emergent risks.
◆ Integrated risk management. Projects exist in an organizational context, and they may form part of a program
or portfolio. Risk exists at each of these levels, and risks should be owned and managed at the appropriate level.
Some risks identified at higher levels will be delegated to the project team for management, and some project
risks may be escalated to higher levels if they are best managed outside the project. A coordinated approach to
enterprise-wide risk management ensures alignment and coherence in the way risk is managed across all levels.
This builds risk efficiency into the structure of programs and portfolios, providing the greatest overall value for a
given level of risk exposure.
NubPage 368
TAILORING CONSIDERATIONS
Because each project is unique, it is necessary to tailor the way Project Risk Management processes are applied.
Considerations for tailoring include but are not limited to:
◆ Project size. Does the project’s size in terms of budget, duration, scope, or team size require a more detailed
approach to risk management? Or is it small enough to justify a simplified risk process?
◆ Project complexity. Is a robust risk approach demanded by high levels of innovation, new technology, commercial
arrangements, interfaces, or external dependencies that increase project complexity? Or is the project simple
enough that a reduced risk process will suffice?
◆ Project importance. How strategically important is the project? Is the level of risk increased for this project
because it aims to produce breakthrough opportunities, addresses significant blocks to organizational
performance, or involves major product innovation?
◆ Development approach. Is this a waterfall project, where risk processes can be followed sequentially and
iteratively, or does the project follow an agile approach where risk is addressed at the start of each iteration as
well as during its execution?
Tailoring of the Project Risk Management processes to meet these considerations is part of the Plan Risk Management
process, and the outcomes of tailoring decisions are recorded in the risk management plan.
CONSIDERATIONS FOR AGILE/ADAPTIVE ENVIRONMENTS
High-variability environments, by definition, incur more uncertainty and risk. To address this, projects managed using
adaptive approaches make use of frequent reviews of incremental work products and cross-functional project teams to
accelerate knowledge sharing and ensure that risk is understood and managed. Risk is considered when selecting the
content of each iteration, and risks will also be identified, analyzed, and managed during each iteration.
Additionally, the requirements are kept as a living document that is updated regularly, and work may be reprioritized
as the project progresses, based on an improved understanding of current risk exposure.
Mots-clés lemmatisés et fusionnés : ['tailoring project risk', 'shaping project strategy', 'subcontractor propose enhancement', 'planning shaping project', 'project planning shaping']
Texte d'origine : Plan Risk Management is the process of defining how to conduct risk management activities for a project. The key
benefit of this process is that it ensures that the degree, type, and visibility of risk management are proportionate to both
risks and the importance of the project to the organization and other stakeholders. This process is performed once or
at predefined points in the project. The inputs, tools and techniques, and outputs of the process are depicted in Figure
11-2. Figure 11-3 depicts the data flow diagram for the process.
NubPage 369
The Plan Risk Management process should begin when a project is conceived and should be completed early in the
project. It may be necessary to revisit this process later in the project life cycle, for example at a major phase change, or
if the project scope changes significantly, or if a subsequent review of risk management effectiveness determines that the
Project Risk Management process requires modification.
Mots-clés lemmatisés et fusionnés : ['effectiveness determines project', 'project necessary revisit', 'determines project risk', 'management process defining', 'predefined point project']
Texte d'origine : Described in Section 4.1.3.1. The project charter documents the high-level project description and boundaries, high-
level requirements, and risks.
NubPage 370
Mots-clés lemmatisés et fusionnés : ['project charter document', 'section project charter', 'risk nubpage 370', 'nubpage 370', 'project description']
Texte d'origine : Described in Section 4.2.3.1. In planning Project Risk Management, all approved subsidiary management plans
should be taken into consideration in order to make the risk management plan consistent with them. The methodology
outlined in other project management plan components might influence the Plan Risk Management process.
Mots-clés lemmatisés et fusionnés : ['component influence plan', 'plan taken consideration', 'plan component influence', 'outlined project management', 'management plan taken']
Texte d'origine : Project documents that can be considered as inputs for this process include but are not limited to the stakeholder
register as described in Section 13.1.3.1. The stakeholder register contains details of the project’s stakeholders and
provides an overview of their project roles and their attitude toward risk on this project. This is useful in determining
roles and responsibilities for managing risk on the project, as well as setting risk thresholds for the project.
Mots-clés lemmatisés et fusionnés : ['detail project stakeholder', 'project stakeholder provides', 'managing risk project', 'project document considered', 'project stakeholder']
Texte d'origine : The enterprise environmental factors that can influence the Plan Risk Management process include but are not
limited to overall risk thresholds set by the organization or key stakeholders.
Mots-clés lemmatisés et fusionnés : ['environmental factor influence', 'enterprise environmental factor', 'environmental factor', 'factor influence plan', 'enterprise environmental']
Texte d'origine : The organizational process assets that can influence the Plan Risk Management process include but are not
limited to:
◆ Organizational risk policy;
◆ Risk categories, possibly organized into a risk breakdown structure;
◆ Common definitions of risk concepts and terms;
◆ Risk statement formats;
◆ Templates for the risk management plan, risk register, and risk report;
◆ Roles and responsibilities;
◆ Authority levels for decision making; and
◆ Lessons learned repository from previous similar projects.
NubPage 371
Mots-clés lemmatisés et fusionnés : ['similar project nubpage', 'management process include', 'report role responsibility', 'similar project', 'risk report role']
Texte d'origine : Described in Section 4.1.2.1. Expertise should be considered from individuals or groups with specialized knowledge
or training in the following topics:
◆ Familiarity with the organization’s approach to managing risk, including enterprise risk management where this
is performed;
◆ Tailoring risk management to the specific needs of a project; and
◆ Types of risk that are likely to be encountered on projects in the same area.
Mots-clés lemmatisés et fusionnés : ['training following topic', 'tailoring risk management', 'management specific need', 'need project type', 'specific need project']
Texte d'origine : Data analysis techniques that can be used for this process includes but are not limited to a stakeholder analysis
(Section 13.1.2.3) to determine the risk appetite of project stakeholders.
Mots-clés lemmatisés et fusionnés : ['stakeholder analysis section', 'project stakeholder', 'appetite project stakeholder', 'used process includes', 'stakeholder analysis']
Texte d'origine : The risk management plan may be developed as part of the project kick-off meeting or a specific planning meeting may
be held. Attendees may include the project manager, selected project team members, key stakeholders, or team members
who are responsible to manage the risk management process on the project. Others outside the organization may also be
invited, as needed, including customers, sellers, and regulators. A skilled facilitator can help participants remain focused
on the task, agree on key aspects of the risk approach, identify and overcome sources of bias, and resolve any
disagreements that may arise.
Plans for conducting risk management activities are defined in these meetings and documented in the risk
management plan (see Section 11.1.3.1).
NubPage 372
Mots-clés lemmatisés et fusionnés : ['attendee include project', 'planning meeting held', 'manager selected project', 'specific planning meeting', 'meeting held attendee']
Texte d'origine : The risk management plan is a component of the project management plan that describes how risk management
activities will be structured and performed. The risk management plan may include some or all of the following elements:
◆ Risk strategy. Describes the general approach to managing risk on this project.
◆ Methodology. Defines the specific approaches, tools, and data sources that will be used to perform risk
management on the project.
◆ Roles and responsibilities. Defines the lead, support, and risk management team members for each type of
activity described in the risk management plan, and clarifies their responsibilities.
◆ Funding. Identifies the funds needed to perform activities related to Project Risk Management. Establishes
protocols for the application of contingency and management reserves.
◆ Timing. Defines when and how often the Project Risk Management processes will be performed throughout the
project life cycle, and establishes risk management activities for inclusion into the project schedule.
◆ Risk categories. Provide a means for grouping individual project risks. A common way to structure risk categories
is with a risk breakdown structure (RBS), which is a hierarchical representation of potential sources of risk (see
example in Figure 11-4). An RBS helps the project team consider the full range of sources from which individual
project risks may arise. This can be useful when identifying risks or when categorizing identified risks. The
organization may have a generic RBS to be used for all projects, or there may be several RBS frameworks for
different types of projects, or the project may develop a tailored RBS. Where an RBS is not used, an organization
may use a custom risk categorization framework, which may take the form of a simple list of categories or a
structure based on project objectives.
NubPage 373
NubPage 374
◆ Stakeholder risk appetite. The risk appetites of key stakeholders on the project are recorded in the risk
management plan, as they inform the details of the Plan Risk Management process. In particular, stakeholder risk
appetite should be expressed as measurable risk thresholds around each project objective. These thresholds will
determine the acceptable level of overall project risk exposure, and they are also used to inform the definitions of
probability and impacts to be used when assessing and prioritizing individual project risks.
◆ Definitions of risk probability and impacts. Definitions of risk probability and impact levels are specific to the
project context and reflect the risk appetite and thresholds of the organization and key stakeholders. The project
may generate specific definitions of probability and impact levels or it may start with general definitions provided
by the organization. The number of levels reflects the degree of detail required for the Project Risk Management
process, with more levels used for a more detailed risk approach (typically five levels), and fewer for a simple

,Concept,Description,Keywords
0,11 PROJECT RISK MANAGEMENT,Project Risk Management includes the processes...,"[tailoring project risk, shaping project strat..."
1,11.1 PLAN RISK MANAGEMENT,Plan Risk Management is the process of definin...,"[effectiveness determines project, project nec..."
2,11.1.1 PLAN RISK MANAGEMENT: INPUTS,None,[]
3,11.1.1.1 PROJECT CHARTER,Described in Section 4.1.3.1. The project char...,"[project charter document, section project cha..."
4,11.1.1.2 PROJECT MANAGEMENT PLAN,Described in Section 4.2.3.1. In planning Proj...,"[component influence plan, plan taken consider..."
...,...,...,...
106,11.7.3.1 WORK PERFORMANCE INFORMATION,Described in Section 4.5.1.3. Work performance...,"[project risk management, work performance inf..."
107,11.7.3.2 CHANGE REQUESTS,Described in Section 4.3.3.4. The Monitor Risk...,"[plan change request, change request include, ..."
108,11.7.3.3 PROJECT MANAGEMENT PLAN UPDATES,Any change to the project management plan goes...,"[change project management, organization chang..."
109,11.7.3.4 PROJECT DOCUMENTS UPDATES,Project documents that may be updated as a res...,"[project document updated, risk report updated..."
110,11.7.3.5 ORGANIZATIONAL PROCESS ASSETS UPDATES,Organizational process assets that are updated...,"[process asset updated, updated result monitor..."

In [ ]:
df2['Description'] = df2['Description'].fillna('')

In [ ]:
df2

,Concept,Description,Keywords
0,11 PROJECT RISK MANAGEMENT,Project Risk Management includes the processes...,"[tailoring project risk, shaping project strat..."
1,11.1 PLAN RISK MANAGEMENT,Plan Risk Management is the process of definin...,"[effectiveness determines project, project nec..."
2,11.1.1 PLAN RISK MANAGEMENT: INPUTS,,[]
3,11.1.1.1 PROJECT CHARTER,Described in Section 4.1.3.1. The project char...,"[project charter document, section project cha..."
4,11.1.1.2 PROJECT MANAGEMENT PLAN,Described in Section 4.2.3.1. In planning Proj...,"[component influence plan, plan taken consider..."
...,...,...,...
106,11.7.3.1 WORK PERFORMANCE INFORMATION,Described in Section 4.5.1.3. Work performance...,"[project risk management, work performance inf..."
107,11.7.3.2 CHANGE REQUESTS,Described in Section 4.3.3.4. The Monitor Risk...,"[plan change request, change request include, ..."
108,11.7.3.3 PROJECT MANAGEMENT PLAN UPDATES,Any change to the project management plan goes...,"[change project management, organization chang..."
109,11.7.3.4 PROJECT DOCUMENTS UPDATES,Project documents that may be updated as a res...,"[project document updated, risk report updated..."
110,11.7.3.5 ORGANIZATIONAL PROCESS ASSETS UPDATES,Organizational process assets that are updated...,"[process asset updated, updated result monitor..."

In [ ]:
def convert_to_lowercase(text):
    words = text.split()
    updated_words = [word.lower() if word.isupper() else word for word in words]
    return ' '.join(updated_words)

# Apply the function to the 'Concepts' column
df2['Concept'] = df2['Concept'].apply(convert_to_lowercase)

In [ ]:
# Load model and tokenizer
tokenizer = AutoTokenizer.from_pretrained("Babelscape/rebel-large")
model = AutoModelForSeq2SeqLM.from_pretrained("Babelscape/rebel-large")

Downloading (…)okenizer_config.json:   0%|          | 0.00/1.23k [00:00<?, ?B/s]

Downloading (…)olve/main/vocab.json:   0%|          | 0.00/798k [00:00<?, ?B/s]

Downloading (…)olve/main/merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

Downloading (…)/main/tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

Downloading (…)in/added_tokens.json:   0%|          | 0.00/123 [00:00<?, ?B/s]

Downloading (…)cial_tokens_map.json:   0%|          | 0.00/344 [00:00<?, ?B/s]

Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.

Downloading (…)lve/main/config.json:   0%|          | 0.00/1.42k [00:00<?, ?B/s]

Downloading model.safetensors:   0%|          | 0.00/1.63G [00:00<?, ?B/s]

In [ ]:
def extract_relations_from_model_output(text):
    relations = []
    relation, subject, relation, object_ = '', '', '', ''
    text = text.strip()
    current = 'x'
    text_replaced = text.replace("<s>", "").replace("<pad>", "").replace("</s>", "")
    for token in text_replaced.split():
        if token == "<triplet>":
            current = 't'
            if relation != '':
                relations.append({
                    'head': subject.strip(),
                    'type': relation.strip(),
                    'tail': object_.strip()
                })
                relation = ''
            subject = ''
        elif token == "<subj>":
            current = 's'
            if relation != '':
                relations.append({
                    'head': subject.strip(),
                    'type': relation.strip(),
                    'tail': object_.strip()
                })
            object_ = ''
        elif token == "<obj>":
            current = 'o'
            relation = ''
        else:
            if current == 't':
                subject += ' ' + token
            elif current == 's':
                object_ += ' ' + token
            elif current == 'o':
                relation += ' ' + token
    if subject != '' and relation != '' and object_ != '':
        relations.append({
            'head': subject.strip(),
            'type': relation.strip(),
            'tail': object_.strip()
        })
    return relations

In [ ]:
class KB():
    def __init__(self):
        self.relations = []

    def are_relations_equal(self, r1, r2):
        return all(r1[attr] == r2[attr] for attr in ["head", "type", "tail"])

    def exists_relation(self, r1):
        return any(self.are_relations_equal(r1, r2) for r2 in self.relations)

    def add_relation(self, r):
        if not self.exists_relation(r):
            self.relations.append(r)

    def save(self):
        dict_list = []
        for r in self.relations:
            dict_list.append(r)
        return(dict_list)
        #df = pd.DataFrame(dict_list, columns=['head', 'type', 'tail'])
        #print(dict_list)

In [ ]:
def from_small_text_to_kb(text, verbose=False):
    kb = KB()

    # Tokenizer text
    model_inputs = tokenizer(text, max_length=512, padding=True, truncation=True,
                            return_tensors='pt')
    if verbose:
        print(f"Num tokens: {len(model_inputs['input_ids'][0])}")

    # Generate
    gen_kwargs = {
        "max_length": 1000,
        "length_penalty": 0,
        "num_beams": 3,
        "num_return_sequences": 3
    }

    generated_tokens = model.generate(
        **model_inputs,
        **gen_kwargs,
    )

    decoded_preds = tokenizer.batch_decode(generated_tokens, skip_special_tokens=False)

    # create kb
    for sentence_pred in decoded_preds:
        relations = extract_relations_from_model_output(sentence_pred)
        for r in relations:
            kb.add_relation(r)

    return kb

In [ ]:
df2['Description'] = df2['Description'].str.encode('utf-8', 'ignore').str.decode('utf-8')

In [ ]:
import pandas as pd
relation_list = []

# Étape 3 : Appliquer le code à la colonne 'Descr'
for item in tqdm(df2['Description']):
    if isinstance(item, str):  # Vérifier si l'élément est une chaîne de caractères valide
        try:
            kb = from_small_text_to_kb(item, verbose=False) # Remplacez avec votre fonction
            relation_list.append(kb.save())
        except Exception as e:
            print(f"Erreur : {e} pour l'élément '{item}'") # Afficher les erreurs éventuelles
    else:
        print(f"Attention : élément non valide '{item}'")

# Étape 4 : Vérifiez la longueur de la liste et imprimez-la
print(f"Longueur de la liste : {len(relation_list)}")

# Étape 5 : Si la longueur de la liste est correcte, ajoutez les résultats à une nouvelle colonne du DataFrame
if len(relation_list) == len(df2):
    df2['Relation'] = relation_list
else:
    print("Erreur : La longueur de la liste ne correspond pas à la longueur du DataFrame.")

# Étape 6 : Affichez le DataFrame modifié
print(df2)

100%|██████████| 111/111 [08:32<00:00,  4.62s/it]

Longueur de la liste : 111
                                            Concept  \
0                        11 project risk management
1                         11.1 plan risk management
2               11.1.1 plan risk management: inputs
3                          11.1.1.1 project charter
4                  11.1.1.2 project management plan
..                                              ...
106           11.7.3.1 work performance information
107                        11.7.3.2 change requests
108        11.7.3.3 project management plan updates
109              11.7.3.4 project documents updates
110  11.7.3.5 organizational process assets updates

                                           Description  \
0    Project Risk Management includes the processes...
1    Plan Risk Management is the process of definin...
2
3    Described in Section 4.1.3.1. The project char...
4    Described in Section 4.2.3.1. In planning Proj...
..                                                 ...
106  Described in Section 4.5.1.3. Work performance...
107  Described in Section 4.3.3.4. The Monitor Risk...
108  Any change to the project management plan goes...
109  Project documents that may be updated as a res...
110  Organizational process assets that are updated...

                                              Keywords  \
0    [tailoring project risk, shaping project strat...
1    [effectiveness determines project, project nec...
2                                                   []
3    [project charter document, section project cha...
4    [component influence plan, plan taken consider...
..                                                 ...
106  [project risk management, work performance inf...
107  [plan change request, change request include, ...
108  [change project management, organization chang...
109  [project document updated, risk report updated...
110  [process asset updated, updated result monitor...

                                              Relation
0    [{'head': 'risk management', 'type': 'studies'...
1    [{'head': 'Plan Risk Management', 'type': 'use...
2    [{'head': 'World Heritage Site', 'type': 'main...
3    [{'head': 'requirements', 'type': 'part of', '...
4    [{'head': 'Project Risk Management', 'type': '...
..                                                 ...
106  [{'head': 'Work performance information', 'typ...
107  [{'head': 'Monitor Risks', 'type': 'facet of',...
108  [{'head': 'change control', 'type': 'facet of'...
109  [{'head': 'Assumption log', 'type': 'facet of'...
110  [{'head': 'risk register', 'type': 'use', 'tai...

[111 rows x 4 columns]

In [ ]:
dict_list =[]
for item in tqdm(relation_list):
    for dic in item:
        dict_list.append(dic)
triplet = pd.DataFrame(dict_list, columns=['head', 'type', 'tail'])

100%|██████████| 111/111 [00:00<00:00, 158356.38it/s]

In [ ]:
triplet

                        head         type                  tail
0            risk management      studies                  risk
1                       risk   studied by       risk management
2    Project Risk Management  subclass of       risk management
3       Plan Risk Management          use       risk management
4       Plan Risk Management     facet of       risk management
..                       ...          ...                   ...
336           Assumption log     facet of         Monitor Risks
337           Assumption log  subclass of         risk register
338            risk register          use       risk management
339            risk register      part of  risk management plan
340            risk register          use  risk management plan

[341 rows x 3 columns]

In [ ]:
unique_triplets = triplet.drop_duplicates()

In [ ]:
unique_triplets

                        head         type                     tail
0            risk management      studies                     risk
1                       risk   studied by          risk management
2    Project Risk Management  subclass of          risk management
3       Plan Risk Management          use          risk management
4       Plan Risk Management     facet of          risk management
..                       ...          ...                      ...
333           change control     facet of  project management plan
334   change control process     facet of  project management plan
335           change control      part of  project management plan
336           Assumption log     facet of            Monitor Risks
337           Assumption log  subclass of            risk register

[257 rows x 3 columns]

In [ ]:
tiplet_unique = triplet['head'].unique()

In [ ]:
final_triplet_unique = triplet.drop_duplicates(keep='first')

In [ ]:
final_triplet_unique = final_triplet_unique.reset_index(drop=True)

In [ ]:
final_triplet_unique

                        head         type                     tail
0            risk management      studies                     risk
1                       risk   studied by          risk management
2    Project Risk Management  subclass of          risk management
3       Plan Risk Management          use          risk management
4       Plan Risk Management     facet of          risk management
..                       ...          ...                      ...
252           change control     facet of  project management plan
253   change control process     facet of  project management plan
254           change control      part of  project management plan
255           Assumption log     facet of            Monitor Risks
256           Assumption log  subclass of            risk register

[257 rows x 3 columns]

In [ ]:
text = ''
for item in df2['Description']:
    text += item

In [ ]:
text = ''
for item in df2['Description']:
    text += ''.join(item)
example_sent = text
stop_words = set(stopwords.words('english'))
word_tokens = word_tokenize(example_sent)
filtered_sentence = [w for w in word_tokens if not w.lower() in stop_words]
filtered_sentence = []

for w in word_tokens:
    if w not in stop_words:
        filtered_sentence.append(w)
test_text = ' '.join(filtered_sentence)

In [ ]:
import textacy
triple_list = []
for sentence in test_text.split('.'):
    t1 = nlp(sentence)
    triple = textacy.extract.subject_verb_object_triples(t1)
    if triple:
        triple_to_list = list(triple)
        triple_list.append(pd.DataFrame(triple_to_list))
svo=pd.concat(triple_list, axis=0) # this should concat all dfs on top of one another using axis=0
svo.columns=['subject','verb','object'] # change your columns on teh final df

In [ ]:
svo

,subject,verb,object
0,"[Project, Risk, Management]",[includes],[processes]
0,"[objectives, project, impact, risks]",[decrease],[risks]
1,[order],[optimize],"[project, success]"
0,[3],[Perform],"[Qualitative, Risk, Analysis]"
1,[process],[risks],"[analysis, action, probability, occurrence, im..."
...,...,...,...
0,[This],"[may, include]","[adding, new, risks, ,, updating, outdated, ri..."
0,[project],[risks],"[project, risk]"
0,"[risk, report]","[may, include]",[details]
0,[It],"[may, include]","[conclusions, effectiveness, management, process]"
0,"[Risks, process]",[include],"[Templates, management, plan, risk, register, ..."

In [ ]:
svo = svo.reset_index(drop=True)

In [ ]:
final_svo = copy.deepcopy(svo)

In [ ]:
for idx,row in final_svo.iterrows():
    for c in final_svo.columns:
        for i in row[c]:
            if isinstance(i, spacy.tokens.span.Span):
                row[c] = i.text
            else:
                row[c] = i

In [ ]:
for idx,item in enumerate(final_svo['subject']):
    if isinstance(item, spacy.tokens.token.Token):
        item = item.text
        final_svo.iloc[idx]['subject'] = item
    else:
        item = item
        final_svo.iloc[idx]['subject'] = item
for idx,item in enumerate(final_svo['verb']):
    if isinstance(item, spacy.tokens.token.Token):
        item = item.text
        final_svo.iloc[idx]['verb'] = item
    else:
        item = item
        final_svo.iloc[idx]['verb'] = item
for idx,item in enumerate(final_svo['object']):
    if isinstance(item, spacy.tokens.token.Token):
        item = item.text
        final_svo.iloc[idx]['object'] = item
    else:
        item = item
        final_svo.iloc[idx]['object'] = item

In [ ]:
concept_list = []
concept_index = []
for _,row in final_svo.iterrows():
    item = row['subject']
    for i in tiplet_unique:
        if (i in item):
            concept_list.append(item)
            concept_index.append(list(final_svo['subject']).index(item))
svo_unique = dict(zip(concept_index, concept_list))

In [ ]:
final_svo_unique = final_svo.drop_duplicates(keep='first')

In [ ]:
final_svo_unique

        subject      verb     object
0    Management  includes  processes
1         risks  decrease      risks
2         order  optimize    success
3             3   Perform   Analysis
4       process     risks     impact
..          ...       ...        ...
744        risk  register      risks
745        This   include          ,
747      report   include    details
748          It   include    process
749     process   include  structure

[657 rows x 3 columns]

In [ ]:
df_final['Concepts'] = data_frame['scope_concepts']
df2['Type_relation'] = ''
df2['Concept_of_type_relation'] = ''

NameError: ignored

In [ ]:
final_triplet_unique = final_triplet_unique.reset_index(drop=True)

In [ ]:
final_triplet_unique

                        head         type                     tail
0            risk management      studies                     risk
1                       risk   studied by          risk management
2    Project Risk Management  subclass of          risk management
3       Plan Risk Management          use          risk management
4       Plan Risk Management     facet of          risk management
..                       ...          ...                      ...
252           change control     facet of  project management plan
253   change control process     facet of  project management plan
254           change control      part of  project management plan
255           Assumption log     facet of            Monitor Risks
256           Assumption log  subclass of            risk register

[257 rows x 3 columns]

In [ ]:
for _,row1 in final_triplet_unique.iterrows():
    for _,row2 in df2.iterrows():
        if row1['head'] in row2['Concept']:
            row2['Type_relation'] = row1['type']
            row2['Concept_of_type_relation'] = row1['tail']

In [ ]:
df2

,Concept,Description,Keywords,Relation
0,11 project risk management,Project Risk Management includes the processes...,"[tailoring project risk, shaping project strat...","[{'head': 'risk management', 'type': 'studies'..."
1,11.1 plan risk management,Plan Risk Management is the process of definin...,"[effectiveness determines project, project nec...","[{'head': 'Plan Risk Management', 'type': 'use..."
2,11.1.1 plan risk management: inputs,,[],"[{'head': 'World Heritage Site', 'type': 'main..."
3,11.1.1.1 project charter,Described in Section 4.1.3.1. The project char...,"[project charter document, section project cha...","[{'head': 'requirements', 'type': 'part of', '..."
4,11.1.1.2 project management plan,Described in Section 4.2.3.1. In planning Proj...,"[component influence plan, plan taken consider...","[{'head': 'Project Risk Management', 'type': '..."
...,...,...,...,...
106,11.7.3.1 work performance information,Described in Section 4.5.1.3. Work performance...,"[project risk management, work performance inf...","[{'head': 'Work performance information', 'typ..."
107,11.7.3.2 change requests,Described in Section 4.3.3.4. The Monitor Risk...,"[plan change request, change request include, ...","[{'head': 'Monitor Risks', 'type': 'facet of',..."
108,11.7.3.3 project management plan updates,Any change to the project management plan goes...,"[change project management, organization chang...","[{'head': 'change control', 'type': 'facet of'..."
109,11.7.3.4 project documents updates,Project documents that may be updated as a res...,"[project document updated, risk report updated...","[{'head': 'Assumption log', 'type': 'facet of'..."
110,11.7.3.5 organizational process assets updates,Organizational process assets that are updated...,"[process asset updated, updated result monitor...","[{'head': 'risk register', 'type': 'use', 'tai..."

In [ ]:
df2['reference'] = None
df2['links']= None

In [ ]:
import pandas as pd
# Replace 'figre' with 'figure' in the 'Text' column
df2['Description'] = df2['Description'].str.replace('figre', 'figure')

# Print the updated DataFrame
print(df2)

                                            Concept  \
0                        11 project risk management
1                         11.1 plan risk management
2               11.1.1 plan risk management: inputs
3                          11.1.1.1 project charter
4                  11.1.1.2 project management plan
..                                              ...
106           11.7.3.1 work performance information
107                        11.7.3.2 change requests
108        11.7.3.3 project management plan updates
109              11.7.3.4 project documents updates
110  11.7.3.5 organizational process assets updates

                                           Description  \
0    Project Risk Management includes the processes...
1    Plan Risk Management is the process of definin...
2
3    Described in Section 4.1.3.1. The project char...
4    Described in Section 4.2.3.1. In planning Proj...
..                                                 ...
106  Described in Section 4.5.1.3. Work performance...
107  Described in Section 4.3.3.4. The Monitor Risk...
108  Any change to the project management plan goes...
109  Project documents that may be updated as a res...
110  Organizational process assets that are updated...

                                              Keywords  \
0    [tailoring project risk, shaping project strat...
1    [effectiveness determines project, project nec...
2                                                   []
3    [project charter document, section project cha...
4    [component influence plan, plan taken consider...
..                                                 ...
106  [project risk management, work performance inf...
107  [plan change request, change request include, ...
108  [change project management, organization chang...
109  [project document updated, risk report updated...
110  [process asset updated, updated result monitor...

                                              Relation reference links
0    [{'head': 'risk management', 'type': 'studies'...      None  None
1    [{'head': 'Plan Risk Management', 'type': 'use...      None  None
2    [{'head': 'World Heritage Site', 'type': 'main...      None  None
3    [{'head': 'requirements', 'type': 'part of', '...      None  None
4    [{'head': 'Project Risk Management', 'type': '...      None  None
..                                                 ...       ...   ...
106  [{'head': 'Work performance information', 'typ...      None  None
107  [{'head': 'Monitor Risks', 'type': 'facet of',...      None  None
108  [{'head': 'change control', 'type': 'facet of'...      None  None
109  [{'head': 'Assumption log', 'type': 'facet of'...      None  None
110  [{'head': 'risk register', 'type': 'use', 'tai...      None  None

[111 rows x 6 columns]

In [ ]:
df2['Description'][33]

'Perform Qualitative Risk Analysis is the process of prioritizing individual project risks for further analysis or actionby assessing their probability of occurrence and impact as well as other characteristics. The key benefit of thisprocess is that it focuses efforts on high-priority risks. This process is performed throughout the project. The inputs,tools and techniques, and outputs of the process are depicted in Figure 11-8. Figure 11-9 depicts the data flowdiagram for the process.NubPage 385Perform Qualitative Risk Analysis assesses the priority of identified individual project risks using their probability ofoccurrence, the corresponding impact on project objectives if the risks occur, and other factors. Such assessments aresubjective as they are based on perceptions of risk by the project team and other stakeholders. Effective assessmenttherefore requires explicit identification and management of the risk attitudes of key participants in the PerformQualitative Risk Analysis process. Risk perception introduces bias into the assessment of identified risks, so attention shouldbe paid to identifying bias and correcting for it. Where a facilitator is used to support the Perform Qualitative RiskAnalysis process, addressing bias is a key part of the facilitator’s role. An evaluation of the quality of the availableinformation on individual project risks also helps to clarify the assessment of each risk’s importance to the project.NubPage 386Perform Qualitative Risk Analysis establishes the relative priorities of individual project risks for Plan Risk Responses. Itidentifies a risk owner for each risk who will take responsibility for planning an appropriate risk response and ensuring thatit is implemented. Perform Qualitative Risk Analysis also lays the foundation for Perform Quantitative Risk Analysis if thisprocess is required.The Perform Qualitative Risk Analysis process is performed regularly throughout the project life cycle, as defined in therisk management plan. Often, in an agile development environment, the Perform Qualitative Risk Analysis process isconducted before the start of each iteration.'

In [ ]:
df2['Description'] = df2['Description'].str.replace('\n', '')
df2['Description'] = df2['Description'].str.replace('theProject', 'the Project')
df2['Description'] = df2['Description'].str.replace('◆', '-')

In [ ]:
pattern = r'Figure\d+-\d+'

# Nouveau motif à remplacer
new_pattern = r'Figure \\d+-\\d+'

# Remplacer le motif initial par le nouveau motif
df2['Description'] = df2['Description'].str.replace(pattern, new_pattern)
df2

,Concept,Description,Keywords,Relation,reference,links
0,11 project risk management,Project Risk Management includes the processes...,"[tailoring project risk, shaping project strat...","[{'head': 'risk management', 'type': 'studies'...",[11-1],None
1,11.1 plan risk management,Plan Risk Management is the process of definin...,"[effectiveness determines project, project nec...","[{'head': 'Plan Risk Management', 'type': 'use...",[11-3],None
2,11.1.1 plan risk management: inputs,,[],"[{'head': 'World Heritage Site', 'type': 'main...",[],None
3,11.1.1.1 project charter,Described in Section 4.1.3.1. The project char...,"[project charter document, section project cha...","[{'head': 'requirements', 'type': 'part of', '...",[],None
4,11.1.1.2 project management plan,Described in Section 4.2.3.1. In planning Proj...,"[component influence plan, plan taken consider...","[{'head': 'Project Risk Management', 'type': '...",[],None
...,...,...,...,...,...,...
106,11.7.3.1 work performance information,Described in Section 4.5.1.3. Work performance...,"[project risk management, work performance inf...","[{'head': 'Work performance information', 'typ...",[],None
107,11.7.3.2 change requests,Described in Section 4.3.3.4. The Monitor Risk...,"[plan change request, change request include, ...","[{'head': 'Monitor Risks', 'type': 'facet of',...",[],None
108,11.7.3.3 project management plan updates,Any change to the project management plan goes...,"[change project management, organization chang...","[{'head': 'change control', 'type': 'facet of'...",[],None
109,11.7.3.4 project documents updates,Project documents that may be updated as a res...,"[project document updated, risk report updated...","[{'head': 'Assumption log', 'type': 'facet of'...",[],None
110,11.7.3.5 organizational process assets updates,Organizational process assets that are updated...,"[process asset updated, updated result monitor...","[{'head': 'risk register', 'type': 'use', 'tai...",[],None

In [ ]:
from numpy.core.multiarray import empty
import re

def extraire_phrases_figure(texte):
    # Utiliser une expression régulière pour trouver les phrases commençant par "Figure"
    phrases_figure = re.findall(r'Figure \d+-\d+', texte)
    return phrases_figure

for i in range(len(df2)):
  empty_list = []
  phrases_figure = extraire_phrases_figure(df2['Description'][i])

# Afficher les phrases extraites
  for phrase in phrases_figure:
      phrase=phrase.replace("Figure ","")
      phrase=phrase.replace(" ","")
      empty_list.append(phrase)
      print(phrase)
  if(phrases_figure!=empty):
    df2['reference'][i]=empty_list

11-1
11-3
11-4
11-5
11-6
11-7
11-4
11-8
11-9
11-4
11-5
11-10
11-11
11-12
11-13
11-14
11-15
11-16
11-17
11-19
11-20
11-21

In [ ]:
phrases_figure = extraire_phrases_figure(df2['Description'][25])

In [ ]:
phrases_figure

['Figure 11-2', 'Figure 11-3']

In [ ]:
!pip install rouge
!pip install textacy
!pip install pdfplumber
!pip install rdflib
!pip install bert-score
!pip install autocorrect
!pip install sentence-transformers
!pip install faiss-cpu --no-cache

Requirement already satisfied: rouge in /usr/local/lib/python3.10/dist-packages (1.0.1)
Requirement already satisfied: six in /usr/local/lib/python3.10/dist-packages (from rouge) (1.16.0)
Requirement already satisfied: textacy in /usr/local/lib/python3.10/dist-packages (0.13.0)
Requirement already satisfied: cachetools>=4.0.0 in /usr/local/lib/python3.10/dist-packages (from textacy) (5.3.1)
Requirement already satisfied: catalogue~=2.0 in /usr/local/lib/python3.10/dist-packages (from textacy) (2.0.10)
Requirement already satisfied: cytoolz>=0.10.1 in /usr/local/lib/python3.10/dist-packages (from textacy) (0.12.2)
Requirement already satisfied: floret~=0.10.0 in /usr/local/lib/python3.10/dist-packages (from textacy) (0.10.4)
Requirement already satisfied: jellyfish>=0.8.0 in /usr/local/lib/python3.10/dist-packages (from textacy) (1.0.1)
Requirement already satisfied: joblib>=0.13.0 in /usr/local/lib/python3.10/dist-packages (from textacy) (1.3.2)
Requirement already satisfied: networkx>=2.7 in /usr/local/lib/python3.10/dist-packages (from textacy) (3.2)
Requirement already satisfied: numpy>=1.17.0 in /usr/local/lib/python3.10/dist-packages (from textacy) (1.23.5)
Requirement already satisfied: pyphen>=0.10.0 in /usr/local/lib/python3.10/dist-packages (from textacy) (0.14.0)
Requirement already satisfied: requests>=2.10.0 in /usr/local/lib/python3.10/dist-packages (from textacy) (2.31.0)
Requirement already satisfied: scipy>=1.8.0 in /usr/local/lib/python3.10/dist-packages (from textacy) (1.11.3)
Requirement already satisfied: scikit-learn>=1.0 in /usr/local/lib/python3.10/dist-packages (from textacy) (1.2.2)
Requirement already satisfied: spacy~=3.0 in /usr/local/lib/python3.10/dist-packages (from textacy) (3.6.1)
Requirement already satisfied: tqdm>=4.19.6 in /usr/local/lib/python3.10/dist-packages (from textacy) (4.66.1)
Requirement already satisfied: toolz>=0.8.0 in /usr/local/lib/python3.10/dist-packages (from cytoolz>=0.10.1->textacy) (0.12.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests>=2.10.0->textacy) (3.3.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests>=2.10.0->textacy) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests>=2.10.0->textacy) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests>=2.10.0->textacy) (2023.7.22)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn>=1.0->textacy) (3.2.0)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in /usr/local/lib/python3.10/dist-packages (from spacy~=3.0->textacy) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from spacy~=3.0->textacy) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /usr/local/lib/python3.10/dist-packages (from spacy~=3.0->textacy) (1.0.10)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /usr/local/lib/python3.10/dist-packages (from spacy~=3.0->textacy) (2.0.8)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /usr/local/lib/python3.10/dist-packages (from spacy~=3.0->textacy) (3.0.9)
Requirement already satisfied: thinc<8.2.0,>=8.1.8 in /usr/local/lib/python3.10/dist-packages (from spacy~=3.0->textacy) (8.1.12)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in /usr/local/lib/python3.10/dist-packages (from spacy~=3.0->textacy) (1.1.2)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in /usr/local/lib/python3.10/dist-packages (from spacy~=3.0->textacy) (2.4.8)
Requirement already satisfied: typer<0.10.0,>=0.3.0 in /usr/local/lib/python3.10/dist-packages (from spacy~=3.0->textacy) (0.9.0)
Requirement already satisfied: pathy>=0.10.0 in /usr/local/lib/python3.10/dist-packages (from spacy~=3.0->textacy) (0.10.2)
Requirement already satisfied: smart-open<7.0.0,>=5.2.1 in /usr/local/lib/python3.10/dist-packages (from spacy~=3.0->textacy) (6.4.0)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 in /usr/local/lib/python3.10/dist-packages (from spacy~=3.0->textacy) (1.10.13)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from spacy~=3.0->textacy) (3.1.2)
Requirement already satisfied: setuptools in /usr/local/lib/python3.10/dist-packages (from spacy~=3.0->textacy) (67.7.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from spacy~=3.0->textacy) (23.2)
Requirement already satisfied: langcodes<4.0.0,>=3.2.0 in /usr/local/lib/python3.10/dist-packages (from spacy~=3.0->textacy) (3.3.0)
Requirement already satisfied: typing-extensions>=4.2.0 in /usr/local/lib/python3.10/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy~=3.0->textacy) (4.5.0)
Requirement already satisfied: blis<0.8.0,>=0.7.8 in /usr/local/lib/python3.10/dist-packages (from thinc<8.2.0,>=8.1.8->spacy~=3.0->textacy) (0.7.11)
Requirement already satisfied: confection<1.0.0,>=0.0.1 in /usr/local/lib/python3.10/dist-packages (from thinc<8.2.0,>=8.1.8->spacy~=3.0->textacy) (0.1.3)
Requirement already satisfied: click<9.0.0,>=7.1.1 in /usr/local/lib/python3.10/dist-packages (from typer<0.10.0,>=0.3.0->spacy~=3.0->textacy) (8.1.7)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->spacy~=3.0->textacy) (2.1.3)
Requirement already satisfied: pdfplumber in /usr/local/lib/python3.10/dist-packages (0.10.2)
Requirement already satisfied: pdfminer.six==20221105 in /usr/local/lib/python3.10/dist-packages (from pdfplumber) (20221105)
Requirement already satisfied: Pillow>=9.1 in /usr/local/lib/python3.10/dist-packages (from pdfplumber) (9.4.0)
Requirement already satisfied: pypdfium2>=4.18.0 in /usr/local/lib/python3.10/dist-packages (from pdfplumber) (4.22.0)
Requirement already satisfied: charset-normalizer>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from pdfminer.six==20221105->pdfplumber) (3.3.0)
Requirement already satisfied: cryptography>=36.0.0 in /usr/local/lib/python3.10/dist-packages (from pdfminer.six==20221105->pdfplumber) (41.0.4)
Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.10/dist-packages (from cryptography>=36.0.0->pdfminer.six==20221105->pdfplumber) (1.16.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.10/dist-packages (from cffi>=1.12->cryptography>=36.0.0->pdfminer.six==20221105->pdfplumber) (2.21)
Requirement already satisfied: rdflib in /usr/local/lib/python3.10/dist-packages (7.0.0)
Requirement already satisfied: isodate<0.7.0,>=0.6.0 in /usr/local/lib/python3.10/dist-packages (from rdflib) (0.6.1)
Requirement already satisfied: pyparsing<4,>=2.1.0 in /usr/local/lib/python3.10/dist-packages (from rdflib) (3.1.1)
Requirement already satisfied: six in /usr/local/lib/python3.10/dist-packages (from isodate<0.7.0,>=0.6.0->rdflib) (1.16.0)
Requirement already satisfied: bert-score in /usr/local/lib/python3.10/dist-packages (0.3.13)
Requirement already satisfied: torch>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from bert-score) (2.1.0+cu118)
Requirement already satisfied: pandas>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from bert-score) (1.5.3)
Requirement already satisfied: transformers>=3.0.0 in /usr/local/lib/python3.10/dist-packages (from bert-score) (4.34.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from bert-score) (1.23.5)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from bert-score) (2.31.0)
Requirement already satisfied: tqdm>=4.31.1 in /usr/local/lib/python3.10/dist-packages (from bert-score) (4.66.1)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.10/dist-packages (from bert-score) (3.7.1)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.10/dist-packages (from bert-score) (23.2)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.0.1->bert-score) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.0.1->bert-score) (2023.3.post1)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from torch>=1.0.0->bert-score) (3.12.4)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.10/dist-packages (from torch>=1.0.0->bert-score) (4.5.0)
Requirement already satisfied: sympy in /usr/local/lib/python3.10/dist-packages (from torch>=1.0.0->bert-score) (1.12)
Requirement already satisfied: networkx in /usr/local/lib/python3.10/dist-packages (from torch>=1.0.0->bert-score) (3.2)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch>=1.0.0->bert-score) (3.1.2)
Requirement already satisfied: fsspec in /usr/local/lib/python3.10/dist-packages (from torch>=1.0.0->bert-score) (2023.6.0)
Requirement already satisfied: triton==2.1.0 in /usr/local/lib/python3.10/dist-packages (from torch>=1.0.0->bert-score) (2.1.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.16.4 in /usr/local/lib/python3.10/dist-packages (from transformers>=3.0.0->bert-score) (0.17.3)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from transformers>=3.0.0->bert-score) (6.0.1)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.10/dist-packages (from transformers>=3.0.0->bert-score) (2023.6.3)
Requirement already satisfied: tokenizers<0.15,>=0.14 in /usr/local/lib/python3.10/dist-packages (from transformers>=3.0.0->bert-score) (0.14.1)
Requirement already satisfied: safetensors>=0.3.1 in /usr/local/lib/python3.10/dist-packages (from transformers>=3.0.0->bert-score) (0.4.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->bert-score) (1.1.1)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.10/dist-packages (from matplotlib->bert-score) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->bert-score) (4.43.1)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->bert-score) (1.4.5)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->bert-score) (9.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->bert-score) (3.1.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->bert-score) (3.3.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->bert-score) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->bert-score) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->bert-score) (2023.7.22)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.1->pandas>=1.0.1->bert-score) (1.16.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->torch>=1.0.0->bert-score) (2.1.3)
Requirement already satisfied: mpmath>=0.19 in /usr/local/lib/python3.10/dist-packages (from sympy->torch>=1.0.0->bert-score) (1.3.0)
Requirement already satisfied: autocorrect in /usr/local/lib/python3.10/dist-packages (2.6.1)
Requirement already satisfied: sentence-transformers in /usr/local/lib/python3.10/dist-packages (2.2.2)
Requirement already satisfied: transformers<5.0.0,>=4.6.0 in /usr/local/lib/python3.10/dist-packages (from sentence-transformers) (4.34.1)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from sentence-transformers) (4.66.1)
Requirement already satisfied: torch>=1.6.0 in /usr/local/lib/python3.10/dist-packages (from sentence-transformers) (2.1.0+cu118)
Requirement already satisfied: torchvision in /usr/local/lib/python3.10/dist-packages (from sentence-transformers) (0.16.0+cu118)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from sentence-transformers) (1.23.5)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.10/dist-packages (from sentence-transformers) (1.2.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.10/dist-packages (from sentence-transformers) (1.11.3)
Requirement already satisfied: nltk in /usr/local/lib/python3.10/dist-packages (from sentence-transformers) (3.8.1)
Requirement already satisfied: sentencepiece in /usr/local/lib/python3.10/dist-packages (from sentence-transformers) (0.1.99)
Requirement already satisfied: huggingface-hub>=0.4.0 in /usr/local/lib/python3.10/dist-packages (from sentence-transformers) (0.17.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.4.0->sentence-transformers) (3.12.4)
Requirement already satisfied: fsspec in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.4.0->sentence-transformers) (2023.6.0)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.4.0->sentence-transformers) (2.31.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.4.0->sentence-transformers) (6.0.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.4.0->sentence-transformers) (4.5.0)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.4.0->sentence-transformers) (23.2)
Requirement already satisfied: sympy in /usr/local/lib/python3.10/dist-packages (from torch>=1.6.0->sentence-transformers) (1.12)
Requirement already satisfied: networkx in /usr/local/lib/python3.10/dist-packages (from torch>=1.6.0->sentence-transformers) (3.2)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch>=1.6.0->sentence-transformers) (3.1.2)
Requirement already satisfied: triton==2.1.0 in /usr/local/lib/python3.10/dist-packages (from torch>=1.6.0->sentence-transformers) (2.1.0)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.10/dist-packages (from transformers<5.0.0,>=4.6.0->sentence-transformers) (2023.6.3)
Requirement already satisfied: tokenizers<0.15,>=0.14 in /usr/local/lib/python3.10/dist-packages (from transformers<5.0.0,>=4.6.0->sentence-transformers) (0.14.1)
Requirement already satisfied: safetensors>=0.3.1 in /usr/local/lib/python3.10/dist-packages (from transformers<5.0.0,>=4.6.0->sentence-transformers) (0.4.0)
Requirement already satisfied: click in /usr/local/lib/python3.10/dist-packages (from nltk->sentence-transformers) (8.1.7)
Requirement already satisfied: joblib in /usr/local/lib/python3.10/dist-packages (from nltk->sentence-transformers) (1.3.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn->sentence-transformers) (3.2.0)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in /usr/local/lib/python3.10/dist-packages (from torchvision->sentence-transformers) (9.4.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->torch>=1.6.0->sentence-transformers) (2.1.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub>=0.4.0->sentence-transformers) (3.3.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub>=0.4.0->sentence-transformers) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub>=0.4.0->sentence-transformers) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub>=0.4.0->sentence-transformers) (2023.7.22)
Requirement already satisfied: mpmath>=0.19 in /usr/local/lib/python3.10/dist-packages (from sympy->torch>=1.6.0->sentence-transformers) (1.3.0)
Requirement already satisfied: faiss-cpu in /usr/local/lib/python3.10/dist-packages (1.7.4)

In [ ]:
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

# Remplacez 'facebook/bart-large-cnn' par le modèle que vous souhaitez utiliser
model_name = "facebook/bart-large-cnn"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSeq2SeqLM.from_pretrained(model_name)

Downloading (…)lve/main/config.json:   0%|          | 0.00/1.58k [00:00<?, ?B/s]

Downloading (…)olve/main/vocab.json:   0%|          | 0.00/899k [00:00<?, ?B/s]

Downloading (…)olve/main/merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

Downloading (…)/main/tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

Downloading pytorch_model.bin:   0%|          | 0.00/1.63G [00:00<?, ?B/s]

Downloading (…)neration_config.json:   0%|          | 0.00/363 [00:00<?, ?B/s]

In [ ]:
def generate_better_description(description):
    if not pd.isnull(description) and description != "":
        input_text = description
        input_ids = tokenizer.encode(input_text, return_tensors="pt", max_length=1024, truncation=True, padding=True)
        output = model.generate(input_ids, max_length=100, num_return_sequences=1, no_repeat_ngram_size=2, top_k=50, top_p=0.95)
        # Extrait la description améliorée du résultat de la génération
        description_amelioree = tokenizer.decode(output[0], skip_special_tokens=True)
        return description_amelioree
    else:
        # Gérez le cas où la description est manquante
        return description

df2['DescriptionAmelioree'] = df2['Description'].apply(generate_better_description)
df2

,Concept,Description,Keywords,DescriptionAmelioree
0,11 PROJECT RISK MANAGEMENT,Project Risk Management includes the processes...,"[tailoring project risk, shaping project strat...",Project Risk Management includes the processes...
1,11.1 PLAN RISK MANAGEMENT,Plan Risk Management is the process of definin...,"[effectiveness determines project, project nec...",Plan Risk Management is the process of definin...
2,11.1.1 PLAN RISK MANAGEMENT: INPUTS,None,[],None
3,11.1.1.1 PROJECT CHARTER,Described in Section 4.1.3.1. The project char...,"[project charter document, section project cha...",Described in Section 4.1.3. The project charte...
4,11.1.1.2 PROJECT MANAGEMENT PLAN,Described in Section 4.2.3.1. In planning Proj...,"[component influence plan, plan taken consider...",Described in Section 4.2.3. In planning Projec...
...,...,...,...,...
106,11.7.3.1 WORK PERFORMANCE INFORMATION,Described in Section 4.5.1.3. Work performance...,"[project risk management, work performance inf...",Work performance information includes informat...
107,11.7.3.2 CHANGE REQUESTS,Described in Section 4.3.3.4. The Monitor Risk...,"[plan change request, change request include, ...",The Monitor Risks process may result in a chan...
108,11.7.3.3 PROJECT MANAGEMENT PLAN UPDATES,Any change to the project management plan goes...,"[change project management, organization chang...",Any change to the project management plan goes...
109,11.7.3.4 PROJECT DOCUMENTS UPDATES,Project documents that may be updated as a res...,"[project document updated, risk report updated...",Project documents that may be updated as a res...
110,11.7.3.5 ORGANIZATIONAL PROCESS ASSETS UPDATES,Organizational process assets that are updated...,"[process asset updated, updated result monitor...",Organizational process assets that are updated...